### ISSUE TITLE
Command Block Non-Visible (1.8.9)

### ISSUE THREAD

**Issue by Michael1297** [ViaVersion/ViaRewind#100]
client 1.8.9
server 1.12.2

> https://dump.viaversion.com/be2fc43519d0d92a6d11ff9cc73e2b6d732505b5c37cabd38e331238560b2a9e

![default](https://user-images.githubusercontent.com/38764610/47160847-749dfa00-d2f9-11e8-96c7-8b35599055ca.png)

**Comment by ArtelGG** [comment]
This is ViaRewind, not ViaVersion.
