### ISSUE TITLE
Server kick randomly player to lobby.

### ISSUE THREAD

**Issue by YONONH** [ViaVersion/ViaRewind#103]
Hi! I have some problem I'm using 1.8.8 Version and Bungeecord and I got this error
https://pastebin.com/8vjEeV7y
It will kick player in my server.
How do i know, this plugin's making?
because I tried to remove Viarewind and put protocol support instead then, this problem don't happen again but i want to use viarewind It can use with hologram display.

**Comment by Gerrygames** [comment]
ViaRewind/ViaVersion shouldn't sent any empty packets. If so, the issue will be down to ViaVersion.
Afaik you can disable the empty packet check if you are using Waterfall as a proxy.
