### ISSUE TITLE
Incompatible SkinsRestorer plugin

### ISSUE THREAD

**Issue by cqzhcs** [ViaVersion/ViaRewind#111]
Skin not displayed to players in 1.7.x

**Comment by Gerrygames** [comment]
Did you test without SkinsRestorer? Does this only occur on 1.7.x? Are you using any proxy (BungeeCord)? Also can you provide /viaversion dump?

**Comment by cqzhcs** [comment]
if without SkinsRestorer Unable to displayed Skin.
not use any proxy.
https://dump.viaversion.com/8091a2e12ed0398248ff96097293e334d94de6c29ddd1dd4e0a35db8a509911b
