### ISSUE TITLE
1.7 clients crashing when loading the Bossbar

### ISSUE THREAD

**Issue by Stualyttle** [ViaVersion/ViaRewind#115]
My 1.7 clients are crashing when they are loading the Bossbar. The Whitherskull is chashing them.
Could there be a option to disable it for 1.7 users only?

Thank you!

**Comment by Gerrygames** [comment]
Could you provide the crash log?

**Comment by Stualyttle** [comment]
The error is the same for both 1.7.2 and 1.7.10 I've used 1.7.10 and I've added a gif, a pasted the error (verry short xP) And the long error. 

GIF:
![fHRdOGe3A9](https://user-images.githubusercontent.com/27898452/58588817-d09e0900-8260-11e9-903b-6e71e8bd8e7d.gif)

Short: 
`The game crashed whilst ticking entity`
`Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte`

Full: https://pastebin.com/NSVqZtkN
