### ISSUE TITLE
[Suggestion]  Delay message.

### ISSUE THREAD

**Issue by BrettplayMC** [ViaVersion/ViaRewind#117]
The ability to delay this message on join by seconds/ticks would be nice:

> versioninfo:
  active: true
  max-version: 47
  interval: JOIN
  message: '&eUnchainedMC &7> &fWe are running running Minecraft %version%. The best
    gameplay experience is only guaranteed if you are using this version.'

**Comment by Logics4** [comment]
This behavior can be achieved with the [VersionInfo](https://www.spigotmc.org/resources/versioninfo.47999/) plugin.

**Comment by Logics4** [comment]
This should go to [ViaRewind Legacy Support's GitHub Issue Tracker](https://github.com/Gerrygames/ViaRewind-Legacy-Support), as this feature is not provided by ViaRewind itself but by this addon.
