### ISSUE TITLE
Randomly Timing Out Players

### ISSUE THREAD

**Issue by JoeDon16** [ViaVersion/ViaRewind#119]
Hey,

Using ViaRewind 1.4.0 and ViaVersion 2.1.1 on a 1.9.4 server.

Randomly, I BELIEVE when a 1.8 user joins, there's a chance everybody online is timed out. Either timed out, or kicked. The server never crashes, just seems to time out and kick everyone.

There are also no visible errors in console I don't believe.

What could be causing this? It really sucks.

Edit: Am also getting it on individual players (it looks like) such as myself, where everything freezes for me but I can still send messages/my movements show to other players. Really weird. Like I can send all actions but cant receive any including my own (not seeing own chat messages but others see it)

**Comment by JoeDon16** [comment]
During PvP, it seemed to have an increased effect, and also kicked EVERYONE online. What the fuck?

**Comment by Gerrygames** [comment]
ViaVersion / ViaRewind does nothing for players connected with the native version. So this will almost certainly not be related to ViaRewind.

**Comment by JoeDon16** [comment]
Majority of my players are behind my server version, on 1.8 (servers 1.9). It literally can't be anything else, nothing else handles connections.

**Comment by toxamin** [comment]
... does it happen with only the via plugins mentioned installed?

**Comment by JoeDon16** [comment]
> ... does it happen with only the via plugins mentioned installed?

No, I wouldn't be able to test that. But before on my old server with older versions of each plugin, this was not an issue. Immediately upon upgrading to add 1.14 support on my new server however, this started happening. Is there any settings I can change or do about this?
