### ISSUE TITLE
1.8 Players Stuck when Teleported

### ISSUE THREAD

**Issue by LinsaFTW** [ViaVersion/ViaRewind#120]
Sometimes when teleporting a player many times (in this case with aac movement system) they get frozen in the air sometimes.

They can move on their screen, but the other players see them like they are frozen in the air until they reconnect or teleport again.

Using 1.12.2 Spigot.

**Comment by DavidVioMC** [comment]
Having same issue

**Comment by LinsaFTW** [comment]
I can confirm. Same issue. Running Spigot 1.12.2 - This happens on 1.4.3 and on. Doesnt happen on 1.8.8 server.

![image](https://user-images.githubusercontent.com/25271111/79278800-dacdf380-7e82-11ea-8ea1-b68bced633cf.png)
