### ISSUE TITLE
XP Orbs non visible for 1.7

### ISSUE THREAD

**Issue by InfinityZ25** [ViaVersion/ViaRewind#121]
Whenever an XP Orb is supposed to exist it just doesn't if you're on 1.7, though if you walk by it you do pick it up.

**Comment by Bonista** [comment]
@Gerrygames 
I can confirm the buggy nature of XP orbs on a 1.8.8 server:
Expect behaviour (on 1.8.8) is shown first, then on 1.7.10 in this gif:
https://imgur.com/jTWkUiV

**Comment by Gerrygames** [comment]
Yeah this seems to be an issue within the 1.7 client.
