### ISSUE TITLE
1.7 team related error

### ISSUE THREAD

**Issue by MedicOP** [ViaVersion/ViaRewind#122]
Players are unable to connect using Minecraft 1.7 client. Travertine (BungeeCord fork that allows 1.7) shows this error:

![Screenshot_1](https://user-images.githubusercontent.com/18251099/62140508-5e42b700-b2eb-11e9-9c69-f98d4547861e.png)

On the Spigot side it just shows this:
```Blabla lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe```

I am using Spigot 1.8. Is this a Travertine or a ViaRewind problem?

**Comment by ItzVinex** [comment]
I can confirm that 1.7 players are getting crashed due to failing to be removed from a Team.
