### ISSUE TITLE
hit registration and item use issues with thrown potions

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaRewind#123]
1.8 server with 1.7 client

xp potions not showing: https://gyazo.com/68685b904fc7ecd1cbc483d8f78f7604

potions thrown very quickly one after the other sometimes dont register despite being removed from inventory https://youtu.be/_GuDUHEVRmg

**Comment by FlorianMichael** [comment]
Also happens with a 1.8 client on a 1.8 server, so is not a ViaRewind issue.
