### ISSUE TITLE
DecoderException for FALLING_DUST particle in 1.9.4

### ISSUE THREAD

**Issue by Nubebuster** [ViaVersion/ViaRewind#125]
When a 1.9.4 player sees FALLING_DUST in a 1.12 server, they get kicked:
"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/34 (gt) was larger than I expected, found 1 bytes extra whilst reading packet 34

**Comment by Nubebuster** [comment]
And in 1.8.9 also:
"... 0/42 (gr) was larger, found 1 bytes extra ... packet 42

**Comment by Gerrygames** [comment]
This is a ViaBackwards issue.
