### ISSUE TITLE
1.8 - 1.8.9 Players Rubberbanding

### ISSUE THREAD

**Issue by Hatntops** [ViaVersion/ViaRewind#132]
Very recently many player complaints have came in on my server about severe rubber banding (Once you move you instantly get teleported back to the original position). It seems to be accelerated but not caused by blocks that aren't an entire block or if the player is getting moved by water. This does not happen on any other version except 1.8 - 1.8.9. The server is running spigot 1.12.2 
Any help would be greatly appreciated.
Thanks!

**Comment by BrunoSilvaFreire** [comment]
I can replicate this issue. Running on a custom built 1.15.2 Paper server.
[Here is the dump.](https://dump.viaversion.com/54a05c66ae105c148cb26b8499424cf772353f5a8f80218b562f794ec4c71d69)

In my case this happens whenever a 1.8.9 player tries to climb a wooden ladder.

I will try to examine this and create a pull request, but it would be nice to have a maintainer comment on this or point a direction or general idea of where the issue may reside

**Comment by Gerrygames** [comment]
The collision boxes of some blocks are fixed in ViaRewind Legacy Support.
