### ISSUE TITLE
Wither visible to users

### ISSUE THREAD

**Issue by camdenorrb** [ViaVersion/ViaRewind#133]
The current implementation of bossbar appears to make the wither follow the cursor within the player's view, this has been annoying players on our server and there is probably a better way to do this as most other servers running 1.8 don't have this issue.

![image](https://user-images.githubusercontent.com/5360339/68081758-a258c280-fdd8-11e9-8746-523fb2225bd7.png)

**Comment by camdenorrb** [comment]
Alright, this is an issue with wither health

**Comment by Gerrygames** [comment]
This is a clientside issue. The client renders the withers shield even though the wither is invisible.

**Comment by camdenorrb** [comment]
You could just add a configuration option that makes it so the wither's health doesn't change on these versions?

**Comment by NovaPixell** [comment]
Hi, I have this issue.
This is a clientside issue? Not fixable via plugin?
![photo_2023-01-05_18-39-01](https://user-images.githubusercontent.com/55632135/210857632-4fc94d97-552c-4b0a-9cd4-ff0e5b2940a0.jpg)
