### ISSUE TITLE
No item pickup and block place sounds

### ISSUE THREAD

**Issue by MGlolenstine** [ViaVersion/ViaRewind#151]
I'm using 1.8.9 client on 1.14.4 server with ViaVersion 3.0.0-SNAPSHOT, ViaBackwards 3.0.0-SNAPSHOT and ViaRewind 1.5.0-SNAPSHOT.

I found these two issues #59 and [#241](https://github.com/ViaVersion/ViaVersion/issues/241), but it doesn't really show how to solve anything ...

**Comment by Gerrygames** [comment]
As already stated in the linked issue #59 there is a fix for that in ViaRewind Legacy Support.
