### ISSUE TITLE
1.8 can't climb a ladder

### ISSUE THREAD

**Issue by ypxo-mc** [ViaVersion/ViaRewind#155]
PaperSpigot 1.15.2 build 137
ViaVersion-3.0.0-SNAPSHOT build 41
ViaBackwards-3.0.0-SNAPSHOT build 87
viarewind-all-1.5.0-SNAPSHOT build 94

Players with Minecraft 1.8 are stuck on a ladder.

**Comment by krusic22** [comment]
You also need ViaRewind-Legacy-Support.
