### ISSUE TITLE
Holograms in 1.8 clients appear lower than 1.9+

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaRewind#156]
Describe the bug, provide any errors
On all my server versions (1.15.2 and 1.8) holograms appear lower on 1.8 clients as apposed to where they are positioned in higher versions

How can we reproduce it?

Login on 1.9+
Create a hologram
Login on 1.8, the hologram is lower
Expected behaviour
Holograms should be at the same height

ViaVersion Dump:
https://dump.viaversion.com/74335738c18d2bb24dbb6e936ee88d8bae046dc89d50a3d80eabd9848ae4d21b

**Comment by JHarris12345** [comment]
Ok so here is the image of a hologram made with Holographic displays on a 1.14.4 client with the server versions 1.15.2 (latest paper jar). Notice the hologram height
![image](https://user-images.githubusercontent.com/46936647/77229089-9a30d200-6b83-11ea-9b20-0c39e5642a27.png)

Here is the same image but taken on a 1.8 client
![image](https://user-images.githubusercontent.com/46936647/77229125-c9474380-6b83-11ea-9cb8-72288e6fe517.png)


Dump:
https://dump.viaversion.com/11809c5cec1c6fd9be13b2c7de1d6d1e3d5bea2996fa47e4dda52f92388bc948

**Comment by JHarris12345** [comment]
Here is the screenshots on a 1.9 client (looks like this is fine):
![image](https://user-images.githubusercontent.com/46936647/77229825-ee3db580-6b87-11ea-8690-8a4486306b3a.png)

And 1.11 which also looks fine: 
![image](https://user-images.githubusercontent.com/46936647/77229834-01e91c00-6b88-11ea-8146-287a7790d199.png)


Seems like just 1.8 clients on 1.15.2 server is too high. And also my Y offset is -4.9 or something. It seems this value isnt doing anything as 1.9+ clients are fine and 1.8 clients are too high

**Comment by Cecer** [comment]
While not directly the problem here, it's worth noting that the nameplate of marker armour stands is shown at the feet of the armour stand in early 1.8 versions but above the head in later 1.8 versions. As both versions use the same protocol version it is not really possible to detect and compensate between these two versions.

**Comment by JHarris12345** [comment]
Well im pretty sure every holograms plugin uses armor stands since I just tried 2 more plugins and they have the same issue. Ive seen many servers without this issue so what would be the way to go about fixing. Theres 100% nothing viaversion can patch here? Like making holograms on armor stands at the base again?

**Comment by Golicraft** [comment]
Hey. I have the exact same issue

**Comment by SladeHazard** [comment]
try enabling fix hologram in viaversion's config!

**Comment by Gerrygames** [comment]
Is this on a 1.8 or 1.8.9 client? 1.8.x clients are not distinguishable by the server and I will always assume a 1.8.9 client.

**Comment by LBoomsky** [comment]
issue persists sorry for necropost 🥺

**Comment by LBoomsky** [comment]
nvm guys so sorry gerrygames is right; this is a 1.8.0 exclusive issue! Interestingly; holograms are completely missing on 1.8.1 for some reason! 😭🙏
