### ISSUE TITLE
Lily pads issue

### ISSUE THREAD

**Issue by MarcelDutko** [ViaVersion/ViaRewind#158]
Hello,
When you walk on a lily pad on 1.12.2 server with ViaRewind and ViaBackwards, its pretty glitchy. Lags you and makes not able to move.
Regards

**Comment by krusic22** [comment]
Did you install ViaRewind Legacy Support?

**Comment by MarcelDutko** [comment]
No, now I did and it works awesome.
Thank you for help and the godly fast support :)
Regards
