### ISSUE TITLE
1.8.9 client at 1.15.2 server

### ISSUE THREAD

**Issue by MarcelDutko** [ViaVersion/ViaRewind#159]
in 1.15.2 you can put chests right next each other. while logging on in 1.8.9 The chests are invisible but still act as if they're their.

https://cdn.discordapp.com/attachments/463810024708374558/702264806727745656/2020-04-21_17.09.19.png

**Comment by Gerrygames** [comment]
Nothing I can do about that. That's just a limitation in the 1.8 client.

**Comment by MarcelDutko** [comment]
actually can do, enderchest?

**Comment by Gerrygames** [comment]
Yeah but that looks kinda ass

**Comment by MarcelDutko** [comment]
it does, but players won't be confused at least

**Comment by Gerrygames** [comment]
Oh yes they will. _Looks at ProtocolSupport_
