### ISSUE TITLE
Hologram flickering

### ISSUE THREAD

**Issue by toxamin** [ViaVersion/ViaRewind#161]
Whenever holograms are updated, they flicker for 1.7 clients. This does not happen on any other version.
Here's what I mean: [https://imgur.com/a/gAoWmR4](https://imgur.com/a/gAoWmR4)

**Comment by Xernium** [comment]
That happens because the substitute entity for invisible armorstands needs to be despawned and respawned to update the *hologram*. Can’t really be fixed due to the limitations this poses and the way the Via plugins work.

**Comment by toxamin** [comment]
right, not sure what you're on about, the entity does not need to be despawned and respawned to update it's name...

**Comment by Xernium** [comment]
Feel free to propose a better solution for this then please. By just updating metadata the substitute either bugs out or becomes visible in my testing.

**Comment by Bonista** [comment]
> 
> 
> Feel free to propose a better solution for this then please. By just updating metadata the substitute either bugs out or becomes visible in my testing.

Commenting out updateLocation(); in the updateState(); method in the ArmorStandReplacement function seems to have no issues with holograms... what do you to do to see them bug out or become visible?

**Comment by Kichura** [comment]
Fixed.
