### ISSUE TITLE
1.7 PLAYERS GET KICKED

### ISSUE THREAD

**Issue by SladeHazard** [ViaVersion/ViaRewind#162]
How many times PLLZZ 1.7 players are getting kicked for this:
Error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte
even happens when their view distance is 3 mostly when theyre getting teleported and switching world!! HOWEVER THIS DOES NOT happen with protocolsupport so don't make a excuse please!!! i'm using latest viarewind-dev! 1.12.2 server

**Comment by Gerrygames** [comment]
Tracked in #174

**Comment by SladeHazard** [comment]
What? @Gerrygames why did you close this this error is because viarewind doesn't support duels hologram extension & holoplots I can provide the crash logs it's completely different that #174
