### ISSUE TITLE
StorageDrawers, MalisisDoor and MalisisCore doesn't work with ViaRewind

### ISSUE THREAD

**Issue by MichelBaie** [ViaVersion/ViaRewind#163]
Hello,
I recently wanted to get back into a Minecraft server project. Only after restoring a backup I realized I couldn't connect to my vanilla server anymore.
I have :
Bungeecord: Tavertine
Bungeecord Plugins: ViaVersion-Abstraction ViaBackwards-Abstraction ViaRewind-Dev
Minecraft Server: Paperspigot 1.8.8
Minecraft Mod: StorageDrawers-1.7.10-1.10.9, Malisisdoors-1.7.10-0.14.3, MalisisCore-1.7.10-0.14.3

Do you have solutions to this problem? Can you patch it?
https://imgur.com/a/3EFCYUX

**Comment by Gerrygames** [comment]
Please provide the whole error from the server log and not a screenshot.
