### ISSUE TITLE
Bow animation is not visible (not fixed since 2018?)

### ISSUE THREAD

**Issue by SaltyPotata** [ViaVersion/ViaRewind#164]
Server version: 1.13.2 paperspigot b655
Using: Viaversion, Viarewind, ViaBackwards

When you pull up a bow higher then the server version (for example in 1.15.2) then the player who is in under the server version (for example 1.12.2) can't see the bow pull animation.

Same issue like here: https://github.com/ViaVersion/ViaRewind/issues/64

**Comment by Gerrygames** [comment]
Duplicate #64

**Comment by Govindass** [comment]
I find it funny how this issue being 164 is duplicate of issue 64
