### ISSUE TITLE
1.7 Game Crash

### ISSUE THREAD

**Issue by ShepMC** [ViaVersion/ViaRewind#165]
Hey, I use a 1.8 tacospigot server, however when i have all of the newest abstraction versions of the via series (version, backwards and rewind) and try to connect to the server it crashes my minecraft, not the server, just the minecraft. I have the same viaversion setup on my lobby which seems to work (thats a paperspigot) but then its the same with my 1.15 server that i want 1.7 support on, just kills my minecraft and gives an error: ---- Minecraft Crash Report ----
// Don't do that.

Time: 23/05/20 11:03
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at bac.d(SourceFile:169)
	at bjb.a(SourceFile:1173)
	at id.a(SourceFile:100)
	at id.a(SourceFile:12)
	at ej.a(SourceFile:174)
	at bje.e(SourceFile:212)
	at bao.p(SourceFile:1306)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)

But then looking further into it, it describes every line of the holograms i have near, but then on the 1.15 server i have no holos and its the same so nothing adds up.

**Comment by Seanoo1** [comment]
don't use abstraction build on 1.12.2 and lower Server, and use paperspigot.

**Comment by SladeHazard** [comment]
> don't use abstraction build on 1.12.2 and lower Server, also you need viaversion plugin.

Hi what's your discord and what plugins do we need exactly each of them

**Comment by ShepMC** [comment]
I managed to fix this. I used abstraction build still but i had to use flamecord instead. Then it all worked.

**Comment by SladeHazard** [comment]
> I managed to fix this. I used abstraction build still but i had to use flamecord instead. Then it all worked.

lmfao?! wdym flamecord has nothing to do with this you're not suppose to run via plugins on bungeecord

**Comment by SladeHazard** [comment]
> I managed to fix this. I used abstraction build still but i had to use flamecord instead. Then it all worked.

Also you probably didn't fix it then this is caused randomly when your server ticks hologram and player at the same time you just didn't thorougly tested it again your players will have issue with this again here is my crash report; https://pastebin.com/Yju4GENX
