### ISSUE TITLE
Can not load

### ISSUE THREAD

**Issue by notImAle** [ViaVersion/ViaRewind#169]
I got via version 3.0 and via backwords 3.0 and it says that it can't load viarewind

**Comment by Lmmb74** [comment]
You are using the DEV branch right? 'Cause that's the one you should use along the Abstraction branch of ViaVersion (ViaBackwards as well).

**Comment by notImAle** [comment]
> You are using the DEV branch right? 'Cause that's the one you should use along the Abstraction branch of ViaVersion (ViaBackwards as well).

Already changed and now it load and i try to join a spigot 1.13 in 1.8 but it won't work

**Comment by Jo0001** [comment]
Please run `/viaversion dump` in-game or in your console and provide us with the link, it gives us useful information about your server.

**Comment by Lmmb74** [comment]
> 
> 
> > You are using the DEV branch right? 'Cause that's the one you should use along the Abstraction branch of ViaVersion (ViaBackwards as well).
> 
> Already changed and now it load and i try to join a spigot 1.13 in 1.8 but it won't work

Hmmm, wierd. Just tested it with Paper 1.15.2 ([build #350](https://papermc.io/api/v1/paper/1.15.2/350/download)) and it worked. Also tested with the latest build of Spigot 1.13.2, and worked as well.

**Comment by Lmmb74** [comment]
@notImAle So were you able to solve it? If not, you should post the dump.
