### ISSUE TITLE
Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaRewind#173]
Error: https://pastebin.com/Xm8PAdR7

PaperSpigot: 1.12.2 (latest)
ViaRewind Build - request -> 45

**Comment by Gerrygames** [comment]
Update all your Via plugins to the latest version

**Comment by Gerrygames** [comment]
Ah nvm, Kenny found the issue. Should be fixed in a few minutes.
