### ISSUE TITLE
Enchant table enchants not showing level.

### ISSUE THREAD

**Issue by LilNermy** [ViaVersion/ViaRewind#175]
![viaversion](https://user-images.githubusercontent.com/65257005/86545686-430dfd80-bee5-11ea-87f0-69478fe5a3e8.PNG)
picture of issue ^^
that problem happens with all enchants not just the one in the picture

**Comment by Venalia-network** [comment]
Update ?? plz

**Comment by jcuesta8** [comment]
I have the same problem

**Comment by John0oe** [comment]
I still have this issue, any fix yet?

**Comment by FlorianMichael** [comment]
Fixed in latest dev build on https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/
