### ISSUE TITLE
Anvil item name color

### ISSUE THREAD

**Issue by bertek41** [ViaVersion/ViaRewind#178]
I send anvil gui with 1.15.2 server and there is no color in item name but in 1.8.8 it still shows "§f". Any way i can fix that?
![image](https://user-images.githubusercontent.com/20637793/87037036-4dd1d680-c1f4-11ea-83a4-9a87528e20db.png)
![image](https://user-images.githubusercontent.com/20637793/87037044-51655d80-c1f4-11ea-8280-108fb2f680e1.png)

Also i am using DEV-180.

**Comment by FlorianMichael** [comment]
![image](https://github.com/ViaVersion/ViaRewind/assets/60033407/804372b0-a92d-4c6b-84ad-e008b8390148)
Can't reproduce, try to update to latest Via* plugins
