### ISSUE TITLE
Containers don't work

### ISSUE THREAD

**Issue by xSqne** [ViaVersion/ViaRewind#196]
**Describe the bug, provide any errors**
I am on a 1.8 client (Lunar client) and when trying to open a container on a 1.16.1 spigot server with the latest viaversion, viabackwards, viarewind, it kicks me.

**How can we reproduce it?**
1. Login on 1.8 (I don't know if it is lunar problem)
2. Open any container (hopper, chest, etc)
3. Kicks with the message (screenshot)

**Expected behaviour**
Inventory GUIs would work correctly

**Screenshots**
![2020-08-15_12 14 36](https://user-images.githubusercontent.com/61461639/90310537-93b84380-def2-11ea-82ad-43363b035084.png)

**ViaVersion Dump**
https://dump.viaversion.com/f4d32548fc85331180d635b8025ff45c272b25403c172a09abf86b49a28f0c5c

**Additional server info**
I use Geyser, which is a proxy allowing bedrock players to join a java edition server

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Gerrygames** [comment]
Please provide the full error (set debug=true in server.properties).
