### ISSUE TITLE
Players unable to climb ladders

### ISSUE THREAD

**Issue by Chestly** [ViaVersion/ViaRewind#203]
Just installed ViaVersion, ViaRewind and ViaBackwards. They worked great on our Custom coded Hub style server until i found that players in versions 1.8.x cant climb ladders and can get rubber banding issues while they are trying to climb....

I saw a issue like this from about a year or two back, but now im having the same issue! If anyone knows of a way to fix it or if its just a bug that would be great to know! Thanks!

**Comment by krusic22** [comment]
Install ViaRewind Legacy Support.

**Comment by Jo0001** [comment]
https://www.spigotmc.org/resources/viarewind-legacy-support.52924/

**Comment by DarkProvider** [comment]
What if u have a paper server?

**Comment by DarkProvider** [comment]
Via rewind legacy support doesn't support paper sadly

**Comment by krusic22** [comment]
Are you sure about that?

**Comment by Xernium** [comment]
Thats news to me too

**Comment by DarkProvider** [comment]
I stand corrected, I just tried it. It works perfectly!

**Comment by ChibeMeliodas** [comment]
dont work in 1.19.2
