### ISSUE TITLE
Enderman causes 1.8.9 client crash

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaRewind#205]
Running Spigot 1.16.2 server and joining with a 1.8.9 client, the client crashes when it attempts to render an enderman. 

To reproduce, use the following plugin versions:
ViaBackwards-3.2.0-b166
ViaRewind-1.5.2-b61
ViaVersion-3.2.0-b465

Join the 1.16.2 server with a 1.8.9 client, switch to Creative mode, open the inventory and get a "Spawn Enderman" egg, then right-click on the ground with the egg to spawn an enderman. The client will crash.

Client error report:
```
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
Exit Code: -1
```

Full crash report: https://pastebin.com/wmT5AtLa
ViaVersion dump: https://dump.viaversion.com/7cdfa86a7c8c83e8d6dec702007e991f2b19425fdaecc073002cfcd7c11ddbc3
Spigot version git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2)

**Comment by Bobcat00** [comment]
This is definitely the result of a ViaVersion commit.  Testing with 
ViaBackwards-3.1.1-b148
ViaRewind-1.5.1-b58
ViaVersion-3.1.1-b455
the problem does not occur.

Updating ViaVersion to build 456, and the enderman problem occurs.

**Comment by MacTh3Mac** [comment]
**Verified Issue on The following Setups**

**Base Servers:** 
  Paper 1.12.2 - 1617
  Paper 1.15.2 - 385
  Tunity 1.16.3 - fe40e04
  Paper  1.16.3 - 192

**Via Suite Builds**
ViaVersion       - 3.2.0-SNAPSHOT b465
ViaBackwards - 3.2.0-SNAPSHOT b166
ViaRewind       - 1.5.2-SNAPSHOT b61 
ViaRewind-Legacy-Support - 1.3.2 b7 

**Clients Tested** 
Vanilla Minecraft 1.8.8
Vanilla Minecraft 1.8.9

**Viaver Dump:** [https://dump.viaversion.com/aa48ee262be12c0ced3f50fedc1bf68bbc61cd4a060951218d5d46f23d2e1025](https://dump.viaversion.com/aa48ee262be12c0ced3f50fedc1bf68bbc61cd4a060951218d5d46f23d2e1025) 

Error: Same as above

**Comment by Bobcat00** [comment]
Looks good.  Thanks!

Tested OK with:
ViaBackwards-3.2.0-b166
ViaRewind-1.5.2-b63
ViaVersion-3.2.0-b465
