### ISSUE TITLE
1.8 connection problem

### ISSUE THREAD

**Issue by DarkmcHERO** [ViaVersion/ViaRewind#207]
Hello,
I have a 1.16.1 papermc server with viaversion + backwards and rewind to allow all versions (1.7+) to connect.
It was working perfectly but today I had a couple of people who couldn't connect with 1.8 versions and it gave me an error that said to report it here.

This is a raw paste of the error:
https://pastebin.pl/view/b134b8c1

This is also a screenshot of all plugins I currently have installed:
https://i.gyazo.com/1aa3b99a29acde5a544669fc4118c5aa.png

Thanks in advance for the help!

**Comment by nathanfranke** [comment]
> https://pastebin.pl/view/b134b8c1

Can't open this. I would recommend pastebin.com, paste.wut.ee, hastebin.com

**Comment by Gerrygames** [comment]
^

**Comment by nathanfranke** [comment]
@Gerrygames I can open the link now. Here is a reliable mirror: https://pastebin.com/sfLP9wKT

**Comment by Gerrygames** [comment]
This is a ViaBackwards issue and you did not copy the full error.
