### ISSUE TITLE
Playing on 1.8 and I got an Error

### ISSUE THREAD

**Issue by SonEfAdam** [ViaVersion/ViaRewind#208]
**Describe the bug, provide any errors**
Playing on RedditMC server and I got an error which in in the screenshot.

**How can we Reproduce it?**
Login to RedditMC Server with 1.8.9 and run a command.

**Screenshots**
![image](https://user-images.githubusercontent.com/65645141/93174910-e2e6d380-f73f-11ea-8c96-6cccf051ae14.png)

Thank you!

**Comment by Mine-Go** [comment]
I have this Error too D:

**Comment by Gerrygames** [comment]
Please provide the full error printed in the console.
