### ISSUE TITLE
1.8.X client crashes

### ISSUE THREAD

**Issue by nads1303** [ViaVersion/ViaRewind#213]
---- Minecraft Crash Report ----
// You're mean.

Time: 11/10/20 22:36
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
	at xv.b(SourceFile:96)
	at aer.ck(SourceFile:297)
	at cpr.a(SourceFile:28)
	at cpr.a(SourceFile:12)
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at xv.b(SourceFile:96)
	at aer.ck(SourceFile:297)
	at cpr.a(SourceFile:28)
	at cpr.a(SourceFile:12)

-- Entity being rendered --
Details:
	Entity Type: Enderman (aer)
	Entity ID: 2048
	Entity Name: Enderman
	Entity's Exact location: 96.50, 40.00, -396.50
	Entity's Block location: 96.00,40.00,-397.00 - World: (96,40,-397), Chunk: (at 0,2,3 in 6,-25; contains blocks 96,0,-400 to 111,255,-385), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: cpr@32394a4b
	Location: -23.84,-30.55,47.31 - World: (-24,-31,47), Chunk: (at 8,-2,15 in -2,2; contains blocks -32,0,32 to -17,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -2.8125
	Delta: 0.58982265
Stacktrace:
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [cio['Nadsthebear'/1128, l='MpServer', x=120.32, y=70.50, z=-443.70]]
	Chunk stats: MultiplayerChunkCache: 470, 543
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 8.00,64.00,8.00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 109608123 game time, 81122841 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 297 total; [aer['Enderman'/2048, l='MpServer', x=96.50, y=40.00, z=-396.50], afw['Skeleton'/2051, l='MpServer', x=119.50, y=12.00, z=-408.50], adm['Painting'/581, l='MpServer', x=43.50, y=69.50, z=-389.97], agj['Zombie'/2056, l='MpServer', x=91.28, y=51.00, z=-442.47], age['Spider'/2061, l='MpServer', x=160.50, y=59.00, z=-457.50], age['Spider'/2062, l='MpServer', x=156.50, y=59.00, z=-461.50], age['Spider'/2064, l='MpServer', x=154.50, y=59.00, z=-463.50], aep['Creeper'/2069, l='MpServer', x=143.50, y=42.00, z=-412.50], adi['Armor Stand'/534, l='MpServer', x=60.78, y=58.53, z=-420.50], aep['Creeper'/2070, l='MpServer', x=145.50, y=42.00, z=-411.50], adi['Armor Stand'/535, l='MpServer', x=60.34, y=58.16, z=-420.50], aep['Creeper'/2073, l='MpServer', x=78.50, y=76.00, z=-467.50], agj['Zombie'/2074, l='MpServer', x=132.54, y=59.00, z=-455.69], afw['Skeleton'/2080, l='MpServer', x=78.44, y=61.00, z=-452.75], aef['container.minecart'/547, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/548, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/549, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/550, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/551, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/552, l='MpServer', x=60.50, y=359.94, z=-420.50], agj['Zombie'/2088, l='MpServer', x=152.50, y=9.00, z=-407.50], aef['container.minecart'/553, l='MpServer', x=60.50, y=359.94, z=-420.50], aef['container.minecart'/554, l='MpServer', x=60.50, y=359.94, z=-420.50], agj['Zombie'/2090, l='MpServer', x=86.50, y=42.00, z=-410.50], aef['container.minecart'/555, l='MpServer', x=60.50, y=359.94, z=-420.50], aeg['entity.MinecartRideable.name'/1068, l='MpServer', x=88.50, y=69.00, z=-487.47], agp['Villager'/1069, l='MpServer', x=88.50, y=69.15, z=-487.47], aeg['entity.MinecartRideable.name'/1070, l='MpServer', x=82.47, y=69.00, z=-487.47], agp['Villager'/1071, l='MpServer', x=82.47, y=69.15, z=-487.47], aeg['entity.MinecartRideable.name'/1072, l='MpServer', x=88.50, y=69.00, z=-489.50], agp['Villager'/1073, l='MpServer', x=88.50, y=69.15, z=-489.50], aeg['entity.MinecartRideable.name'/1074, l='MpServer', x=82.47, y=69.00, z=-489.50], agp['Villager'/1075, l='MpServer', x=82.47, y=69.15, z=-489.50], aeg['entity.MinecartRideable.name'/1076, l='MpServer', x=82.47, y=69.00, z=-491.47], agp['Villager'/1077, l='MpServer', x=82.47, y=69.15, z=-491.47], aeg['entity.MinecartRideable.name'/1078, l='MpServer', x=82.47, y=69.00, z=-495.50], aeg['entity.MinecartRideable.name'/1080, l='MpServer', x=82.63, y=69.00, z=-493.50], aeg['entity.MinecartRideable.name'/570, l='MpServer', x=69.50, y=63.06, z=-397.47], aby['§fCat'/1082, l='MpServer', x=88.25, y=69.00, z=-491.44], adu['Boat'/571, l='MpServer', x=69.50, y=63.21, z=-397.47], abo['Bat'/2108, l='MpServer', x=144.78, y=60.47, z=-477.41], abo['Bat'/2109, l='MpServer', x=155.66, y=59.25, z=-457.75], aeg['entity.MinecartRideable.name'/1086, l='MpServer', x=103.47, y=69.00, z=-486.50], abo['Bat'/2110, l='MpServer', x=154.63, y=60.41, z=-456.31], aeg['entity.MinecartRideable.name'/1087, l='MpServer', x=103.47, y=69.00, z=-488.47], abo['Bat'/2111, l='MpServer', x=131.00, y=59.08, z=-453.53], abo['§fChadwick'/575, l='MpServer', x=90.75, y=63.10, z=-397.75], agp['Villager'/1088, l='MpServer', x=103.47, y=69.15, z=-488.47], abo['§fviki'/576, l='MpServer', x=91.16, y=64.10, z=-397.28], aeg['entity.MinecartRideable.name'/1089, l='MpServer', x=103.47, y=69.00, z=-490.50], agp['Villager'/1090, l='MpServer', x=103.47, y=69.15, z=-490.50], aeg['entity.MinecartRideable.name'/1091, l='MpServer', x=109.50, y=69.00, z=-490.47], agp['Villager'/1092, l='MpServer', x=109.50, y=69.15, z=-490.47], aeg['entity.MinecartRideable.name'/1093, l='MpServer', x=103.47, y=69.00, z=-492.50], aeg['entity.MinecartRideable.name'/1095, l='MpServer', x=103.47, y=69.00, z=-494.50], aeg['entity.MinecartRideable.name'/1097, l='MpServer', x=109.50, y=69.00, z=-494.47], aeg['entity.MinecartRideable.name'/1099, l='MpServer', x=109.50, y=69.00, z=-492.50], aeg['entity.MinecartRideable.name'/1101, l='MpServer', x=109.50, y=69.00, z=-488.50], agp['Villager'/1102, l='MpServer', x=109.50, y=69.15, z=-488.50], aeg['entity.MinecartRideable.name'/1103, l='MpServer', x=103.47, y=73.00, z=-486.50], adm['Painting'/572, l='MpServer', x=56.97, y=69.50, z=-389.50], agp['Villager'/1104, l='MpServer', x=103.47, y=73.15, z=-486.50], aco['Tropical Fish'/592, l='MpServer', x=111.25, y=59.00, z=-411.75], aeg['entity.MinecartRideable.name'/1105, l='MpServer', x=109.50, y=73.00, z=-486.50], aco['Tropical Fish'/593, l='MpServer', x=112.14, y=59.80, z=-411.11], agp['Villager'/1106, l='MpServer', x=109.50, y=73.15, z=-486.50], aco['Tropical Fish'/594, l='MpServer', x=112.93, y=60.03, z=-410.77], aeg['entity.MinecartRideable.name'/1107, l='MpServer', x=109.50, y=73.00, z=-488.50], afw['Skeleton'/2131, l='MpServer', x=131.50, y=51.00, z=-449.50], aco['Tropical Fish'/595, l='MpServer', x=114.82, y=60.09, z=-411.72], agp['Villager'/1108, l='MpServer', x=109.50, y=73.15, z=-488.50], aco['Tropical Fish'/596, l='MpServer', x=115.59, y=61.03, z=-411.83], aeg['entity.MinecartRideable.name'/1109, l='MpServer', x=103.47, y=73.00, z=-488.50], aco['Tropical Fish'/597, l='MpServer', x=114.17, y=58.82, z=-411.23], agp['Villager'/1110, l='MpServer', x=103.47, y=73.15, z=-488.50], aco['Tropical Fish'/598, l='MpServer', x=111.80, y=59.97, z=-410.61], aeg['entity.MinecartRideable.name'/1111, l='MpServer', x=103.47, y=73.00, z=-490.50], aco['Tropical Fish'/599, l='MpServer', x=114.52, y=60.05, z=-411.22], agp['Villager'/1112, l='MpServer', x=103.47, y=73.15, z=-490.50], aco['Tropical Fish'/600, l='MpServer', x=115.47, y=59.00, z=-411.81], aeg['entity.MinecartRideable.name'/1113, l='MpServer', x=109.50, y=73.00, z=-490.50], aco['Tropical Fish'/601, l='MpServer', x=115.00, y=59.00, z=-411.25], agp['Villager'/1114, l='MpServer', x=109.50, y=73.15, z=-490.50], aco['Tropical Fish'/602, l='MpServer', x=114.35, y=59.00, z=-411.78], aeg['entity.MinecartRideable.name'/1115, l='MpServer', x=103.47, y=73.00, z=-492.50], aco['Tropical Fish'/603, l='MpServer', x=115.92, y=59.00, z=-411.75], aco['Tropical Fish'/604, l='MpServer', x=111.72, y=59.73, z=-410.38], aeg['entity.MinecartRideable.name'/1117, l='MpServer', x=109.50, y=73.00, z=-492.47], aco['Tropical Fish'/605, l='MpServer', x=112.79, y=60.96, z=-410.05], agp['Villager'/1118, l='MpServer', x=109.50, y=73.15, z=-492.47], aco['Tropical Fish'/606, l='MpServer', x=111.60, y=59.79, z=-412.01], aeg['entity.MinecartRideable.name'/1119, l='MpServer', x=109.50, y=73.00, z=-494.47], aeg['entity.MinecartRideable.name'/1121, l='MpServer', x=103.47, y=73.00, z=-494.50], age['Spider'/2145, l='MpServer', x=135.56, y=59.00, z=-482.03], afw['Skeleton'/2146, l='MpServer', x=144.02, y=59.00, z=-470.29], agj['Zombie'/1123, l='MpServer', x=117.16, y=25.00, z=-461.50], aep['Creeper'/2147, l='MpServer', x=132.66, y=59.00, z=-480.47], aep['Creeper'/2148, l='MpServer', x=136.84, y=59.00, z=-482.16], aby['Turtle'/613, l='MpServer', x=111.97, y=62.00, z=-398.91], aby['§fCat'/1127, l='MpServer', x=111.50, y=64.00, z=-456.72], agj['Zombie'/2156, l='MpServer', x=149.22, y=30.00, z=-483.25], aep['Creeper'/2165, l='MpServer', x=73.47, y=59.76, z=-452.38], aep['Creeper'/2182, l='MpServer', x=91.50, y=31.00, z=-399.75], aco['Salmon'/1161, l='MpServer', x=138.25, y=57.00, z=-431.66], aco['Tropical Fish'/1162, l='MpServer', x=149.10, y=59.30, z=-428.41], aco['Tropical Fish'/1163, l='MpServer', x=137.65, y=56.99, z=-431.06], aco['Tropical Fish'/1164, l='MpServer', x=132.70, y=59.00, z=-402.26], aco['Tropical Fish'/1165, l='MpServer', x=133.08, y=59.00, z=-400.09], aco['Tropical Fish'/1166, l='MpServer', x=132.25, y=59.00, z=-400.25], aco['Tropical Fish'/1167, l='MpServer', x=133.99, y=59.00, z=-400.82], aco['Tropical Fish'/1168, l='MpServer', x=133.13, y=59.00, z=-399.16], aco['Tropical Fish'/1169, l='MpServer', x=133.68, y=59.00, z=-399.96], aco['Tropical Fish'/1170, l='MpServer', x=133.36, y=59.00, z=-401.28], aco['Tropical Fish'/1171, l='MpServer', x=132.25, y=59.00, z=-399.22], aco['Tropical Fish'/1172, l='MpServer', x=132.50, y=59.91, z=-400.53], aco['Tropical Fish'/1173, l='MpServer', x=132.75, y=59.00, z=-401.23], aco['Tropical Fish'/1174, l='MpServer', x=132.25, y=59.00, z=-400.98], aco['Tropical Fish'/1177, l='MpServer', x=137.25, y=59.00, z=-433.25], aco['Tropical Fish'/1178, l='MpServer', x=136.89, y=59.00, z=-434.25], aco['Tropical Fish'/1179, l='MpServer', x=138.10, y=59.00, z=-434.41], aco['Tropical Fish'/1180, l='MpServer', x=137.55, y=59.00, z=-434.13], aco['Tropical Fish'/1181, l='MpServer', x=138.09, y=59.00, z=-433.25], aco['Tropical Fish'/1182, l='MpServer', x=138.71, y=59.00, z=-433.79], abt['§fCucciolino piccolino 2'/1183, l='MpServer', x=130.97, y=70.00, z=-438.78], aeg['entity.MinecartRideable.name'/1186, l='MpServer', x=82.47, y=69.00, z=-497.47], aeg['entity.MinecartRideable.name'/1188, l='MpServer', x=109.50, y=69.00, z=-496.50], aeg['entity.MinecartRideable.name'/1190, l='MpServer', x=103.47, y=69.00, z=-496.47], aeg['entity.MinecartRideable.name'/1192, l='MpServer', x=103.47, y=69.00, z=-498.50], aeg['entity.MinecartRideable.name'/1194, l='MpServer', x=109.50, y=69.00, z=-498.47], aeg['entity.MinecartRideable.name'/1196, l='MpServer', x=103.47, y=69.00, z=-500.47], aeg['entity.MinecartRideable.name'/1198, l='MpServer', x=109.50, y=69.00, z=-500.47], aeg['entity.MinecartRideable.name'/1200, l='MpServer', x=109.50, y=69.00, z=-502.47], aeg['entity.MinecartRideable.name'/1202, l='MpServer', x=103.47, y=69.00, z=-504.50], aeg['entity.MinecartRideable.name'/1204, l='MpServer', x=103.47, y=69.00, z=-502.50], aeg['entity.MinecartRideable.name'/1206, l='MpServer', x=109.50, y=69.00, z=-504.47], aby['§fCat'/1244, l='MpServer', x=126.75, y=69.00, z=-473.22], acl['§fDinnerbone'/1260, l='MpServer', x=154.53, y=72.00, z=-492.44], aby['§fCat'/1270, l='MpServer', x=154.19, y=68.00, z=-457.13], aef['container.minecart'/1280, l='MpServer', x=154.50, y=70.06, z=-494.45], aco['Tropical Fish'/1281, l='MpServer', x=156.25, y=59.00, z=-432.22], aco['Tropical Fish'/1282, l='MpServer', x=155.98, y=59.00, z=-433.44], aco['Tropical Fish'/1283, l='MpServer', x=156.25, y=59.00, z=-431.47], aco['Tropical Fish'/1284, l='MpServer', x=149.38, y=59.00, z=-433.28], cio['Nadsthebear'/1128, l='MpServer', x=120.32, y=70.50, z=-443.70], aco['Tropical Fish'/1285, l='MpServer', x=154.97, y=59.00, z=-433.22], aco['Tropical Fish'/1286, l='MpServer', x=155.45, y=59.00, z=-433.99], aco['Tropical Fish'/1287, l='MpServer', x=154.85, y=59.00, z=-433.88], aco['Tropical Fish'/1288, l='MpServer', x=157.34, y=59.00, z=-432.72], aco['Tropical Fish'/1289, l='MpServer', x=155.40, y=59.00, z=-433.53], aco['Tropical Fish'/1298, l='MpServer', x=148.84, y=57.00, z=-430.86], aco['Tropical Fish'/1299, l='MpServer', x=148.33, y=56.96, z=-431.75], aco['Tropical Fish'/1300, l='MpServer', x=147.50, y=56.91, z=-430.75], aco['Tropical Fish'/1301, l='MpServer', x=149.13, y=57.00, z=-431.72], aco['Tropical Fish'/1302, l='MpServer', x=148.24, y=56.92, z=-431.08], aco['Tropical Fish'/1303, l='MpServer', x=149.55, y=56.09, z=-430.99], aco['Tropical Fish'/1304, l='MpServer', x=149.44, y=59.00, z=-434.63], aco['Tropical Fish'/1305, l='MpServer', x=156.28, y=59.00, z=-432.81], aco['Tropical Fish'/1306, l='MpServer', x=142.90, y=56.74, z=-431.38], aco['Tropical Fish'/1307, l='MpServer', x=146.47, y=56.97, z=-431.41], aco['Tropical Fish'/1308, l='MpServer', x=150.38, y=56.96, z=-430.61], aco['Cod'/1309, l='MpServer', x=149.91, y=57.03, z=-431.75], aco['Cod'/1310, l='MpServer', x=147.84, y=57.00, z=-431.75], aco['Tropical Fish'/1311, l='MpServer', x=150.14, y=55.89, z=-431.72], adi['Armor Stand'/1313, l='MpServer', x=147.50, y=60.00, z=-405.50], agj['Zombie'/819, l='MpServer', x=74.50, y=60.00, z=-468.21], aco['Tropical Fish'/829, l='MpServer', x=120.25, y=59.00, z=-406.78], aco['Tropical Fish'/830, l='MpServer', x=121.28, y=59.00, z=-408.13], aco['Tropical Fish'/831, l='MpServer', x=121.18, y=59.00, z=-410.10], aco['Tropical Fish'/832, l='MpServer', x=121.08, y=59.00, z=-406.96], aco['Tropical Fish'/833, l='MpServer', x=121.52, y=59.00, z=-407.63], aco['Tropical Fish'/834, l='MpServer', x=120.25, y=59.00, z=-407.75], aco['Tropical Fish'/835, l='MpServer', x=119.72, y=60.96, z=-406.52], aco['Tropical Fish'/836, l='MpServer', x=120.37, y=60.90, z=-406.87], aco['Tropical Fish'/837, l='MpServer', x=120.25, y=61.47, z=-407.72], aco['Tropical Fish'/838, l='MpServer', x=121.27, y=60.93, z=-408.02], aco['Tropical Fish'/839, l='MpServer', x=120.90, y=61.00, z=-406.77], aco['Tropical Fish'/840, l='MpServer', x=120.25, y=60.91, z=-407.75], aco['Tropical Fish'/841, l='MpServer', x=121.06, y=60.89, z=-407.53], aco['Tropical Fish'/842, l='MpServer', x=121.80, y=59.00, z=-410.72], aco['Tropical Fish'/843, l='MpServer', x=121.77, y=59.00, z=-411.91], aco['Tropical Fish'/844, l='MpServer', x=123.25, y=59.00, z=-408.50], aco['Tropical Fish'/845, l='MpServer', x=121.75, y=59.00, z=-407.00], aco['Tropical Fish'/846, l='MpServer', x=121.88, y=59.00, z=-413.72], aco['Tropical Fish'/847, l='MpServer', x=121.14, y=59.00, z=-414.20], aco['Tropical Fish'/848, l='MpServer', x=121.16, y=59.00, z=-412.35], aco['Tropical Fish'/849, l='MpServer', x=120.25, y=61.59, z=-407.75], aco['Tropical Fish'/850, l='MpServer', x=120.69, y=59.00, z=-405.47], aco['Tropical Fish'/851, l='MpServer', x=119.94, y=59.00, z=-406.25], aco['Tropical Fish'/852, l='MpServer', x=121.88, y=59.00, z=-413.04], aco['Tropical Fish'/853, l='MpServer', x=120.25, y=59.00, z=-407.75], aco['Tropical Fish'/854, l='MpServer', x=122.36, y=59.00, z=-414.78], aco['Tropical Fish'/855, l='MpServer', x=121.79, y=59.00, z=-412.62], aco['Tropical Fish'/856, l='MpServer', x=121.25, y=59.00, z=-409.48], aco['Tropical Fish'/857, l='MpServer', x=120.97, y=59.00, z=-407.41], aco['Tropical Fish'/858, l='MpServer', x=121.77, y=59.00, z=-414.07], aco['Tropical Fish'/859, l='MpServer', x=121.75, y=59.00, z=-406.25], aco['Tropical Fish'/860, l='MpServer', x=120.68, y=59.93, z=-407.75], aco['Tropical Fish'/861, l='MpServer', x=122.96, y=59.00, z=-414.75], aco['Tropical Fish'/862, l='MpServer', x=123.86, y=59.00, z=-414.75], aco['Tropical Fish'/863, l='MpServer', x=123.43, y=59.00, z=-414.75], aco['Tropical Fish'/864, l='MpServer', x=124.14, y=59.00, z=-413.95], aco['Tropical Fish'/865, l='MpServer', x=122.33, y=59.00, z=-414.25], aco['Tropical Fish'/866, l='MpServer', x=121.22, y=59.00, z=-413.58], aco['Tropical Fish'/867, l='MpServer', x=121.13, y=59.00, z=-414.95], aco['Tropical Fish'/868, l='MpServer', x=121.99, y=59.00, z=-409.08], aco['Tropical Fish'/869, l='MpServer', x=123.31, y=59.00, z=-413.95], aco['Tropical Fish'/870, l='MpServer', x=121.75, y=59.00, z=-411.17], aco['Tropical Fish'/871, l='MpServer', x=121.22, y=59.00, z=-411.96], aco['Tropical Fish'/872, l='MpServer', x=121.23, y=59.00, z=-408.90], aco['Tropical Fish'/873, l='MpServer', x=121.72, y=61.59, z=-410.72], aco['Tropical Fish'/874, l='MpServer', x=123.49, y=59.00, z=-413.27], aco['Tropical Fish'/875, l='MpServer', x=119.16, y=61.59, z=-406.25], aco['Tropical Fish'/876, l='MpServer', x=124.75, y=59.00, z=-414.75], aco['Tropical Fish'/877, l='MpServer', x=118.95, y=60.97, z=-406.17], aco['Tropical Fish'/878, l='MpServer', x=118.38, y=61.03, z=-407.72], aco['Tropical Fish'/879, l='MpServer', x=117.66, y=61.00, z=-406.25], aco['Tropical Fish'/880, l='MpServer', x=121.19, y=59.00, z=-413.05], aby['Turtle'/881, l='MpServer', x=112.69, y=62.00, z=-400.34], aby['Turtle'/882, l='MpServer', x=114.50, y=62.00, z=-400.06], aco['Tropical Fish'/883, l='MpServer', x=116.75, y=59.00, z=-411.85], aco['Tropical Fish'/884, l='MpServer', x=116.85, y=59.00, z=-413.89], aco['Tropical Fish'/885, l='MpServer', x=116.76, y=59.00, z=-411.47], aco['Tropical Fish'/886, l='MpServer', x=117.10, y=59.00, z=-418.67], aco['Tropical Fish'/887, l='MpServer', x=116.25, y=59.00, z=-419.59], aco['Tropical Fish'/888, l='MpServer', x=116.53, y=59.00, z=-411.75], aco['Tropical Fish'/889, l='MpServer', x=116.22, y=59.00, z=-418.31], aco['Tropical Fish'/890, l='MpServer', x=116.75, y=59.00, z=-412.88], aco['Tropical Fish'/891, l='MpServer', x=116.75, y=59.00, z=-413.01], adm['Painting'/608, l='MpServer', x=49.00, y=70.50, z=-381.97], aco['Tropical Fish'/892, l='MpServer', x=116.25, y=59.00, z=-413.00], aco['Tropical Fish'/893, l='MpServer', x=116.21, y=59.00, z=-416.86], aco['Tropical Fish'/894, l='MpServer', x=116.72, y=59.00, z=-416.31], adm['Painting'/573, l='MpServer', x=49.00, y=70.00, z=-390.97], aco['Tropical Fish'/895, l='MpServer', x=115.25, y=61.00, z=-410.20], aco['Tropical Fish'/897, l='MpServer', x=115.46, y=61.00, z=-411.20], aco['Tropical Fish'/898, l='MpServer', x=112.75, y=60.97, z=-411.72], aco['Tropical Fish'/899, l='MpServer', x=113.62, y=59.00, z=-411.25], aco['Tropical Fish'/900, l='MpServer', x=115.84, y=60.94, z=-412.36], aco['Tropical Fish'/901, l='MpServer', x=116.75, y=61.59, z=-411.25], aco['Tropical Fish'/902, l='MpServer', x=116.77, y=59.00, z=-415.53], aco['Tropical Fish'/903, l='MpServer', x=116.75, y=59.00, z=-414.71], aco['Tropical Fish'/904, l='MpServer', x=116.24, y=59.00, z=-414.45], aco['Tropical Fish'/905, l='MpServer', x=116.25, y=60.94, z=-411.47], aco['Tropical Fish'/906, l='MpServer', x=116.75, y=59.00, z=-412.29], aco['Tropical Fish'/907, l='MpServer', x=116.75, y=59.88, z=-411.25], aco['Tropical Fish'/908, l='MpServer', x=116.72, y=61.13, z=-415.23], aco['Tropical Fish'/909, l='MpServer', x=116.53, y=61.44, z=-412.53], aco['Tropical Fish'/910, l='MpServer', x=116.75, y=59.00, z=-411.12], aco['Tropical Fish'/911, l='MpServer', x=116.21, y=61.03, z=-414.12], aco['Tropical Fish'/912, l='MpServer', x=113.53, y=61.06, z=-412.53], aco['Tropical Fish'/913, l='MpServer', x=112.75, y=59.00, z=-410.56], aco['Tropical Fish'/914, l='MpServer', x=112.32, y=59.00, z=-411.75], aco['Tropical Fish'/915, l='MpServer', x=116.17, y=61.06, z=-413.07], aco['Tropical Fish'/916, l='MpServer', x=112.53, y=60.00, z=-412.19], aco['Tropical Fish'/917, l='MpServer', x=114.47, y=61.06, z=-411.25], aco['Tropical Fish'/918, l='MpServer', x=115.41, y=59.00, z=-411.72], aco['Tropical Fish'/919, l='MpServer', x=116.25, y=60.97, z=-414.71], aco['Tropical Fish'/920, l='MpServer', x=113.04, y=59.00, z=-411.75], aco['Tropical Fish'/921, l='MpServer', x=113.11, y=60.94, z=-411.14], aco['Tropical Fish'/922, l='MpServer', x=116.80, y=59.00, z=-415.53], aco['Tropical Fish'/923, l='MpServer', x=116.79, y=61.00, z=-412.61], aco['Tropical Fish'/924, l='MpServer', x=111.44, y=59.00, z=-410.25], aco['Tropical Fish'/925, l='MpServer', x=116.23, y=59.00, z=-415.94], aco['Tropical Fish'/926, l='MpServer', x=116.82, y=60.96, z=-413.80], aco['Tropical Fish'/927, l='MpServer', x=116.75, y=61.00, z=-411.25], aco['Tropical Fish'/928, l='MpServer', x=116.22, y=59.00, z=-413.57], adm['Painting'/978, l='MpServer', x=50.00, y=67.50, z=-478.03], aco['Tropical Fish'/929, l='MpServer', x=117.69, y=59.00, z=-418.25], aco['Tropical Fish'/930, l='MpServer', x=116.24, y=59.00, z=-414.03], aco['Tropical Fish'/931, l='MpServer', x=116.75, y=61.13, z=-411.25], aco['Tropical Fish'/932, l='MpServer', x=112.63, y=59.94, z=-410.97], aco['Tropical Fish'/933, l='MpServer', x=116.40, y=60.97, z=-411.16], aco['Tropical Fish'/934, l='MpServer', x=116.79, y=59.00, z=-417.54], aco['Tropical Fish'/935, l='MpServer', x=116.75, y=59.00, z=-410.37], aco['Tropical Fish'/936, l='MpServer', x=116.96, y=60.93, z=-411.78], aco['Tropical Fish'/937, l='MpServer', x=116.53, y=61.00, z=-412.14], aby['§fCat'/938, l='MpServer', x=113.19, y=64.00, z=-422.47], abo['Bat'/1989, l='MpServer', x=92.23, y=26.96, z=-405.89], abo['Bat'/1990, l='MpServer', x=145.28, y=60.03, z=-484.75], abo['Bat'/1991, l='MpServer', x=151.66, y=59.00, z=-469.91], abo['Bat'/1993, l='MpServer', x=148.47, y=62.94, z=-454.97], abo['Bat'/1994, l='MpServer', x=136.59, y=61.47, z=-453.16], abo['Bat'/1995, l='MpServer', x=141.50, y=61.09, z=-471.53], abo['Bat'/1996, l='MpServer', x=140.25, y=59.78, z=-460.16], aep['Creeper'/2005, l='MpServer', x=146.16, y=59.00, z=-454.22], aep['Creeper'/2006, l='MpServer', x=139.00, y=59.00, z=-450.50], afw['Skeleton'/2007, l='MpServer', x=139.91, y=59.00, z=-455.50], afw['Skeleton'/2008, l='MpServer', x=148.50, y=59.00, z=-453.50], agj['Zombie'/2011, l='MpServer', x=142.50, y=15.00, z=-415.50], agj['Zombie'/2015, l='MpServer', x=100.50, y=24.00, z=-489.50], agj['Zombie'/2016, l='MpServer', x=135.50, y=35.00, z=-474.50], afw['Skeleton'/2018, l='MpServer', x=134.50, y=35.00, z=-473.50], aep['Creeper'/2036, l='MpServer', x=94.66, y=25.00, z=-405.50], aep['Creeper'/2043, l='MpServer', x=115.53, y=57.00, z=-479.50], aep['Creeper'/2044, l='MpServer', x=73.28, y=58.00, z=-452.28], aep['Creeper'/2045, l='MpServer', x=74.22, y=58.00, z=-452.22], aby['§fCat'/1023, l='MpServer', x=111.50, y=64.00, z=-466.19]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at cen.a(SourceFile:308)
	at bsu.b(SourceFile:2252)
	at bsu.a(SourceFile:323)
	at net.minecraft.client.main.Main.main(SourceFile:120)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1067593888 bytes (1018 MB) / 1409286144 bytes (1344 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by DoctorMacc** [comment]
Are you using the build from https://ci.viaversion.com/job/ViaVersion/ ?

**Comment by GC-spigot** [comment]
Same issue, seems like Enderman crashes the client

**Comment by DoctorMacc** [comment]
With ViaVersion 3.1.1 or 3.2.0-SNAPSHOT?
