### ISSUE TITLE
1.8.X client crashes

### ISSUE THREAD

**Issue by TerThesz** [ViaVersion/ViaRewind#214]
I have optifine and labymode but it crashes on vanila aswell

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 18.10.2020 20:08
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
	at pz.b(DataWatcher.java:91)
	at vo.cm(SourceFile:297)
	at bis.a(SourceFile:28)
	at bis.a(SourceFile:12)
	at biu.a(RenderManager.java:402)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:120)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:107)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:82)
	at bfr.a(RenderGlobal.java:870)
	at bfk.a(EntityRenderer.java:1763)
	at bfk.b(EntityRenderer.java:1580)
	at bfk.a(EntityRenderer.java:1372)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pz.b(DataWatcher.java:91)
	at vo.cm(SourceFile:297)
	at bis.a(SourceFile:28)
	at bis.a(SourceFile:12)

-- Entity being rendered --
Details:
	Entity Type: Enderman (vo)
	Entity ID: 319
	Entity Name: Enderman
	Entity's Exact location: -17,50, 58,00, -3,50
	Entity's Block location: -18,00,58,00,-4,00 - World: (-18,58,-4), Chunk: (at 14,3,12 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: bis@69e4e90b
	Location: -16,28,-36,22,3,14 - World: (-17,-37,3), Chunk: (at 15,-3,3 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -149.0625
	Delta: 0.3704819
Stacktrace:
	at biu.a(RenderManager.java:402)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:120)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:107)
	at net.labymod.core_implementation.mc18.render.RenderManagerCustom.a(RenderManagerCustom.java:82)
	at bfr.a(RenderGlobal.java:870)
	at bfk.a(EntityRenderer.java:1763)
	at bfk.b(EntityRenderer.java:1580)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [bew['TerThesz2'/233, l='MpServer', x=-1,12, y=94,17, z=-6,78], bex['TerThesz'/234, l='MpServer', x=-3,22, y=93,00, z=-6,28]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -18,00,94,00,-3,00 - World: (-18,94,-3), Chunk: (at 14,5,13 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 334119 game time, 633490 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 45 total; [wa['Skeleton'/129, l='MpServer', x=4,50, y=76,00, z=-31,25], vn['Creeper'/321, l='MpServer', x=-6,50, y=52,00, z=-8,50], we['Zombie'/131, l='MpServer', x=16,50, y=83,00, z=-28,50], we['Zombie'/132, l='MpServer', x=16,50, y=83,00, z=-28,50], tv['Sheep'/133, l='MpServer', x=19,50, y=108,00, z=-19,61], wc['Spider'/261, l='MpServer', x=-7,50, y=74,00, z=29,50], we['Zombie'/262, l='MpServer', x=23,50, y=71,00, z=-7,50], vn['Creeper'/264, l='MpServer', x=-7,38, y=69,00, z=-20,50], to['Cow'/73, l='MpServer', x=-34,19, y=91,00, z=7,41], to['Cow'/75, l='MpServer', x=-39,47, y=93,00, z=5,25], we['Zombie'/140, l='MpServer', x=22,50, y=68,00, z=-5,50], tn['Chicken'/143, l='MpServer', x=21,81, y=104,00, z=7,50], vn['Creeper'/271, l='MpServer', x=-11,50, y=72,00, z=-23,22], we['Zombie'/80, l='MpServer', x=-32,50, y=75,00, z=31,50], we['Zombie'/81, l='MpServer', x=-20,47, y=72,00, z=-13,19], tt['Pig'/82, l='MpServer', x=-15,75, y=91,00, z=-15,75], tp['Horse'/83, l='MpServer', x=-19,03, y=91,00, z=-21,22], we['Zombie'/84, l='MpServer', x=-15,47, y=81,00, z=-27,25], bew['TerThesz2'/233, l='MpServer', x=-1,12, y=94,17, z=-6,78], wc['Spider'/281, l='MpServer', x=0,50, y=51,00, z=-4,50], vn['Creeper'/91, l='MpServer', x=-27,34, y=71,00, z=29,53], we['Zombie'/92, l='MpServer', x=-28,50, y=75,00, z=34,50], wa['Skeleton'/284, l='MpServer', x=-7,50, y=68,00, z=18,50], tp['Horse'/93, l='MpServer', x=-8,03, y=85,00, z=-41,97], wa['Skeleton'/285, l='MpServer', x=-34,50, y=64,00, z=-0,50], to['Cow'/94, l='MpServer', x=-8,16, y=92,00, z=-40,38], wa['Skeleton'/224, l='MpServer', x=-0,47, y=68,00, z=16,31], to['Cow'/97, l='MpServer', x=-3,13, y=92,00, z=-39,28], wa['Skeleton'/226, l='MpServer', x=-15,19, y=72,00, z=-20,34], wa['Skeleton'/227, l='MpServer', x=7,50, y=81,00, z=30,50], wa['Skeleton'/228, l='MpServer', x=8,50, y=81,00, z=29,50], wa['Skeleton'/229, l='MpServer', x=6,50, y=81,00, z=31,50], wc['Spider'/103, l='MpServer', x=-15,38, y=77,00, z=40,03], wd['Witch'/297, l='MpServer', x=27,50, y=80,00, z=-12,50], bex['TerThesz'/234, l='MpServer', x=-3,22, y=93,00, z=-6,28], bex['TerThesz'/234, l='MpServer', x=-3,22, y=93,00, z=-6,28], vn['Creeper'/304, l='MpServer', x=-26,50, y=56,00, z=9,50], wa['Skeleton'/114, l='MpServer', x=13,25, y=77,00, z=-28,50], wa['Skeleton'/306, l='MpServer', x=-10,50, y=73,00, z=-24,50], wa['Skeleton'/115, l='MpServer', x=21,22, y=75,00, z=-21,53], uz['item.item.egg'/307, l='MpServer', x=22,72, y=104,00, z=8,44], to['Cow'/118, l='MpServer', x=21,50, y=102,00, z=-26,78], vn['Creeper'/310, l='MpServer', x=9,50, y=73,00, z=21,50], we['Zombie'/312, l='MpServer', x=-3,50, y=57,00, z=4,50], vo['Enderman'/319, l='MpServer', x=-17,50, y=58,00, z=-3,50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bdb.a(WorldClient.java:402)
	at ave.b(SourceFile:2311)
	at ave.a(SourceFile:334)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141228688 bytes (134 MB) / 402653184 bytes (384 MB) up to 7214202880 bytes (6880 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx6850M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.8783, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8783
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by Gerrygames** [comment]
Fixed in the newest ci build
