### ISSUE TITLE
<= 1.8.9 kick issue

### ISSUE THREAD

**Issue by ZeyKoYT** [ViaVersion/ViaRewind#222]
Describe the bug, provide any errors
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

The bug is when i install Viaversion , ViabackWards and viarewind , and when i join the server with 1.8.8 client on my 1.12.2 server it kick me instantly for [Proxy] Lost connection to the server (screen : https://prnt.sc/vaofn6)

I use Travetive for proxy , i try to change it and use normal bungeecord , flamecord ect but same issue.
And server version i use Paper 1.12.2.

I got 0 plugins on my bungeecord.
I got Only ViaVersion , ViaRewind and ViaBackWards my spigot server.

How can we reproduce it?
To reproduce the player kick issue ,
1 - just setup a bungeecord
2 - setup a 1.12.2 paper server
3- install viaversion , viarewind and viabackwards on it (spigot side)
4 - Join with a <= 1.8.9 client

Expected behaviour

I expect it to be fixed
Screenshots
If applicable, add screenshots to help explain your problem.*

With the kick issue on <= 1.8.9 client i got just 2 screens 1 minecraft side and on bungeecord side
Minecraft Side: https://prnt.sc/vaoixp
Bungeecord Side (Console) : https://prnt.sc/vaoj6l
No console errors proxy / spigot side.
ViaVersion Dump:

Type /viaversion dump, and put the link here.
https://dump.viaversion.com/dd77e09a3d415f490c96cf64f49d830ebc59c17a6d7a646b3553ce3e1feae461
Additional server info
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
i use Travetine lasted for this test , but alredy tryed to use FlameCord or a normal Bungeecord. i dont have plugins proxy side.

Checklist

 I have included a ViaVersion dump

 If applicable, I have included a paste (not a screenshot) of the error

 I have tried a build from https://ci.viaversion.com/ and the issue still persists

I install lasted version of all the plugins

Good luck for fixing it. and Srry for my english i'm french

**Comment by ZeyKoYT** [comment]
if that can help you the issue is caused by using 1.12.2 spigot bossbar api : 
bossbar = new Bar();
bossbar.bar = Bukkit.createBossBar("", BarColor.RED, BarStyle.SOLID);

**Comment by MrKlarki** [comment]
Confirm. I have in the course of the same because of the boss of the bar kicks on 1.8

**Comment by Coolfire02** [comment]
Bug can be replicated on our server as well. We're reverting to 1.8-1.15.2 support on a legacy version of VV for now until this gets fixed.
