### ISSUE TITLE
Enderman crashes Minecraft 1.8.9 client

### ISSUE THREAD

**Issue by GIGAADAM** [ViaVersion/ViaRewind#223]
Hello, I have a little problem,

I have server (Spigot 1.16.1) and when I join with 1.8.9 client version, then just chunk will load enderman and my game crashes

Crash Report from client:
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6.11.20 22:30
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Short
	at pz.b(SourceFile:96)
	at vo.cm(SourceFile:297)
	at bis.a(SourceFile:28)
	at bis.a(SourceFile:12)
	at biu.a(SourceFile:295)
	at biu.a(SourceFile:260)
	at biu.a(SourceFile:227)
	at bfr.a(SourceFile:596)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)
	at bfk.a(SourceFile:1002)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pz.b(SourceFile:96)
	at vo.cm(SourceFile:297)
	at bis.a(SourceFile:28)
	at bis.a(SourceFile:12)

-- Entity being rendered --
Details:
	Entity Type: Enderman (vo)
	Entity ID: 104584
	Entity Name: Enderman
	Entity's Exact location: 501,50, 67,00, -1271,50
	Entity's Block location: 501,00,67,00,-1272,00 - World: (501,67,-1272), Chunk: (at 5,4,8 in 31,-80; contains blocks 496,0,-1280 to 511,255,-1265), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: bis@7aad7df5
	Location: 1,58,-1,01,0,74 - World: (1,-2,0), Chunk: (at 1,-1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 171.5625
	Delta: 0.8073462
Stacktrace:
	at biu.a(SourceFile:295)
	at biu.a(SourceFile:260)
	at biu.a(SourceFile:227)
	at bfr.a(SourceFile:596)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [bew['GigaAdamYT'/150, l='MpServer', x=499,92, y=68,01, z=-1272,24], bex['I_Lik3_Wqlfys'/55924, l='MpServer', x=500,10, y=67,02, z=-1271,06]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -160,00,70,00,-186,00 - World: (-160,70,-186), Chunk: (at 0,4,6 in -10,-12; contains blocks -160,0,-192 to -145,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1397379 game time, 487267 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 32 total; [vn['Creeper'/104449, l='MpServer', x=541,50, y=27,00, z=-1281,78], tn['Chicken'/104129, l='MpServer', x=536,00, y=77,00, z=-1243,00], tn['Chicken'/104128, l='MpServer', x=538,31, y=80,00, z=-1236,50], vn['Creeper'/104448, l='MpServer', x=542,75, y=28,00, z=-1283,56], we['Zombie'/104386, l='MpServer', x=525,50, y=39,00, z=-1302,50], vn['Creeper'/104450, l='MpServer', x=537,50, y=27,00, z=-1280,50], we['Zombie'/104582, l='MpServer', x=477,50, y=17,00, z=-1232,50], vo['Enderman'/104584, l='MpServer', x=501,50, y=67,00, z=-1271,50], vn['Creeper'/104394, l='MpServer', x=541,50, y=41,00, z=-1309,50], wa['Skeleton'/104397, l='MpServer', x=516,31, y=45,00, z=-1224,34], uz['item.item.reeds'/103756, l='MpServer', x=531,28, y=63,39, z=-1283,53], wc['Spider'/104396, l='MpServer', x=519,50, y=44,00, z=-1226,50], wa['Skeleton'/104207, l='MpServer', x=488,50, y=19,00, z=-1314,50], ts['Turtle'/103759, l='MpServer', x=468,55, y=68,00, z=-1291,89], uz['item.item.stick'/103758, l='MpServer', x=520,00, y=66,00, z=-1281,88], ts['Turtle'/103760, l='MpServer', x=470,50, y=65,00, z=-1287,47], wa['Skeleton'/104405, l='MpServer', x=489,25, y=14,00, z=-1280,53], vn['Creeper'/104406, l='MpServer', x=521,50, y=22,00, z=-1276,50], wc['Spider'/104280, l='MpServer', x=491,50, y=15,00, z=-1298,50], wa['Skeleton'/104223, l='MpServer', x=453,50, y=34,00, z=-1314,50], wa['Skeleton'/104419, l='MpServer', x=494,50, y=25,00, z=-1319,50], we['Zombie'/104421, l='MpServer', x=477,50, y=15,00, z=-1256,50], we['Zombie'/104299, l='MpServer', x=486,50, y=15,00, z=-1276,50], wa['Skeleton'/104492, l='MpServer', x=513,47, y=24,00, z=-1285,09], vn['Creeper'/104498, l='MpServer', x=543,50, y=47,00, z=-1229,50], bex['I_Lik3_Wqlfys'/55924, l='MpServer', x=500,10, y=67,02, z=-1271,06], vn['Creeper'/104501, l='MpServer', x=511,50, y=38,00, z=-1231,50], bew['GigaAdamYT'/150, l='MpServer', x=499,92, y=68,01, z=-1272,24], vn['Creeper'/104500, l='MpServer', x=510,50, y=38,00, z=-1232,50], vn['Creeper'/104502, l='MpServer', x=514,50, y=38,00, z=-1232,50], vn['Creeper'/104315, l='MpServer', x=475,50, y=23,00, z=-1296,50], bex['I_Lik3_Wqlfys'/55924, l='MpServer', x=500,10, y=67,02, z=-1271,06]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:281aece:1538) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bdb.a(SourceFile:309)
	at ave.b(SourceFile:2311)
	at ave.a(SourceFile:334)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 498654352 bytes (475 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8.8
	LWJGL: 2.9.4
	OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz`

Plugins: ViaVersion 3.1.1, ViaBackwards 3.1.1, ViaRewind 1.5.1

Thanks for all answers!!!

**Comment by KennyTV** [comment]
All of your Via plugins are outdated.
