### ISSUE TITLE
Fishing rod animation on 1.8

### ISSUE THREAD

**Issue by ZedarYT** [ViaVersion/ViaRewind#225]
Fishing rods are slightly stuttering when used in 1.8

1. Login on 1.8
2. Use a fishing rod

Expected behaviour
Smooth usage of the fishing rod and no stuttering

ViaVersion Dump
https://dump.viaversion.com/42ef3359698ddcfbc144273baf2e3a28c4585852bb6b3654dd997ad80e5ffe42

Additional server info
Bungeecord

Video:

1.8:

https://gyazo.com/617857f87116f959e1dcc58c499b8c6e

1.16:

https://gyazo.com/a0dafe235f563b7c99224979a41bc83a

**Comment by Gerrygames** [comment]
Looks like a client-side issue. Or the movement code slightly changed. Nothing can be done about that.
