### ISSUE TITLE
1.8.9 on 1.16.4

### ISSUE THREAD

**Issue by Magzypotato** [ViaVersion/ViaRewind#226]
Describe the bug, provide any errors
I host a 1.16.4 bungeecord network. Me and my friends want to play on 1.8.9 since its just the best for bedwars and other mini-games. When i joined i got this message on my screen https://imgur.com/a/frv4yz4. This is also what i see in the server it doesnt work https://paste.gg/p/anonymous/19cf647e0ced4d12ba48d2c3277b4d58 . BTW i have to say that this does work in all the other server in my network, its just not working in this one.

Expected behaviour
Simply join the 1.16.4 with 1.8.9 minecraft version without any problems.

ViaVersion Dump
https://dump.viaversion.com/d0616fdd9af56ddb99a77f90eddb3c90313da2f11d1cf22f0aafc67cd910cb8b

Additional server info
I use Bungeecord. I use PaperMC 1.16.4 to host it. This is a photo of all my plugins inside the bungeecord folder https://imgur.com/a/UFMySbF . This is a photo of all my plugins inside the server i didnt manage to join https://imgur.com/a/pQ8zEFw .

Checklist

 I have included a Viaversion dump
 If applicable, I have included a paste (not a screenshot) of the error
 I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Blocksnmore** [comment]
If this works on all your servers besides this specific one it's likely an issue with one of your plugins. I would suggest trying via* without any other plugins

**Comment by Magzypotato** [comment]
> If this works on all your servers besides this specific one it's likely an issue with one of your plugins. I would suggest trying via* without any other plugins

Yeah it worked after i tried without all of my plugins. But i need to check some more.

**Comment by Blocksnmore** [comment]
> > If this works on all your servers besides this specific one it's likely an issue with one of your plugins. I would suggest trying via* without any other plugins
> 
> Yeah it worked after i tried without all of my plugins. But i need to check some more.

That means it's one of your plugins causing issues, i would suggest adding the plugins 1 at a time and find out the culprit

**Comment by Magzypotato** [comment]
> > > If this works on all your servers besides this specific one it's likely an issue with one of your plugins. I would suggest trying via* without any other plugins
> > 
> > 
> > Yeah it worked after i tried without all of my plugins. But i need to check some more.
> 
> That means it's one of your plugins causing issues, i would suggest adding the plugins 1 at a time and find out the culprit

It is multiverse-core. So what do i do now?

**Comment by Blocksnmore** [comment]
I would try using the latest version of the plugin since multiverse doesn't cause issues from my experience

**Comment by Magzypotato** [comment]
> I would try using the latest version of the plugin since multiverse doesn't cause issues from my experience

Where do i find the absolute latest version ?

**Comment by Blocksnmore** [comment]
first result on google https://dev.bukkit.org/projects/multiverse-core/files

**Comment by Magzypotato** [comment]
i found it out:

https://paste.gg/p/anonymous/e6bdc5897943408c8e1c9e63b5b0bd59

I changed the <biome> stuff with THE_VOID because it showed an error in console if not but i just changed back, so its good.
