### ISSUE TITLE
Players not being rendered at times

### ISSUE THREAD

**Issue by SprigWave** [ViaVersion/ViaRewind#228]
---
name: Players not being rendered at times
about: When a player dies, they cannot see other players.
---

**Describe the bug, provide any errors**
So when a player joins the server, a player can see them. But let's say player 1 dies. Player 1 cannot see player 2 but player 2 can see player 1. Player 2 can interact with player 1 but player 1 cannot interact with player 2.

**How can we reproduce it?**
Unfortunately, I don't know what is causing the issues explained.

**Expected behavior**
For players to be rendered universally.

**Screenshots**
There is no screenshots needed.

**ViaVersion Dump:**
https://dump.viaversion.com/69558e3b143b6290149e5714861c8afe025c0438b44235a32e79da29c4603ac8

**Additional server info**
I do not use a proxy. Although I do use these plugins listed:
ClearLag, CombatPlus, CoreProtect, Dynmap, Essentials, EssentialsChat, EssentialsGeoIP,  (WorldEdit)FastAsyncWorldEdit, floodgate-bukkit, Geyser-Spigot, ImageOnMap, KeepDeathDrop, LaggRemover, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, OpenInv, PlugMan, ProtocolLib, SuperVanish, TAB, TrollBoss, UberEnchant, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard

**Checklist**
- [✓ ] I have included a ViaVersion dump
- [ ✓] If applicable, I have included a paste (not a screenshot) of the error
- [ ✓] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Gerrygames** [comment]
Please provide a video.
