### ISSUE TITLE
Add an option to replace submerged grass with just water on versions where the grass is ugly

### ISSUE THREAD

**Issue by nathanfranke** [ViaVersion/ViaRewind#229]
What 1.8 clients currently see:
![image](https://user-images.githubusercontent.com/14253836/100666918-77180e00-331f-11eb-8ff8-dd0ba1997368.png)

What 1.8 clients should see with this option:
![image](https://user-images.githubusercontent.com/14253836/100666933-7e3f1c00-331f-11eb-9e5a-530a5ea50575.png)

**Comment by Gerrygames** [comment]
This is a ViaBackwards issue and ViaBackwards mappings can be customized.
