### ISSUE TITLE
1.8 clients disconnect when 1.9 bossbar is sent by server (refCnt: 0)

### ISSUE THREAD

**Issue by NEZNAMY** [ViaVersion/ViaRewind#232]
**Describe the bug, provide any errors**
When joining a 1.15.2 server where 1.9 bossbar packet is sent, 1.8 clients get disconnected with following message http://prntscr.com/vz66j2

**How can we reproduce it?**
1. Start a 1.15.2 server
2. Install latest build of all via plugins and a plugin that sends bossbar packets
3. Join with 1.8 client

**Expected behaviour**
Bossbar packets translated into entities

**Screenshots**
http://prntscr.com/vz66j2

**ViaVersion Dump**
https://dump.viaversion.com/ada4cd4e9b665005ee5736f64362fea7472ac4b8e8cfc3a48630c7f4f38e28b2

**Additional server info**

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
I can't replicate this on a 1.15.2 server nor a 1.12.2 server. Perhaps I need a config change or something in TAB? I enabled bossbars in the default bossbar.yml

1.15.2 - https://dump.viaversion.com/f877f5403fc7fd6b3282d6bafbd798fd5bf3ba1c4c8fbc7d377aaa6cd7f4c01b
1.12.2 - https://dump.viaversion.com/5e9024233637a5776a83d1708be992fc6090009031f38f8faba9cf04070f43ba

**Comment by NEZNAMY** [comment]
I was able to successfully reproduce it with a plugin as trivial as this https://pastebin.com/2wMxjwij.
Disconnected immediately on join http://prntscr.com/x806ob
Via dump https://dump.viaversion.com/4f67b7659a1a244476c401abfc15bf214292416a85498d1d3fa2b7d72f1a107b (the "test" plugin is literally the paste above).

**Comment by FormallyMyles** [comment]
I tried with the plugin provided and it doesn't seem to error still, I downloaded older Via* jars to match yours and just seems to work fine.

Here's my dump - https://dump.viaversion.com/f37a7060814f7af48d0f1d857ebaa1f28946349f2e466d273ea1080675f2dcea (also tested Java 8 in the case it was that)
Image - https://i.imgur.com/9YGaFzL.png

**Comment by NEZNAMY** [comment]
Turns out to be caused by `online-mode=false` in server.properties file. With true it works.

**Comment by FormallyMyles** [comment]
Thanks for the info, based on my current findings:

Works on ViaVersion 3.1.0, ViaBackwards 3.1.0, ViaRewind 1.5.0
Issues on 3.1.1, 3.1.1, 1.5.1 (unsure if just bad mappings, might be my end)
Error appears on 3.2.0, 3.2.0, 1.5.3

Commenting out updateLocation in WitherBossBar.java seems to cause the issue not to happen. Not really sure what the cause is, unfortunately (may be related to a change in ViaVersion/Backwards).

**Comment by NEZNAMY** [comment]
Looks like this is a duplicate of #222 and possibly #243 .
