### ISSUE TITLE
1.8 Players causing server crash from Too many output messages (Console spam)

### ISSUE THREAD

**Issue by Welcome234** [ViaVersion/ViaRewind#236]
Here is the error on stack trace

https://pastebin.com/sQJQYtw5

Here is the error logs on my host:
![image](https://user-images.githubusercontent.com/68016689/102542263-6d293580-40a9-11eb-831f-53b9136cf4fa.png)

**Comment by Gerrygames** [comment]
That's most likely a player sending bad data.
