### ISSUE TITLE
Scoreboard text messed up on 1.8 servers

### ISSUE THREAD

**Issue by ZedarYT** [ViaVersion/ViaRewind#238]
The scoreboard text is fine if you are playing on 1.8, however, if you're playing on 1.16 the scoreboard messes up some letters. I assume it has to do something with the max character limit on the scoreboards and as a result, some text appears weird on the scoreboard. 
![image](https://user-images.githubusercontent.com/74577732/102576318-36f8af80-40c3-11eb-9d25-c35b472c0b8b.png)

**Comment by Gerrygames** [comment]
Could you test what the scoreboard looks like on a 1.9 client?
