### ISSUE TITLE
Wrong packetorder

### ISSUE THREAD

**Issue by LIWKK** [ViaVersion/ViaRewind#239]
ViaRewind makes players to send PacketPlayInArmAnimation on post (normally sent on pre) when u place or break blocks.

**Comment by Gerrygames** [comment]
https://github.com/ViaVersion/ViaRewind/blob/80fd245fb2df93b290e1fd1ef75d689ae54d806f/core/src/main/java/de/gerrygames/viarewind/protocol/protocol1_8to1_9/packets/PlayerPackets.java#L563-L575

You're welcome to PR a better solution for this issue.

**Comment by LIWKK** [comment]
InArmAnimation when placing or breaking block is sent on pre every version of minecraft.

**Comment by Gerrygames** [comment]
But the order of packets when hitting entities has changed. There is no information in the animation packet on which action it was triggered by.

**Comment by LIWKK** [comment]
I'm unsure if it changed attackEntity is still called pre in 1.12.2 source

**Comment by LIWKK** [comment]
Also protocolsupport causes no issues with this, only ViaRewind.

**Comment by Seanoo1** [comment]
> Also protocolsupport causes no issues with this, only ViaRewind.

Protocolsupport does not show tools attack cooldown to 1.8.9- player. I think that is why.
