### ISSUE TITLE
Client kick when connecting with a 1.8.x client on 1.12.2

### ISSUE THREAD

**Issue by Chappy202** [ViaVersion/ViaRewind#241]
**Bug Description**
https://sourceb.in/GApPoz0xfi - When using ViaVersion 3.2.0 alongside ViaRewind 1.5.2 everything works. Updating it breaks the 1.8.x client connections.

**How to reproduce**
1. Create a 1.12.2 Server running ViaVersion 3.2.1 and up alongside ViaBackwards-3.2.0 and VieRewind-1.5.3
2. Attempt to connect to the server using client version 1.8.9
3. The client should be disconnected, with the error message in console.

**Expected behaviour**
The 1.8.x clients should be able to connect like any other version.

**Screenshots**
https://i.imgur.com/aqEunmP.png

**ViaVersion Dump**
https://dump.viaversion.com/d8ce6668764ee527483ea8a493bdbf6cd143190021011ef44c0aa34e4bd50e8c

**Additional server info**
We use Flamecord 1.4.6 for our proxy.
Running Paperspigot 1.12.2 on the affected server.
Here is our plugins https://i.imgur.com/xp6H1FW.png

**Checklist**
- [✓] I have included a Viaversion dump
- [✓] If applicable, I have included a paste (not a screenshot) of the error
- [✓] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**More info**
I tried downgrading ViaVersion to an older version (3.2.0) and that works, the error disappears and 1.8 clients can connect, but this then in turn prevents 1.16.4 clients to connect due to the plugin then being outdated.

Using any version above 3.2.1 (Including dev builds), cause the error to occur and prevents 1.8.x clients from connecting.

**Comment by Gerrygames** [comment]
Could you try if this issue occurs without ProtocolLib?

**Comment by Gerrygames** [comment]
Duplicates #240
