### ISSUE TITLE
1.8.9 Scoreboard Issue

### ISSUE THREAD

**Issue by nevetS-718** [ViaVersion/ViaRewind#243]
When I try to join a bedwars game on a 1.8.9 client, I get kicked with this error message, `Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0` 
When using other versions, it works. I believe it may have something to do with the scoreboard. I am running a 1.14.4 paper server on a normal bungeecord network. I also tried using the latest versions given in the Via Discord server and I got the same kick message.
Via Dump:
https://dump.viaversion.com/6a34390b26771debca0a030c0dc7369613716f3ff2f7ae817d707b2dd2c0ebde

**Comment by Gerrygames** [comment]
Please provide the full error. You might have to set debug=true in server.properties.
