### ISSUE TITLE
*CLIENT CRASH* (1.7.10) - HolographicDisplays Entity Metadata error

### ISSUE THREAD

**Issue by kmecpp** [ViaVersion/ViaRewind#244]
**Describe the bug, provide any errors**
I have a 1.12.2 Paper server and a Spawn with a lot of Holograms. Everyone in Spawn with a 1.7.10 client crashes sometimes when running /hd reload or updating a lot of holograms at once with another plugin. This is the client error: https://pastebin.com/raw/PKVarTu8

Stuff I tried:
- Removing FAWE
- Using Holographic Displays 2.2.6, 2.3.2, and 2.4.5 (latest)
- Using all the latest ViaVersion builds from https://ci.viaversion.com
- Tried connecting to the lobby directly bypassing our proxy software Travertine
- Tried connecting with a vanilla client instead of forge

None of the above worked

**How can we reproduce it?**
Not entirely sure how to reproduce it. /hd reload causes it sometimes. We also have a Holographic Displays parkour leaderboard which consistently crashes everyone when it is reloaded. Here is the code that reloads that Hologram leaderboard if that is useful: https://pastebin.com/raw/ekgbkLJX

The problem is only caused when the server an client are different versions. 1.7.10 server/client and 1.12.2 server client work fine.

**ViaVersion Dump:**
- https://dump.viaversion.com/768aa4cad593d8a84dfb6318dc0ae4b154d88ea3a53df9471116f06f4757cee5

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by kmecpp** [comment]
This PR claimed to fix the problem and has more information https://github.com/ViaVersion/ViaRewind/pull/81 not sure why the author closed it.

**Comment by turnolos** [comment]
I am also having this problem

**Comment by f7h2938h3** [comment]
> This PR claimed to fix the problem and has more information #81 not sure why the author closed it.

Hey, I'm so sorry for the extremely late response, I don't use this github account anymore. I believe I closed the PR because the issue seemed to fix itself without my change and I was no longer confident that my commit would solve the issue I was having initially. It's possible it does actually fix the issue, but without it the chances of it happening are small thus making it hard to reproduce.
