### ISSUE TITLE
/offhand command is undocumented

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaRewind#247]
https://github.com/ViaVersion/ViaRewind/blob/3580caab91b678d0ceb268c489f36d83ba2d7bfa/core/src/main/java/de/gerrygames/viarewind/protocol/protocol1_8to1_9/packets/PlayerPackets.java#L316

**Comment by WolfyRed** [comment]
?

**Comment by FlorianMichael** [comment]
Now part of the configuration file.
