### ISSUE TITLE
left hand item does not visible to 1.8.9- client on 1.9+ servers

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaRewind#248]
**How can we reproduce it?**
1. Login with 1.8.9- client on 1.9+ servers
2. held item with left hand, you can't see left hand items.

**Expected behaviour**
Item should visible on left on the screen(I think it is possible with summon falling block & item hologram and track the player)

**Checklist** (mark with [X] to check)
- [Not needed] I have included a ViaVersion dump
- [Not needed] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
The 1.8 client doesn‘t support that.
