### ISSUE TITLE
Rabbit + Endermite Replacement (1.7.10)

### ISSUE THREAD

**Issue by rowan-smith** [ViaVersion/ViaRewind#25]
https://gist.github.com/4832b508eab672f7f035b3f5f70b34b0

**When a guardian is spawned nothing appears and the player can take damage.**
https://gyazo.com/c6a606533c81cfac3258e0f7b0f0d3f5

**Also you can't see rabbits**
https://gyazo.com/5e768f37872f5960bd350f11ac564abf

**UPDATE: Endermite's as well.**

**Comment by Gerrygames** [comment]
Neither rabbits nor guardians did exist in 1.7.x

**Comment by rowan-smith** [comment]
How does ViaVersion handle seeing older mobs?
I know Protocol Support display them as other mobs.

**Comment by Gerrygames** [comment]
ViaVersion does not have this problem. All entities existing in older versions do also exist in newer ones. ProtocolSupport is replacing them with old entities. I think I will do this in a future update.
