### ISSUE TITLE
1.16.4 Server, 1.8.9 Client - Chunk loading very slow, players fall through blocks.

### ISSUE THREAD

**Issue by nathanfranke** [ViaVersion/ViaRewind#251]
**Describe the bug, provide any errors**
See this video: https://www.youtube.com/watch?v=Hl76Q0D88vU

**How can we reproduce it?**
1. Start a 1.16.4+ server, make sure all four Via* plugins are installed and latest.
2. Join on 1.8.X
3. Notice chunks load slowly
4. Re-log, they load fast again. While you're on the server, make a platform in the air. Restart the server and reconnect on top of the platform. You will fall through.

**Expected behaviour**
Chunks load fast just like in 1.8

**Screenshots**
https://www.youtube.com/watch?v=Hl76Q0D88vU

**ViaVersion Dump:**
https://dump.viaversion.com/772d09a832c3cb53dba23c6bb7803655b72bdc61f7265a297540f876e8afd5de

**Additional server info**
Reproducible without Proxy

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
Translation takes time. And there are no bulk chunk packets in 1.9+ and the 1.8 client does not like single chunk packets. If you want chunks to load fast, use a modern client.
