### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Gilthunderx** [ViaVersion/ViaRewind#253]
**Describe the bug, provide any errors**
Hello Guys Im having excessive spam from the plugin viaversion and ViaBackwars. 

Spam # 1 : https://pastebin.com/uhueFzNx
Spam # 2 : https://pastebin.com/dBFTfART

**How can we reproduce it?**

**Expected behaviour**
There was no spam when my server was 1.16.4

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/8277c8bec6ee0a0d43f356c873e9a4a0834cb3c8a9f0c1122acff48419abfb16

**Additional server info**
Plugins (36): AnimatedScoreboard, BungeeGuard, ChatControl, Citizens, ClashWars, ConditionalCommands, CraftingStore, CratesPlus, DeluxeChat, DeluxeMenus, Essentials, GadgetsMenu, HolographicDisplays, HolographicPlaceholders, LeaderHeadsRevamped, LevelPoints, LuckPerms, MobDisabler, Multiverse-Core, NoCheatPlus, NoRainReloaded*, OldCombatMechanics, PlaceholderAPI, ProtocolLib, spark, SuperVanish, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

Using 1.16.5 Purpur
**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Blocksnmore** [comment]
To fix spam 2 set `suppress-conversion-warnings` and `suppress-metadata-errors` to true in the viaversion config, and for the first spam try replacing your via* jars with 

ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar
