### ISSUE TITLE
Horse holograms not working Correctly

### ISSUE THREAD

**Issue by NotHappyxd** [ViaVersion/ViaRewind#254]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
When using viarewind, horses used for holograms on 1.7.10 will show even if the variant is invalid. 

**How can we reproduce it?**
https://paste.gg/p/anonymous/cf79126478db4a49ab6e7b9c912a1bd2 Code to spawn holograms on 1.7.10
Join and find the hologram/horse

**Expected behaviour**
The horse should not be visible

**Screenshots**
Without viarewind: https://i.imgur.com/ZKmXe9s.png
With viarewind: https://i.imgur.com/eRrH2fI.png

**ViaVersion Dump:**
https://dump.viaversion.com/6b8dac9492c3937b62411cb8c69555b72802dbecdf100b632a5e5dd67c477639

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I do not use a proxy. I use tacospigot fork, viaversion, ProtocolLib, custom KitPvP core and a custom permission + punishment core.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
This is unsupported. You just need to spawn an invisible armor stand and ViaRewind will replace it with a horse.
