### ISSUE TITLE
Disabled Plugin when the Server is On

### ISSUE THREAD

**Issue by ivandelp** [ViaVersion/ViaRewind#255]
**Describe the bug, provide any errors**
Plugin is disabled when I start the Server. I have Paper 1.12.2 and last version of ViaVersion and ViaBackwards but ViaRewind gets me error. https://pastebin.com/chL5emb4

**How can we reproduce it?**
1. Start the Server
2. Show Logs
3. Error displayed

**Expected behaviour**
Problem version or update the plugin by developer

**Screenshots**
![image](https://user-images.githubusercontent.com/27789407/105849756-1b959400-5fe1-11eb-85a8-89694acd1483.png)

**ViaVersion Dump:**
https://dump.viaversion.com/a19f019ee679028c816e1488049a90726f49c5bba4d0863a76be30da111784da

**Additional server info**
FlameCord

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by FormallyMyles** [comment]
Update to the latest from the ci / spigot.
