### ISSUE TITLE
Disabled Plugin when the Server is On, If I update, error is shown too

### ISSUE THREAD

**Issue by ivandelp** [ViaVersion/ViaRewind#256]
**Describe the bug, provide any errors**
Plugin is disabled when I start the Server. I have Paper 1.12.2 and last version of ViaVersion and ViaBackwards but ViaRewind gets me error. https://pastebin.com/chL5emb4

**How can we reproduce it?**
1. Start the Server
2. Show Logs
3. Error displayed

**Expected behaviour**
Problem version or update the plugin by developer

**Screenshots**
![image](https://user-images.githubusercontent.com/27789407/105857174-505a1900-5fea-11eb-9ed6-aeb88ddc7a41.png)

**ViaVersion Dump:**
https://dump.viaversion.com/7228f53367a62c4d832609b7548ed482b9968a016dfced4545614abfab9885f3

**Additional server info**
FlameCord

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

I don't know what versions download to work correct in PaperMC 1.12.2

Only ViaRewind not work, help with links to solve that.

**Comment by FormallyMyles** [comment]
The latest from our CI should work:

ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar
