### ISSUE TITLE
Servers 1.13+. 1.13> players can't see the Lightning

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaRewind#257]
**Describe the bug, provide any errors**
Servers 1.13+. 1.13> players can't see the Lightning
Players under 1.13 cannot see lightning on a 1.16 server. 

**How can we reproduce it?**
1. Login on 1.13> version on minecraft.'
2. Join a 1.16 server'
3. Execute a lightning and it will not show. 

**Expected behaviour**
I expected the lightning to show. 

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/bfcf90c16b4272e40d61b0663ebb5be51cd3837777f7e8c000b23f6c8391e404

**Additional server info**
Bungeecord, paper 1.16.4

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
This is a ViaBackwards issues and was fixed.
