### ISSUE TITLE
1.16 server, players in 1.16 can't see the Cobblestone wall block. 

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaRewind#258]
**Describe the bug, provide any errors**
in 1.16 servers players in 1.16 can't see the Cobblestone wall block. 

**How can we reproduce it?**
1. Login on 1.16'
2. On 1 1.16 client. 
3. The cobblestone walls are not shown. 

**Expected behaviour**
I expected to be able to see them. 

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/bfcf90c16b4272e40d61b0663ebb5be51cd3837777f7e8c000b23f6c8391e404

**Additional server info**
Bungee, paper 1.16.4

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
ViaRewind does not change anything for players connected with the native version.
