### ISSUE TITLE
1.8 users can't see bow animation

### ISSUE THREAD

**Issue by JoelDeadMach** [ViaVersion/ViaRewind#259]
**Describe the bug, provide any errors**
When a 1.9+ player is aiming, you don't see the animation. 

**How can we reproduce it?**
1. Login on 1.8 client'
2. Aim with a 1.9 client to a 1.8 client
3. You don't see the animation.

**Expected behaviour**
As 1.8 client, you should be able to see the higher version player aiming.

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/df3241771f52ea22ead24a8a3a444314d5dbc8a6165431ecac68f2816085e10f

**Additional server info**
I use everything on spigot side, no bungee. 
http://i.insanemc.net/javaw_FifOrE8JPX.png

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
Duplicates #64
