### ISSUE TITLE
Invincible blocks and players.-.

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaRewind#263]
**Describe the bug, provide any errors**
No errors but sometimes when a 1.8.9 player joins a 1.16.x server the newly placed blocks and players randomly get invincible.

**How can we reproduce it?**
1. Login on 1.8.9'
2. join a 1.16.3 server'
3. Play and now on random occasions new placed blocks and players will be invincible. 

**Expected behaviour**
Things to not be invincible.-.

**ViaVersion Dump:**
- https://dump.viaversion.com/8df8ed5980404127378b08fb5ed067c0aca4603e9dd199d77bfe11eca3079cee

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
it's a bungee. Latest bungee version with a Paper 1.16.3 server. 
Plugins (42): LuckPerms, BetterReports, PlaceholderAPI, spark, BuycraftX, ConsoleSpamFix, OldCombatMechanics, AntiDrop, Void2Spawn, VoidGenerator, GodsEyeSync, ViaVersion, floodgate-bukkit, Vault, ViaBackwards, Lores, ViaRewind, WorldEdit, AnimatedScoreboard, Elo, Essentials, ViaRewind-Legacy-Support, CommandPanels, WorldGuard, ProtocolLib, Multiverse-Core, GodsEye, DeluxeChat, TheBridge, BungeeGuard, Multiverse-Inventories, Duels, TAB, ItemJoin, EssentialsSpawn, Bedwars, PremiumVanish, Skript, GodsEyeGeyserMC, HolographicDisplays, HolographicExtension, ServerNPC

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
Please provide a video.

**Comment by Porkason** [comment]
> Please provide a video.

https://youtu.be/X9Jpx-Lx3Z8

**Comment by Gerrygames** [comment]
Unfortunately this is not really fixable. The 1.8 client just doesn't like receiving many chunks quickly. There are several race conditions in it which causes some chunks not being prepared for rendering and some entities not being added to chunks correctly. This is probably why the chunk bulk packet existed. Theses kind of issues do happen on native 1.8 servers, just less often because they do use the chunk bulk packet. Combining the new chunk load packets into chunk bulk packets isn't really possible.

**Comment by Seanoo1** [comment]
I known as this issue is because of view-distance. I set it to 2 and it was fixed

**Comment by Porkason** [comment]
> Unfortunately this is not really fixable. The 1.8 client just doesn't like receiving many chunks quickly. There are several race conditions in it which causes some chunks not being prepared for rendering and some entities not being added to chunks correctly. This is probably why the chunk bulk packet existed. Theses kind of issues do happen on native 1.8 servers, just less often because they do use the chunk bulk packet. Combining the new chunk load packets into chunk bulk packets isn't really possible.

So you are telling me it's not fixable?

**Comment by Xernium** [comment]
Yes. This is not really fixable without a lot of redesigns and compromises elsewhere.

**Comment by Twiz0x** [comment]
@Porkason just change your bedwars plugin, I had the same issue

**Comment by Porkason** [comment]
> @Porkason just change your bedwars plugin, I had the same issue

It happens on all our servers :3 it has nothing to do with the bw plugin

**Comment by Porkason** [comment]
> I known as this issue is because of view-distance. I set it to 2 and it was fixed

But then we can’t see anything :3
