### ISSUE TITLE
1.8.x player getting kicked for no reason. 

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaRewind#264]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
Login on 1.8.9'
join a 1.16.3 server'

**Expected behaviour**
That players would not get kicked. 

**ViaVersion Dump:**
- https://dump.viaversion.com/8df8ed5980404127378b08fb5ed067c0aca4603e9dd199d77bfe11eca3079cee

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
it's a bungee. Latest bungee version with a Paper 1.16.3 server.
Plugins (42): LuckPerms, BetterReports, PlaceholderAPI, spark, BuycraftX, ConsoleSpamFix, OldCombatMechanics, AntiDrop, Void2Spawn, VoidGenerator, GodsEyeSync, ViaVersion, floodgate-bukkit, Vault, ViaBackwards, Lores, ViaRewind, WorldEdit, AnimatedScoreboard, Elo, Essentials, ViaRewind-Legacy-Support, CommandPanels, WorldGuard, ProtocolLib, Multiverse-Core, GodsEye, DeluxeChat, TheBridge, BungeeGuard, Multiverse-Inventories, Duels, TAB, ItemJoin, EssentialsSpawn, Bedwars, PremiumVanish, Skript, GodsEyeGeyserMC, HolographicDisplays, HolographicExtension, ServerNPC

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Seanoo1** [comment]
You didn't followed the checklist.
Also your protocolLib is outdated. You need 4.6.0
