### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException:  io.netty.util.IllegalReferenceCountException: refCnt: 0

### ISSUE THREAD

**Issue by codergautam** [ViaVersion/ViaRewind#272]
**Describe the bug, provide any errors**
Internal Exception: io.netty.handler.codec.DecoderException: 
io.netty.util.IllegalReferenceCountException: refCnt: 0

**How can we reproduce it?**
1. Make a server on aternos
2. Add viaversion, viabackwards, viarewind, multiverse, and screamingbedwars
3. Setup a bedwars game
4. Join it using /bw join on 1.8 or 1.7
5. It will kick you out with an error

**Expected behaviour**
Doesnt kick me out and actually lets me play the game

**Screenshots**
![image](https://user-images.githubusercontent.com/66850133/107700465-2147d680-6c7d-11eb-871f-d0dbe8c0b183.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/4ca8f363b50df0c740c0c9dd637b691bd2f97d215798c54f5cde2f6c04644c1b

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No. I'm using viaversion, viabackwards, viarewind, multiverse, and screamingbedwars

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by codergautam** [comment]
I have fixed this issue, it was a problem with bossbars
Disabling the bossbars in the ScreamingBedwars config.yml fixed it
```
bossbar:
  use-xp-bar: false
  lobby:
    enable: false
    color: YELLOW
    style: SEGMENTED_20
  game:
    enable: false
    color: GREEN
    style: SEGMENTED_20
```

**Comment by Rollczi** [comment]
The same problem.
Removing bossbar is not a solution.
This is a bug that needs to be fixed.
He kicks me out of the boss bar during the ender dragon fight.
