### ISSUE TITLE
ReOpen

### ISSUE THREAD

**Issue by Rollczi** [ViaVersion/ViaRewind#273]
[https://github.com/ViaVersion/ViaRewind/issues/272](https://github.com/ViaVersion/ViaRewind/issues/272)

The same problem. Removing bossbar is not a solution.
This is a bug that needs to be fixed.
He kicks me out of the boss bar during the ender dragon fight.

**Comment by Seanoo1** [comment]
I known as bossbar was fixed on dev branch. You didn't followed the checklist. Redownload all three plugins to dev build from http://ci.viaversion.com
