### ISSUE TITLE
Issues connecting - NPE

### ISSUE THREAD

**Issue by Astonic11** [ViaVersion/ViaRewind#276]
**Describe the bug, provide any errors**
Im having trouble with players connecting https://paste.gg/p/anonymous/40ef1afadbc94a97aff240d5ced26287

**How can we reproduce it?**
1. Versions lower than 1.12.2
3. The '[Proxy] Lost connection to the server ' is displayed wrong

**Expected behaviour**
That a player can connect from 1.8-1.16 onto the network

**Screenshots**
(https://user-images.githubusercontent.com/55540659/107965459-d692cb00-6faa-11eb-9fb2-a39c453d413c.PNG)

**ViaVersion Dump:**
https://dump.viaversion.com/64d9d277591ac6ae4310ecdff0069a0ba90de998d9afc65d79ed8cb689f2c5b6

**Additional server info**
Yes we are using bungeecord, all of our server are running Paper 1.12.2

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by creeper123123321** [comment]
Can you test latest ci.viaversion.com build?
