### ISSUE TITLE
Lightning cannot be seen on Minecraft 1.8

### ISSUE THREAD

**Issue by awgybop1** [ViaVersion/ViaRewind#277]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Join the server from Minecraft 1.8
2. Try to summon lightning.

**Expected behaviour**
When lightning is spawned, it should be rendered on the client.

**Screenshots**
These wouldn't really show much.

**ViaVersion Dump:**
- https://dump.viaversion.com/40af07b87eef5eb3d7a566dfdb1f93b525210b1d0fa25e903c373d7e3c9d721d

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Paper 1.16.5 server, too many plugins to list, but none of which should interfere.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Jo0001** [comment]
Works fine with Via* 4.0.0
