### ISSUE TITLE
Sound Bug 

### ISSUE THREAD

**Issue by arttwart** [ViaVersion/ViaRewind#286]
**Describe the bug, provide any errors**
Block place sounds are not hearable: https://srcb.in/i6saKtf9Ce

**How can we reproduce it?**
1. Install Paper 1.16.5
2. Install all Via plugins
3. Join the server
4. Place a block
5. Check the console

**Expected behaviour**
We should hear sound.

**ViaVersion Dump:**
https://dump.viaversion.com/5dc99cd39715980c282b9cd204fe2ae49d264fbc034b0a86e76caefcc5c00946

**Additional server info**
I am using Paper 1.16.5 for backend, and Waterfall for proxy server.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by xenforq** [comment]
Having the same issues here, no real differences in our setups. Personally not hooked up to any proxy server at the moment.

**Comment by creeper123123321** [comment]
Should be in via rewind legacy support issue tracker

**Comment by arttwart** [comment]
Fixed in latest build: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/9/
