### ISSUE TITLE
Some Command Blocks are invisible [BUG]

### ISSUE THREAD

**Issue by WolfyRed** [ViaVersion/ViaRewind#299]
**Describe the bug, provide any errors**
While some Command Blocks render just fine, some Command Blocks don't render at all, showing up as air blocks, as if... they are invisible!
*It even crashes if you touch the invisible command blocks, and sometimes, if you're just near them when joining!*

**Bug Details**
Command Block Crashes: occur in **1.7.x-1.8.x**
Invisible Command Blocks: only in **1.8.x**

**How can we see the Invisible Command Blocks?**
1. Login on 1.8.x
2. Go to a Command Block edited in a newer version
3. The Command Block may be completely invisible!
4. If it's invisible, step on it, and prepare to crash your client.

**Expected behaviour**
The Command Block to at least render properly...

**Screenshots**
![image](https://user-images.githubusercontent.com/66114400/112971164-f32f3080-911c-11eb-9ca0-e53f2b54d849.png)
![image](https://user-images.githubusercontent.com/66114400/112971242-06da9700-911d-11eb-8ead-f9d638944c9e.png)
![image](https://user-images.githubusercontent.com/66114400/112971283-1063ff00-911d-11eb-8908-4294550f8610.png)

**Media**
https://user-images.githubusercontent.com/66114400/112970086-d5ad9700-911b-11eb-900a-8a1365e829d1.mp4

**ViaVersion Dump:**
https://dump.viaversion.com/ee6a8e31945da25b0a6c89f513acfe5f09c314be21b116c24151cc7a6f5a4cde

**Additional server info**
*Travertine, 1.7.x-1.16.x protocols.*
Plugins: `GeyserBungee`, `ServerListMOTD`, `BungeeTabListPlus`, `RedisBungee`

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaRewind/issues/303
