### ISSUE TITLE
end_block is replaced with air

### ISSUE THREAD

**Issue by Thin-Troll** [ViaVersion/ViaRewind#302]
**Describe the bug, provide any errors**
No Error

**How can we reproduce it?**
1. Login on 1.8 - 1.8.9'
2. look at the end_ block or stand on it and get stuck.
3. done 
**Expected behaviour**
Expected automatic replacement for the most similar block.

**Screenshots**
1.8
![image](https://user-images.githubusercontent.com/61376903/114011570-cdbdc780-987e-11eb-9153-96f4ea031254.png)
1.12.2
![image](https://user-images.githubusercontent.com/61376903/114011604-d910f300-987e-11eb-87ce-fb4453ddebd9.png)

**ViaVersion Dump:**
https://dump.viaversion.com/3cfa3c5fa9686cf3371e6dd61c1e5248b8f816599fd4a363a885212a205ac1ac

**Additional server info**
BungeeCord, Server version 1.12.2

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by creeper123123321** [comment]
confirmed bug 1.16.5 server 1.8 client

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaRewind/issues/303
