### ISSUE TITLE
Incorrect block remapping for 1.8.9 clients

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaRewind#303]
- [ ] #302 End stone brick
- [ ] #295 Purpur slabs/stairs/etc
- [ ]  #299 Command block

**Comment by Diamax10** [comment]
Maybe it can be the same problem as https://github.com/ViaVersion/ViaBackwards/pull/351

**Comment by Diamax10** [comment]
I've fixed the problem but I don't know how. I will investigate that.

Plugins:
- ViaVersion & ViaBackwards 3.2.1
- ViaRewind 1.5.3
- ViaRewindLegacySupport 1.3.3

**Comment by Thin-Troll** [comment]
updated, the problem is not gone.

> I've fixed the problem but I don't know how. I will investigate that.
> 
> Plugins:
> 
> * ViaVersion & ViaBackwards 3.2.1
> * ViaRewind 1.5.3
> * ViaRewindLegacySupport 1.3.3

updated, the problem is not gone.
