### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaRewind#308]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/2937aa27c3f7477ea02524db63057315

**How can we reproduce it?**
1. use the last dev version of `viaversion`, `viarewind` and `viabackwards`.
2. run server
3. see the error when load the `viarewind`

**Expected behaviour**
can't load the `viarewind`

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/db2f1f863a47d97bb01ca13c72ba61d726347a5668c1830d787311537a22d215

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by creeper123123321** [comment]
Update viarewind-dev

**Comment by Dreeam-qwq** [comment]
> 
> 
> Update viarewind-dev, viaversion-dev and viabackwards-dev

these three plugin already the newest dev version, but the error still appear.

**Comment by creeper123123321** [comment]
> > Update viarewind-dev, viaversion-dev and viabackwards-dev
> 
> these three plugin already the newest dev version, but the error still appear.

The dump info says via version is outdated

**Comment by Dreeam-qwq** [comment]
https://dump.viaversion.com/328f1ae69e52b04a43f75a0da88a9345c2abbb16bf3d4ad384c897eeb64c1fdf
I create a new dump
the server is paper-1.12.2

**Comment by KennyTV** [comment]
Downloading the latest build will fix it: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/212/
