### ISSUE TITLE
1.8 clients disconnect when 1.9 bossbar is sent by server (PacketPlayInSpectate) 

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaRewind#311]
**Describe the bug, provide any errors**
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/30 (PacketPlayInSpectate) was larger than I expected, found 4 bytes extra whilst reading packet 30

viarewind 1.5.0/1.5.1 work good [+1.5.2 broken, first: (refCnt: 0) #232 and now this error: PacketPlayInSpectate in latest version with jenkins]

**How can we reproduce it?**
1. Start a 1.12.2 server
2. Install: viaversion, viarewind, viabackwards, Jobs worldedit, worldguard
3. you have to destroy the blocks downhill y:60 [y:30 flag block-break: false] with pickaxe and axe

**Expected behaviour**
Bossbar packets into clients 1.8

**Screenshots**
https://imgur.com/F2FdkO1 -> server log -> lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/30 (PacketPlayInSpectate) was larger than I expected, found 4 bytes extra whilst reading packet 30

**ViaVersion Dump:**
- https://dump.viaversion.com/4ca4485982de4476a056d909dcf43d214b9adf94bf53c881aea8dc2741d4c704

**Additional server info**
BungeeCord: false

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by KennyTV** [comment]
Update to -DEV builds found on https://ci.viaversion.com/, that'll fix the issue.
