### ISSUE TITLE
1.7.10 client crash on 1.16.5 server join

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaRewind#315]
**Describe the bug, provide any errors**
The game crashed instant when you join a 1.16.5 server with 1.7.10 using latest Via -dev builds

**How can we reproduce it?**
1. Login on with 1.7.10 on 1.16.5 server
2. The game crashed with `java.lang.IndexOutOfBoundsException`

**Crashreport**
https://paste.gg/p/anonymous/2e394fd8e4034be19145155e380f71b1

**Expected behaviour**
Join the server without a crash

**ViaVersion Dump:**
https://dump.viaversion.com/466c00fd2f9b4ccaa7aa3175e7724a1450d5f388b378d9191b10936de5bcdbbd

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by creeper123123321** [comment]
crash report?

**Comment by Jo0001** [comment]
https://paste.gg/p/anonymous/2e394fd8e4034be19145155e380f71b1
