### ISSUE TITLE
Viarewind / Via version kicks players from the server 

### ISSUE THREAD

**Issue by Monsiieur** [ViaVersion/ViaRewind#316]
Internal exception: io.netty.handler.codec.decoderexception: java.io.ioexception: packet 0/45 (PacketPlayInSpectate) was large than I expected, found 4 bytes extra whilst reading packet 45

This error kicks the players, it happends with the players on 1.8 version.
![image](https://user-images.githubusercontent.com/77248719/119030608-5b550280-b967-11eb-9d84-5130f04072bc.png)

**Comment by creeper123123321** [comment]
Can you try to reproduce using ViaFabric + addons?

**Comment by Monsiieur** [comment]
> Can you try to reproduce using ViaFabric + addons?

How can i use that?

**Comment by creeper123123321** [comment]
can you follow the issue template https://github.com/ViaVersion/ViaRewind/blob/master/.github/ISSUE_TEMPLATE/bug_report.md ?

**Comment by Redblock6YT** [comment]
Same issue, dump:
https://dump.viaversion.com/17d22cdc49bd8039b9dbaeb3ffd290d4477c8159b836c84e04d8352ec0786a83

**Comment by Redblock6YT** [comment]
Bump

**Comment by tomcraft** [comment]
Are you all using Lunar Client ?

**Comment by Monsiieur** [comment]
> Are you all using Lunar Client ?


I already tried using any 1.8 client and the same error

**Comment by tomcraft** [comment]
> > Are you all using Lunar Client ?
> 
> I already tried using any 1.8 client and the same error

Are you sure ? I ask this because yesterday [someone had the same issue on Discord](https://discord.com/channels/316206679014244363/316208160232701955/851153499920138282) and it was only with Lunar Client, not with Vanilla client.

**Comment by Camotoy** [comment]
If 1.8 vanilla players are fine, asking Lunar Client to fix their bug.

**Comment by Redblock6YT** [comment]
> If 1.8 vanilla players are fine, ask Lunar Client to fix their bug.

Someone on my server got kicked, and they were not using lunar, this is not a lunar client issue.
