### ISSUE TITLE
1.8.8 crash

### ISSUE THREAD

**Issue by ulllupollllo** [ViaVersion/ViaRewind#317]
https://dump.viaversion.com/351e0502d5ffd49f8a65feae21583564cff44cf01251328daac9b3e9b5d03685
the crash error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Codice di uscita: -1
people can enter the server but then minecraft crash

**Comment by creeper123123321** [comment]
Follow issue template
