### ISSUE TITLE
Unable to locate sign error

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaRewind#319]
**Describe the bug, provide any errors**
Running Via*-DEV builds on a Spigot 1.16.5 server, a 1.8.9 client shows "Unable to locate sign at..." errors and the signs are empty. The errors don't occur with 1.9.4, 1.12.2, or 1.16.5 clients.

**How can we reproduce it?**
Spigot 1.16.5 server + 1.8.9 client and some signs.

**Expected behaviour**
No errors and the signs should show their text.

**Screenshots**
![no_sign](https://user-images.githubusercontent.com/3617206/120381362-53df1300-c2f0-11eb-8e51-89627f559caa.png)

**ViaVersion Dump:**
https://dump.viaversion.com/0d337ec1f1afa59cf17e81d0c386a96329e8bb277bb60ab0e435b96d7c6ce96a

**Additional server info**
No Bungeecord. Server is running on Windows 10 with Java 8.
Via -DEV builds from Jenkins:
ViaBackwards-4.0.0-1.17-pre2-b318
ViaRewind-2.0.0-b225
ViaVersion-4.0.0-1.17-pre3-b547

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by KennyTV** [comment]
Update ViaVersion, I fixed that one today. :p
