### ISSUE TITLE
Purpur blocks aren't being converted

### ISSUE THREAD

**Issue by KolakZ** [ViaVersion/ViaRewind#321]
On 1.8, purpur blocks are glitched because there is no conversion for it yet. As a result, I can't move when stepping on it.

1. Create a 1.16 server
2. Place some purpur blocks
3. Log on 1.8
4. Step on the purpur block
5. You shouldn't be able to move

**ViaVersion Dump:**
https://dump.viaversion.com/77ff17c50368696c0073b35a2b20b0319bc380573717551a498fcb40e597d28d

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [ ] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by FormallyMyles** [comment]
Use latest builds as written in the checklist,

-- https://github.com/ViaVersion/ViaRewind/pull/309
