### ISSUE TITLE
after upgrading from version 1.5.3 to 2.0.0 block replacement became worse

### ISSUE THREAD

**Issue by lokha** [ViaVersion/ViaRewind#323]
original map (without via):  
![image](https://user-images.githubusercontent.com/32991511/121727686-e784c080-caf4-11eb-81cd-e30d0c2fd07f.png)

ViaRewind version 1.5.3 (bukkit 1.12.2, client 1.8):  
![image](https://user-images.githubusercontent.com/32991511/121727799-0edb8d80-caf5-11eb-94cb-c82ea594f06b.png)

ViaRewind version 2.0.0 (bukkit 1.12.2, client 1.8):  
![image](https://user-images.githubusercontent.com/32991511/121727929-3f232c00-caf5-11eb-90bd-c77f54671b56.png)

the [path](https://minecraft.fandom.com/wiki/Dirt_Path) is now replaced with air, which spoils the map

**Comment by KennyTV** [comment]
Update to ci builds.
