### ISSUE TITLE
Cooldown bossbar error

### ISSUE THREAD

**Issue by nmauer** [ViaVersion/ViaRewind#324]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/44631c92b5934390a1f4b60168e0a8dd/revisions
The error occurs when you start the server or switch the hotbar slot.

**How can we reproduce it?**
1. Login with 1.8 on an 1.16 server
2. Switch the hotbar slot

**Expected behaviour**
I did not expected an error

**ViaVersion Dump:**
https://dump.viaversion.com/f4e7d270f78a44682767a958661430c40c458b489f1125b28eb984804c350d0e

**Additional server info**
I am using an spigot 1.6.5 server with ViaVersion, ViaBackwards and ViaRewind

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Jo0001** [comment]
Works fine for me using the latest paper 1.16.5.
In the stacktrace is a bossbar mentioned so you have probably some invalid bossbar (from the LobbySystem plugin)

**Comment by nmauer** [comment]
I removed the lobbysystem but the error still arises.
https://dump.viaversion.com/06dcb2a27f07ae7157f9e8de8f622053859f0f04488db227176bc79f4798984b

**Comment by Jo0001** [comment]
Its working fine for me with just Via* installed. The only differences between your and my setup are the server software (I used paper) and the Java version (I use 16).
Can you try to use the latest Via* builds?

**Comment by nmauer** [comment]
I installed all 4 plugins you linked, and switches to paper spigot, but the error is still arsing.
https://dump.viaversion.com/b0ad263a0af7d0eb576e2944bc4af4111c251c8e2260e994b7855e7f4d24fb4e

**Comment by Jo0001** [comment]
Do you use a proxy?

**Comment by nmauer** [comment]
No. Just a single Spigot/Sponge Serevre

**Comment by nmauer** [comment]
Is there now a Patch for the bug?

**Comment by FlorianMichael** [comment]
Should be fixed in latest versions
