### ISSUE TITLE
1.8.9 players unable connect to 1.17 servers.

### ISSUE THREAD

**Issue by VanillaChan6571** [ViaVersion/ViaRewind#325]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
Error: https://paste.gg/p/anonymous/ff9681b68d0e4284bd948b2d7fa75cb2
Notices: "Index 10819 out of bounds for length 48" the first number always changes but the 48 always stays the same.

**_1.9.x and above can Login just fine._**

**How can we reproduce it?**
1. Login on 1.8.9'
2  You get kicked.

**Expected behavior**
Able to log in to lobby and not get dc.

**Screenshots**
You can't get a screenshot if it kicks in 1ms you aye?

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/1dddfa348ab14cacdb528d823eea0d3e849acb8b19239419c2ddb38de1253fcf

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

Waterfall#436 (Bungeecord/Proxy)
Plugins on Proxy:
Litebans-2.7.1.jar
TAB_Premium_v2.8.11-pre18.jar
Gyser+Floodgate 2.0
Party And Friends + Extensions

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Jo0001** [comment]
Works fine for me with the latest Via*
![works](https://user-images.githubusercontent.com/47455182/121819281-77a93e00-cc8c-11eb-81e7-c8d28308a2d0.PNG)

**Comment by VanillaChan6571** [comment]
> 
> 
> Works fine for me with the latest Via*
> ![works](https://user-images.githubusercontent.com/47455182/121819281-77a93e00-cc8c-11eb-81e7-c8d28308a2d0.PNG)

I tested 1.8.8 myself and it seems 1.8.9 is the issue.

**Comment by Jo0001** [comment]
> I tested 1.8.8 myself and it seems 1.8.9 is the issue.

1.8.9 also works fine for me. You have to try which of your plugins cause it
