### ISSUE TITLE
Dropped item are always stone

### ISSUE THREAD

**Issue by Ytnoos** [ViaVersion/ViaRewind#326]
**Describe the bug, provide any errors**
Dropped items become stone if on 1.7.

**How can we reproduce it?**
1. Host 1.8 server with ViaVersion and ViaRewind
2. Join with 1.7
3. Drop items on the ground

**Expected behaviour**
See dropped items with the right ID

**Screenshots**
![image](https://user-images.githubusercontent.com/21027982/122044008-463f8800-cddc-11eb-9970-b291393221ba.png)

**ViaVersion Dump:**
https://dump.viaversion.com/2caf38b275b12f93b6c7d141325bf68eeb288edd53d68a9895abcf9fd201ae1c

**Additional server info**
I use Velocity as a Proxy and a custom SportPaper fork as software. Most of the plugins are custom.
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by calcastor** [comment]
We are experiencing the same issue with a similar setup that also uses SportPaper. I have tested locally using both Paper and Spigot  1.8.8 and the issue remains.

**Comment by creeper123123321** [comment]
Confirmed

**Comment by fresszin** [comment]
Bump!

**Comment by linsaftw** [comment]
Same issue here.

**Comment by KeanoPlaysYT** [comment]
Im experiencing the same issue using a nachospigot fork.

**Comment by Ccode-lang** [comment]
Maybe it's fixed in 4.1

**Comment by brxve** [comment]
bump

**Comment by Godl1nk** [comment]
same issue

**Comment by WithoutRegret** [comment]
Still having this issue

**Comment by linsaftw** [comment]
Any news about this?
