### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by AirCraze** [ViaVersion/ViaRewind#331]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Have all viaversion plugins installed including this one ON PAPER 1.16.5
2. Login with 1.8
3. Error
4. (you should also see it on console)

**Expected behaviour**
No errors and should be working correctly
**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/c7fced55c517f260b7ce52760fe09bf79e1c6979c008e5d9e5b4cd2b2b1ed345
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
no
**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by KennyTV** [comment]
and what's the error?

**Comment by creeper123123321** [comment]
Error message???

**Comment by Ccode-lang** [comment]
It looks like you don't have viaversion installed.  It looks like you are using a third party plugin for compatibility.
