### ISSUE TITLE
beta 1.7 to release 1.6 support please

### ISSUE THREAD

**Issue by candrawardana** [ViaVersion/ViaRewind#333]

**Comment by krusic22** [comment]
The project you are looking for is down the block: [here](https://github.com/DirtPowered/DirtMultiversion)

**Comment by candrawardana** [comment]
i mean it's i want to backwards compatible not up version

**Comment by RaphiMC** [comment]
This probably is not in the scope of ViaRewind, maybe ProtocolSupport would be a better option if you want clients even older than 1.7 to join your server

**Comment by BuzzTheGamer23** [comment]
I haven’t tested it, but you can try Beta2Release. https://github.com/DirtPowered/Beta2Release
