### ISSUE TITLE
Console Error when opening GUI

### ISSUE THREAD

**Issue by LeStegii** [ViaVersion/ViaRewind#334]
**Describe the bug, provide any errors**
Whenever I open a teleporter GUI on my server (Spigot 1.12.2) when playing with 1.7.10, I get this error in console.
It works still fine and I can use the GUI, but the error is annoying. It seems like the error gets printed once for every item displayed.

**Error** 
https://hatebin.com/tfzwkyyive

**How can we reproduce it?**
1. Login on 1.7.10
2. Open a custom brewing stand GUI
3. See the error.

**Expected behaviour**
No error should be displayed

**Screenshots**
GUI
<img src="https://cdn.discordapp.com/attachments/316208160232701955/862270547081822238/unknown.png">

**ViaVersion Dump:**
Dump: https://dump.viaversion.com/f2bddb06d7322d03b5aacaf215d77e1e2040bceedf285cd053c2c45932b05b23

**Additional server info**
I'm using Travertine

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by FlorianMichael** [comment]
Looks like the error url doesn't work anymore, if the issue still appears, open a new ticket here on GitHub.
