### ISSUE TITLE
Dropped items look the same as stones on 1.7 client

### ISSUE THREAD

**Issue by ShivaTeam** [ViaVersion/ViaRewind#337]
**Describe the bug, provide any errors**
Dropped items look the same as stone. No exceptions.

**How can we reproduce it?**
1. Login on 1.7.10
2. Drop an item
3. Dropped item look the same as stone

**Expected behaviour**
Dropped items display correctly.

**Screenshots**
I think it's not necesarry.

**ViaVersion Dump:**
We've made a dump with useful information, report your issue ad provide this url: https://dump.viaversion.com/ea7a1001e5bdcfe9e6230ae5a93199007947e6f122bb5b633678b1a45b634fa

**Additional server info**
Hexacord. Spigot 1.8.8. the latest Protocollib.
**Checklist** (mark with [X] to check)
- [√] I have included a ViaVersion dump
- [√] If applicable, I have included a paste (not a screenshot) of the error
- [√] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [√] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by Gerrygames** [comment]
Duplicate
