### ISSUE TITLE
1.17?

### ISSUE THREAD

**Issue by srnyx** [ViaVersion/ViaRewind#345]
Does the plugin work on/support 1.17.1? If so, can you mark it as compatible with 1.17 on the Spigot page?

**Comment by Kichura** [comment]
Try it and see. ™️

**Comment by srnyx** [comment]
> Try it and see. ™️

Rather not have it break my server. Can't really "try it and see" when updating to 1.17 as tons of things can go wrong. Such as chunk corruption. Want to confirm with all the developers that don't have their plugins marked as 1.17-compatible before making any changes.
Thanks for the help though, I guess?

**Comment by Earthcomputer** [comment]
Why not use a backup

**Comment by srnyx** [comment]
> Why not use a backup

Takes forever for my server to backup. And I'm in the middle of switching hosts. So I wanted to see if I could simply get an answer instead of going through that whole process.

**Comment by Kichura** [comment]
> 
> 
> > Why not use a backup
> 
> It takes forever for my server to backup and I'm in the middle of switching hosts. So I wanted to see if I could simply get a yes/no answer instead of going through that whole process.

Most plugins from 1.17.0 should be compatible with 1.17.1 (in a proper answer's sense). - Besides, ViaRewind can run all the way back to 1.9.0 aswell if the server wasn't entirely cursed in this case.

**Comment by srnyx** [comment]
> Most plugins from 1.17.0 should be compatible with 1.17.1 which means yes, you can run viarewind just fine.

It doesn't say it's compatible with any 1.17 version on the Spigot, only up to 1.16.x.

**Comment by srnyx** [comment]
Ah, I see one of the updates had "1.17" in the update title not description.
