### ISSUE TITLE
1.8.9 crashing on 1.16.5 viarewind

### ISSUE THREAD

**Issue by h00z3x** [ViaVersion/ViaRewind#347]
when i join with 1.8.9 on the server it crashes tough i have the viarewind and ... installed and some other plugins
i looked at the log of the server after the messge of h00z3x joined the game and before the h00z3x left the game there was no error i think its about the entities or gui
i also looked at the minecraft log on crash and the log was : https://paste.md-5.net/onixobikar.cs
pls a fix for it
(i also tryed the viarewind legacy version&the server is connected to bungeecord)
(server is running on spigot)

**Comment by Kichura** [comment]
Please provide a dump of your viaversion by running **/viaversion dump** either in-game or in console then copy&paste the dump link to this issue as you only gave an error report.

**Comment by Jo0001** [comment]
As I said already in Discord this is probably because of some other plugins and not because of Via (as it works fine on a clean testsetup)
