### ISSUE TITLE
Ladder and lily pad fix not working

### ISSUE THREAD

**Issue by Sckaletz** [ViaVersion/ViaRewind#348]
On Paperspigot 1.16.5 running on Java 16 with the latest version of your plugin and the latest version of Viaversion, Viabackwards and Viarewind, you can't climb ladders in 1.8-1.8.9. Also the lily pads are bugged.

![Udklip](https://user-images.githubusercontent.com/6684408/132468572-e99cacf3-d6f9-4ba9-88e7-3efc287c57a9.PNG)

**ViaVersion Dump:**
https://dump.viaversion.com/e2ca23c0cd051c2758a73659162a66c809244f4c53cd9baf7d717404e63f88ab

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- x[] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git-Paper-788 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--788%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Seanoo1** [comment]
Your VRLS is outdated. You need to download https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.1.jar
This version.

**Comment by Sckaletz** [comment]
Amazing. Thank you ;-)
