### ISSUE TITLE
Sound Issue ViaRewind

### ISSUE THREAD

**Issue by HarshVardhanSingh-op** [ViaVersion/ViaRewind#349]
Hello There , **_I Have a 1.16.5 with ViaVersion , ViaBackward and ViaRewind + ViaRewind Legacy Support But Still 1.8 Players Cannot Listen BlockPlace , ItemPickup Sounds Please help me_**

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by HarshVardhanSingh-op** [comment]
@Barvalg 
![image](https://user-images.githubusercontent.com/82308380/132711031-e91461f9-1cbe-497c-afd6-886a3e29ce3c.png)

**Comment by Jo0001** [comment]
Works fine for me. Either join our Discord discord.gg/viaversion (#support) or open a new Issue (and make sure to fill out the complete template)
