### ISSUE TITLE
1.7.x-1.8.x untranslated texts

### ISSUE THREAD

**Issue by WolfyRed** [ViaVersion/ViaRewind#352]
**Describe the bug**
All 1.7.x-1.8.x versions that join see Withers, Villagers, etc as "entity.name" instead of "Wither", "Villager", etc.

**How can we reproduce it?**
1. Login on 1.7.x-1.8.x
2. Spawn a Wither
3. The name of the Wither is displayed as follows: "entity.WitherBoss.name"

**Expected behaviour**
The Wither to have the name "Wither", as it is in 1.7 and 1.8.

**Screenshots**
![image](https://user-images.githubusercontent.com/66114400/134259101-74ef36ee-abe6-41e7-83bc-449c9f46717e.png)
![image](https://user-images.githubusercontent.com/66114400/134259109-4f4fe139-ab58-40eb-8914-a6bf03a76404.png)
![image](https://user-images.githubusercontent.com/66114400/134259120-ad68fffe-82ed-4158-b51e-fa16b0fcfcc6.png)

**ViaVersion Dump:**
https://dump.viaversion.com/40a895d26157657f20948bdb868a1cc3c349ad3cc0073c9cdd43cd25bb77626f

**Additional server info**
Paper 1.13 Server, plugins used: `CommandHook, Essentials, GMC, LuckPerms, Multiverse-Core, OldCombatMechanics, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, ViaVersionStatus, Wild`

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git-Paper-655 (MC: 1.13.2)](https://img.shields.io/badge/Platform-git--Paper--655%20%28MC%3A%201.13.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by creeper123123321** [comment]
Seems related to ViaBackwards

**Comment by creeper123123321** [comment]
caused by viabackwards

**Comment by WolfyRed** [comment]
@creeper123123321 Did you sort the issue yet? It seems you closed the issue.

**Comment by Elikill58** [comment]
The same already appear with 1.8 client on 1.16 server. I made /gamemode or /tp and I made untranslated messages

**Comment by WolfyRed** [comment]
This issue is not yet fixed

**Comment by FlorianMichael** [comment]
Is this issue still present in latest Via* plugins? Also does it also happen for 1.9+ clients?

**Comment by FlorianMichael** [comment]
Closing as stale and not reproducible, in case there are any new updates on this, make a new issue.
