### ISSUE TITLE
When using Themis Anti Cheat plugin, 1.7.10 client instant kicked from server on 1.17.1 paper server.

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaRewind#353]
**Describe the bug, provide any errors**
[20:44:58 WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF WINDOW_CONFIRMATION (0x07)
[20:45:01 INFO]: Seanoo lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
[20:45:01 INFO]: Seanoo left the game

The error was not happened on previous dev build.

**How can we reproduce it?**
1. Login from 1.7.10
2. Crash

**Expected behaviour**
player should join normally

**Screenshots**
kicked message is same as up console message.

**ViaVersion Dump:**
https://dump.viaversion.com/c983ba00d7707b84a9d26c80d92942009738311135f3ec2217740bb92596b23a

**Additional server info**
I don't use proxy.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git-Paper-278 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--278%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.1.0-21w38a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--21w38a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.1.0-21w38a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--21w38a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)

**Comment by Seanoo1** [comment]
even with master? I downloaded dev build.

**Comment by Jo0001** [comment]
Works fine for me with just Via* installed

**Comment by Seanoo1** [comment]
Are you using dev build too? I downgrad it to previous version and it works perfectly.

**Comment by Jo0001** [comment]
Yep, I use the latest dev build https://dump.viaversion.com/6f25294d03b14ec205696658ad50190214e1b6f0439dd29c4e52472f352bc475

**Comment by Barvalg** [comment]
![Platform: git-Paper-278 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--278%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.1.0-21w38a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--21w38a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.1.0-21w38a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.1.0--21w38a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)

**Comment by Seanoo1** [comment]
I don't know why it is working now. I copied paper.jar and opened clear server and it works perfectly now.

**Comment by Seanoo1** [comment]
Ok, I found Themis plugin has problem with latest dev version of viarewind. I want to confirm this is viarewind issue or themis issue.
