### ISSUE TITLE
Cannot convert component to legacy text with npc plugin

### ISSUE THREAD

**Issue by Brqdford** [ViaVersion/ViaRewind#359]
Server version sponge vanilla 1.12.2 7.3-7127e0882
viaversion version 4.0.1 viarewind 2.0.1

I have npcs plugin for spongevanilla and it wont let 1.7.10, 1.8.9,  players right click to use command actions on the npc, and it also shows error on console. Npcs work fine for other versions https://mclo.gs/vschvlm

1. Login on 1.7.10 or 1.8.9 - 1.9on a 1.12.2 spongevanilla server'
2. Have a npc created with the npcs mod
3. Errors will occur in console, and you wont be able to right click on the npc and have it perform its command actions.

Cant do a viaversion dump shows this error https://mclo.gs/l8B4F8q

**Comment by Jo0001** [comment]
ViaVersion/Backwards 4.0.1 and ViaRewind 2.0.1 are outdated.
Please try it with the latest Via* plugins from Spigot (#links on Discord)

**Comment by FlorianMichael** [comment]
Try latest Via* plugins, if the issue still appears, make a new GH issue.
