### ISSUE TITLE
Any block when dropped is a stone block.

### ISSUE THREAD

**Issue by franciscofl12** [ViaVersion/ViaRewind#363]
**Describe the bug, provide any errors**
It doesn't appear any error, the error is that when you drop a block in 1.7.x or 1.8.x the image is a stone block, if you pick it, its the same block/item that you dropped, but the image is not the item/block that you dropped. No error in console.

**How can we reproduce it?**
Steps to reproduce the behaviour:
1. Create a server with a 1.8.8 spigot.
2. Join with 1.7.x or 1.8.x to the server and get a block
3. Drop the block and a stone block will appear.

**Expected behaviour**
It should drop the block that it is.

**Screenshots**
[Dropped a sword and wool.](https://i.imgur.com/94KtIAW.png)

**ViaVersion Dump:**
- https://dump.viaversion.com/2f1813263db8fb63cac57d30a5a6297347a0e5ea85f02fa0953e9248d084d614

**Additional server info**
I think that I don't use anything that can disturb with the plugin.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--v1.0--19--g2ad6179%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--v1.0--19--g2ad6179%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by franciscofl12** [comment]
Fixed in the snapshot of 4.0.2
