### ISSUE TITLE
I keep getting kicked with ViaVersion 4.1.0 and 4.1.1

### ISSUE THREAD

**Issue by LouieMartin** [ViaVersion/ViaRewind#365]
This is possibly caused by not adding an if statement to a nullable object, please fix this I and my friend can't play on my SMP, sorry for little to no context but I really don't know what to do. And it is not generating an error in the console, so there's not much context.
![image](https://user-images.githubusercontent.com/73145637/144701723-79399c9f-cb51-43a0-9194-9aa102afa076.png)

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by LouieMartin** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

I don't know what that is.

**Comment by LouieMartin** [comment]
It works when I use it locally but I'm using Aternos which may also be the problem.

**Comment by FurmigaHumana** [comment]
they havent added support for 4.1.X yet.

**Comment by HowardZHY** [comment]
close as outdated. they could had a corrupt jar.

**Comment by Kichura** [comment]
Please update your via* and see if your issues persist - otherwise please make a new comment.
