### ISSUE TITLE
1.7 too many player boxes

### ISSUE THREAD

**Issue by HEROOSTECH** [ViaVersion/ViaRewind#372]
When I turn on the tablist on 1.7, I get too many boxes. In the first half of this year there was a version where everything worked normally 20 players = 20 boxes. Screen: https://cdn.discordapp.com/attachments/760014483766116372/923261250950017134/unknown.png

1. Login on 1.7.10
2. Press Tab
3. The Tab is displayed wrong

Expected behaviour:
Normal working tablist on 1.7 ;)

https://dump.viaversion.com/c9af634169da34d65b42a1f945432294f3bcb0cdcd76ab1049aaa666edcc5465

Additional server info:
On velocity occurs same problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by HEROOSTECH** [comment]
On 1.12.2 tablist works normally. It's problem with ViaBackwards maxplayers (I think).
