### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockPosition

### ISSUE THREAD

**Issue by PineAppleGrits** [ViaVersion/ViaRewind#373]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?
For an unknown reason it outputs this error/warn many times.
https://paste.gg/p/anonymous/386e7cc574e24c4290cd918ac2489155
**How can we reproduce it?**
Unknown

**Expected behaviour**
Not have the error/warn?

**Screenshot**
https://mclo.gs/zCElQcy

**ViaVersion Dump:**
https://dump.viaversion.com/167e9e2d144787d9b0d2a47b55f2aae8a61a79c369e10e52ae4af55a811eb14d
**Additional server info**
It's proxied by BungeeCord but runs on paper. In the dump you can see additional information

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--Paper--402%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--402%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Jo0001** [comment]
Please try it with the latest ViaRewind-Legacy-Support version: https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.1.jar
