### ISSUE TITLE
1.8 player can't do something on 1.16 servers

### ISSUE THREAD

**Issue by Elikill58** [ViaVersion/ViaRewind#376]
**Describe the bug, provide any errors**
No console error.

After login, 1.8 can run commands, talk etc but can't move or place block

**How can we reproduce it?**
1. Login with 1.8.9 client
2. Move
3. See you be teleporter back

**Expected behaviour**
Can play.

**ViaVersion Dump:**
[ViaVersion dump](https://dump.viaversion.com/79154d6eb102efc03ca7d0dacbb0a8264fe83baa78e990ee77945d8b808e1724)

**Additional server info**
The plugin "EliTest" only include one event that send message, nothing else.

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Elikill58** [comment]
Oups. I didn't tried with dev build of ViaVersion/ViaBackwards.

That's the same. My Via dump: https://dump.viaversion.com/c6487f72b92b3bc6decc64cafe8d2d41b0689f6c3869aa2995f1c3c3c8d0da61

**Comment by Barvalg** [comment]
![Platform: git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.2.0--22w03a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.2.0--22w03a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Can't reproduce on a 1.16.1 or 1.21 Server, try if the issue still appears with latest Via* components and without any other plugins installed.
