### ISSUE TITLE
Velocity Plugin fails with ViaVersion 4.2.1 + Velocity 3.1.1

### ISSUE THREAD

**Issue by CamperSamu** [ViaVersion/ViaRewind#382]
**Describe the bug, provide any errors**
The plugin fails to initialize on Velocity 3.1.1 with ViaVersion 4.2.1 (and ViaBackwards 4.2.0)
https://paste.gg/p/anonymous/6969e0fddd654cb2a63a6284f3a2e778

**How can we reproduce it?**
1. Start a Velocity 3.1.1 server with ViaVersion 4.2.1 and ViaRewind 2.0.2 or 2.0.3-SNAPSHOT
2. The plugin fails to load.

**Expected behaviour**
The plugin should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/32773961/156568794-180a2d7c-b922-4a1a-a9d5-7edba69d1243.png)

**ViaVersion Dump:**
- https://dump.viaversion.com/35697fefa78240a891beebca61ccbf6f41bcb58e4020095b5cf02542722037ad

**Additional server info**
The plugin is running on Velocity 3.1.1

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by CamperSamu** [comment]
Just updated to Velocity 3.1.2#117, the issue still persists if you are wondering (obviously since it's a logger init error)

**Comment by Kichura** [comment]
Late but managed to reproduce this on my own linux distro instance here using latest velocity + newest via* copies available from CI build list.
