### ISSUE TITLE
Player#setPlayerListName not working in 1.7 clients

### ISSUE THREAD

**Issue by wuangg** [ViaVersion/ViaRewind#384]
**Describe the bug, provide any errors**
`Player#setPlayerListName` not working in 1.7 clients 

**How can we reproduce it?**
1. Login on 1.7.10 client
2. Use `Player#setPlayerListName` to update a player's display name in tab list

**Expected behaviour**
The tab list should display updated name like in 1.8 clients

**Screenshots**
In 1.7 client:
![1](https://user-images.githubusercontent.com/33364204/156968036-f749596c-cae9-4b30-8eb5-c56a714d76f5.png)
In 1.8 client:
![2](https://user-images.githubusercontent.com/33364204/156968056-43247d88-0ce7-47bd-9d6d-a737864a99b6.png)

**ViaVersion Dump:**
https://dump.viaversion.com/d573b44266eb677af4d0df57cbd1956ebe5037f272c1d3e44cb7e6afa541ffc9

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--Azure--200790f%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Azure--200790f%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
