### ISSUE TITLE
15w14a April fools snapshot support

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaRewind#386]
![image](https://user-images.githubusercontent.com/96782166/159135031-83166f12-571f-475d-8baf-2c645e551bb1.png)

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
No
