### ISSUE TITLE
1.7.10 client can't join server with TAB

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaRewind#389]
**Describe the bug, provide any errors**
1.7.10 client will get kick when join server with viave and [TAB](https://github.com/NEZNAMY/TAB)
https://paste.gg/p/anonymous/05f654beb9a84557ba7abf7fe3083406

**How can we reproduce it?**
1. Login on 1.7.10
2. join 1.18.2 server with Tab and viaver
3. get kick and see error on console

**Expected behaviour**
Player can use 1.7.10 client to join server without tick.

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/5fdff182dc825ce7221ce3bd55feb69c63fa15777507458d65c15dbb5fe90422

**Additional server info**
Proxy: velocity-3.1.2-SNAPSHOT-135
Backend Server: paper-1.18.2-290(1.18.1 too)
Backend Server Plugins: 
[TAB](https://github.com/NEZNAMY/TAB), ViaBackwards, ViaRewind, ViaVersion, ViaRewind-Legacy-Support

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--Paper--290%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--290%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaRewind/issues/388 relate?

**Comment by Dreeam-qwq** [comment]
> #388 relate?

seems like same issue

**Comment by Kichura** [comment]
Closing this as this has been fixed in newest viarewind build.
