### ISSUE TITLE
wrong type in UPDATE_SCORE

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaRewind#390]
**Describe the bug, provide any errors**
```
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: UPDATE_SCORE, Type: Byte, Data: [Pair{Type|String,    }], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.ScoreboardPackets$2 (Anonymous), Packet ID: 60}
Actual Error: 
Caused by: java.io.IOException: Unable to read type Byte, found VarInt
```

**How can we reproduce it?**
Use ViaBackwards to connect to a 1.18.2 server

**Expected behaviour**
Don't kick

**Screenshots**
no one

**ViaVersion Dump:**
- https://dump.viaversion.com/ffc0f92227d6a6b861fc46ffb20afb22705f0243deb12d921827853216085601

**Additional server info**
VIAaaS

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: 0.4.16+v0.4.16--37--ga2229d2.dirty](https://img.shields.io/badge/Platform-0.4.16+v0.4.16--37--ga2229d2.dirty-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w16b-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w16b--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.3.0-22w16b-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w16b--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>
