### ISSUE TITLE
visual bugs

### ISSUE THREAD

**Issue by eliazanetti** [ViaVersion/ViaRewind#391]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Login on 1.8'
3. Seeing chest, squid flying, and spam OpenGL error 1283 client 1.8, and moving border offset

**Screenshots**
(https://i.badlion.net/8HKueMDpQH9Rk5pW8gpaE9.png)

**ViaVersion Dump:**
[- Type /viaversion dump, and put the link here.](https://dump.viaversion.com/8664f6f08c5b31b3b9882d6758a3aa14247639101234e694a2c7f8e0b41be674)

**Additional server info**
Bungeecord

**Comment by Kichura** [comment]
The opengl bug is not caused by via*, this is related to compromised drivers instead / client itself. As for the flying squid; this is likely a bee or another translated mob - can be noticed by their assigned name tags.
