### ISSUE TITLE
Tablist Issue 1.7

### ISSUE THREAD

**Issue by iSkyad** [ViaVersion/ViaRewind#394]
**Describe the bug, provide any errors**
When opening the tablist in 1.7 the tablist appears broken and has far too many player boxes causing the format of it to break

**How can we reproduce it?**
1. Login on 1.7.10
2. Open Tab
3. See the tablist being broken

**Expected behaviour**
The expected result without any tablist plugins would be 
![2022-05-24_18 05 11](https://user-images.githubusercontent.com/105819349/170092640-4f7a7c3b-c6a9-4c38-b61b-93dc1f155f37.png)

**Screenshots**
This is how it currently shows up without any tablist plugins; when multiple people are connected it overlaps and when a tablist plugin is used all text becomes overlapped
![2022-05-24_18 04 02](https://user-images.githubusercontent.com/105819349/170092797-8ea6c266-2a20-4c0e-8f3b-4e9cb053bcc1.png)

**ViaVersion Dump:**
https://dump.viaversion.com/c0108b1ac41112a4a37dddf33a93c5a15674f055650147d0508f64313313385a

**Additional server info**
I am running a BungeeCord server. I have attempted a variety of plugin versions and I have also attempted to run a server without bungee but to no avail. I have tried multiple server versions too but it appears to make no difference. ProtocolSupport doesn't have this issue, however their plugin doesn't fit the server version I require.

**Checklist** (mark with [X] to check)
- [X] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by overkidding** [comment]
Thats your bungeecord configuration you should set tab_size to 60 in your bungeecord config.yml
