### ISSUE TITLE
MCPE 1.18 unable to joine 1.19 server

### ISSUE THREAD

**Issue by prabhu8680** [ViaVersion/ViaRewind#395]
i recently updated my server version to 1.19. But now MCPE 1.18 version players unable to join my server. i have added Viaversion / ViaBackwards and Viarewind plugins in my server. But still 1.18 version players couldnt be able to join in my server.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
This issue should go to geyser's issues list but will answer it anyways;

Geyser no longer supports 1.18.x bedrock and instead must be updated to join - If your server is still older than 1.19 then you can use viaversion to allow geyser to properly emulate 1.19 java clients.
