### ISSUE TITLE
Inventory problem

### ISSUE THREAD

**Issue by Anto2602** [ViaVersion/ViaRewind#396]
I've a bug, when i drop an item on the floor, i still see it in my inventory (But it's on a visual bug, if i click on it then the item will dissapear) anyone know how to fix this issue?

**ViaVersion Dump:**
https://dump.viaversion.com/ca800436224b4302120a3f9e795b737ea4b4d7174522ec079c5495fb87f4633c

**Additional server info**
FlameCord

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Anto2602** [comment]
https://dump.viaversion.com/ca800436224b4302120a3f9e795b737ea4b4d7174522ec079c5495fb87f4633c

**Comment by Barvalg** [comment]
![Platform: 1.0.1](https://img.shields.io/badge/Platform-1.0.1-3498db?style=flat-square) </br>![Flamecord is not supported](https://img.shields.io/badge/Unsupported%20Platform%20-%20Please%20use%20Waterfall/Bungee%20instead%20or%20put%20all%20Via*%20plugins%20to%20the%20backend%20servers-orange?style=flat-square) </br>![ViaVersion (4.3.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Anto2602** [comment]
Still persist with latest build.

**Comment by HowardZHY** [comment]
VV had bugs with FlameCord, I remember
