### ISSUE TITLE
Blocking the version on the sub-server (VELOCITY / BUNGEECORD)

### ISSUE THREAD

**Issue by vCren** [ViaVersion/ViaRewind#398]
**Describe the issue you are facing or why you need the feature to be added**
I have viaversion, viarewind, viabackwards on proxy (Velocity) everything works fine, I can go to any subserver on any version. But I plan to do a skyblock on 1.14+, for example, and propose to add in the viaversion config on velocity the ability to write protocols to each subserver.

**Additional Info (optional)** 
In config, just create another list where you can specify the name of the subserver and after ":" print the list of protocols.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
