### ISSUE TITLE
sound mapping problem 

### ISSUE THREAD

**Issue by Shedalatjoo** [ViaVersion/ViaRewind#403]
players can't hear placing blocks sound my server is 1.12 and players use 1.8.9 also all minecraft sounds are bugged and players hear lighting sound instead of all sounds.
https://dump.viaversion.com/78716f7e1b52769cd7a069381fa54cf900782911649ca47db2b3185e6901ecb6

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
Next time please follow the template.
To fix your issue please also install ViaRewindLegacy-Support.
