### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF OPEN_WINDOW (0x2D)

### ISSUE THREAD

**Issue by m3xicang0d** [ViaVersion/ViaRewind#404]
When a user of 1.7.10 right-clicks, an error appears in the console and does not open any menu, it should be noted that in 1.8 this error does not happen

**ViaVersion Dump:**
https://dump.viaversion.com/19092b32c53195af21c414b6a475d064b3b49479e8e0cd1969423ed18e18c7a5

**Additional server info**
FlameCord

Checklist (mark with [X] to check)

- [X ]  I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ]  I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [ ]  I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

 
**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.2--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.2--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FlorianMichael** [comment]
I can't reproduce the issue, you can try to update all Via* plugins to the latest version, if the error still occurs please create a new issue which also follows the issue template.
