### ISSUE TITLE
1.7.10 crashing when approaching an Amethyst Geode on a 1.19.1 server

### ISSUE THREAD

**Issue by ShonP40** [ViaVersion/ViaRewind#405]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

Vanilla 1.7.10 crashlog: https://paste.gg/p/anonymous/dd077a0819404fc7939b07a2ab5e6920

**How can we reproduce it?**
1. Login on `1.7.10`
2. Approach an `Amethyst Geode` (just needs to be in a loaded chunk)
3. The game will crash (I was able to reproduce this on vanilla & on multiple clients)

**Expected behaviour**

Expected it to load it in just fine, like it does on 1.8.9

**Screenshots**

(Taken on 1.8.9)
![2022-07-30_22 26 17](https://user-images.githubusercontent.com/13995143/181957096-d80f3f93-b2f7-4033-8150-1bd89c52be00.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/e02dbe95eb2cdd5271f59bbc81069b6f04827b62feb572a1f7afd554c0a3dd26

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

I use Travertine but I was able to reproduce this without any proxies

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: git--Paper--88%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--88%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by HowardZHY** [comment]
Does it still happen?

**Comment by ShonP40** [comment]
Haven’t tested it in a long while and not near my PC atm.

I’ll make sure I’m on the latest Via* plugins and test it again later this week

**Comment by FlorianMichael** [comment]
Any updates on this?

**Comment by ShonP40** [comment]
Been busy with some other stuff lately and forgot about this

Will test soon

**Comment by ShonP40** [comment]
Sorry for taking so long to respond but it seems to be fixed

so, closing this
thanks for fixing it!
