### ISSUE TITLE
Holograms falling in void on 1.7 Client since 2.0.3-snapshot

### ISSUE THREAD

**Issue by c0dingnoobi** [ViaVersion/ViaRewind#413]
**Describe the bug, provide any errors**
Just had to upgrade to latest dev build since it does have TAB/Scoreboard issues fixed. Holograms doesnt seem to work for 1.7 Clients on 1.8 Servers. The Hologram itself falls into void and an entity is being spawned instead. Currently using DecentHolograms but also happens on HolographicDisplays.

**How can we reproduce it?**
1. Login on 1.7.10 on 1.8 server'
2. Have Holograms created using DecentHolograms
3. See how they fall in void regardless where you have placed them

**Expected behaviour**
The holograms should be displayed as how they do on 1.8+ without falling into void.

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/6cf057bb61e90d6021c94bc019759acb7ec37b01401733f9225040a09ee6e032

**Additional server info**
Running latest Bungeecord without any plugins.

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be closed**

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
