### ISSUE TITLE
Ghost Item in 1.8 on server >= 1.17

### ISSUE THREAD

**Issue by ohAleee** [ViaVersion/ViaRewind#414]
**Describe the bug, provide any errors**
By clicking on an item in a gui, the item is duplicated

**How can we reproduce it?**
1. Login on 1.8.9
2. Open a GUI
3. Click on an item (one or more times)

**Expected behaviour**
The item must not be doubled carried around

**Screenshots**
![image](https://user-images.githubusercontent.com/36593455/193291168-9d57b11b-ac21-4632-8042-b24f06ac10c4.png)

**ViaVersion Dump:**
It is not necessary. You have known the bug for several years, it is time to try to fix it

**Additional server info**
Velocity

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
This issue has nothing to do with ViaRewind but with ViaBackwards.
