### ISSUE TITLE
ViaVersion 4.5.1 bug 1.7 client

### ISSUE THREAD

**Issue by franxyk** [ViaVersion/ViaRewind#419]
### `/viaversion dump` Output

https://dump.viaversion.com/36f993493ad2d67f6f5a3ec471a0298de9e1c5b9414d9a3fd6f7c63dd481988b

### Console Error

[ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF PLAYER_INFO (0x38)
[23:29:12] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:29:12] [Netty Server IO #1/WARN]: Packet Type: PLAYER_INFO, Type: Boolean, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10 (Anonymous), Packet ID: 56

### Bug Description

On use ViaVersion 4.5.1 an ViaRewind, 1.7 clients , kick error console.

### Steps to Reproduce

Example
1- Start spigot 1.19
2- Client 1.7 connect to server

### Expected Behavior

Use client 1.7 satisfactory.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--792%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--792%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by HowardZHY** [comment]
try latest VR from Jenkins.

**Comment by Daisreich** [comment]
tested on 1.19.3, same issue

**Comment by Daisreich** [comment]
dump: https://dump.viaversion.com/46bf3a8ac164d6ffe09a9344293a23780800b21241a7460908eb2f10e1f6d377

**Comment by Barvalg** [comment]
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by EPICSAURUSS** [comment]
Same error. I even disabled all of my plugins (except for via) and it still crashes
dump: https://dump.viaversion.com/804e9c2bc6cc82ef4ee2b467034fa4fd7df0f73e09d97c84a3a0f89e04e9f063
error: https://paste.gg/p/anonymous/a2d72ba17ffd4dbbbaf0b542665c4ddf

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
