### ISSUE TITLE
1.7.10 Players kicked

### ISSUE THREAD

**Issue by RouvbX** [ViaVersion/ViaRewind#420]
### `/viaversion dump` Output

https://dump.viaversion.com/22cd394d2d4cd65691c8b882edaf0b5646240023fef4c208fee3403785960d57

### Console Error

```
https://pastebin.com/TA31MDN5
```

### Bug Description

1.7.10 Players get kicked from the server.

### Steps to Reproduce

1. login with 1.7.10
2. player gets kicked from the server

### Expected Behavior

player should not get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--790%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--790%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by creeper123123321** [comment]
expired pastebin
