### ISSUE TITLE
1.7.10 issue

### ISSUE THREAD

**Issue by EndermanPvP** [ViaVersion/ViaRewind#421]
### `/viaversion dump` Output

https://dump.viaversion.com/e6cb6ab760f0d369d5535839141316d4f6b7abd7d574de2b069ef04ac3a85191

### Console Error

`No console logs`

### Bug Description

Using a splash instant health potion doesn't work *(it does not give health back)*

### Steps to Reproduce

1. Login to a 1.8.8 papermc server
2. Go in survival mode
3. Make sure you are at a point where you can get health again
4. Splash an instant health potion

### Expected Behavior

Doesn't heal you

### Additional Server Info

I am also using Flamecord with plugins AdvancedBan, AuthMeBungee, Bmsg, BungeeGuard, BungeeHub, BungeeWhiteList, BuycraftX, KauriVPN, LuckPerms, movemenow, Pl-Hide-Pro, protocolize-bungeecord, protocolize-legacy-bungeecord, SkinsRestorer, TAB

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by EndermanPvP** [comment]
Floodgate and GeyserMC are also added at this moment, this issue did not have Geyser when submitted

**Comment by Camotoy** [comment]
Neither of those plugins should affect your issue.

**Comment by EndermanPvP** [comment]
yes, how do i fix it

**Comment by EndermanPvP** [comment]
Yeah this isn't a ViaRewind issue, sorry
