### ISSUE TITLE
There is no release, i need it to isntall it on ubuntu with wget.

### ISSUE THREAD

**Issue by Kerbal-Man** [ViaVersion/ViaRewind#427]
### `/viaversion dump` Output

https://example.com

### Console Error

```
false
```

### Bug Description

There is no release, i need it to install it on Ubuntu with wget.

### Steps to Reproduce

open the github

### Expected Behavior

a

### Additional Server Info

a

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
You can use the CI website to get the latest via* copies instead as spigotmc would change links dynamically on next release(s).
