### ISSUE TITLE
ViaVersion cause lags

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaRewind#428]
### `/viaversion dump` Output

https://dump.viaversion.com/01f041c546a9e3a645e7b92a5a27629cc4b2936cbd7bba0f584d580a84b69961

### Console Error

.

### Bug Description

tested with no dev version, same problem
i have lags with viaversion
timings https://timings.aikar.co/dev/?id=183bedcdbe7a4083a5ec1a0cea2c1446

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
please try normal paper instead of weird forks

**Comment by F3F5** [comment]
> please try normal paper instead of weird forks

+ i tested with normal, fork, + other fork, same. i changed 3 core to best free and i see timings same

**Comment by HowardZHY** [comment]
I think PebbleAntiVPN and other Anticheat/Antibot plugins are causing lags. That's not a Via problem.

**Comment by F3F5** [comment]
> I think PebbleAntiVPN and other Anticheat/Antibot plugins are causing lags. That's not a Via problem.

you can see what cause lags, viaversion too, pebbleantivpn yes, i changed

**Comment by FormallyMyles** [comment]
Not a ViaVersion issue

**Comment by F3F5** [comment]
> Not a ViaVersion issue

1 question, why?

**Comment by F3F5** [comment]
> Not a ViaVersion issue

oops, viarewind xd, sorry
