### ISSUE TITLE
Error with block sounds on 1.12.2 server

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaRewind#440]
### `/viaversion dump` Output

https://dump.viaversion.com/986ab644ecdc0959cbb8b386edecb7a8337ab5d5c574fd868f3ab754b63b4023

### Console Error

```
[Put the paste.gg link or text here.](https://pastebin.com/J0xWPdyu)
```

### Bug Description

With 1.8.8 client when placing blocks, it does not make any sound and it gives the error posted above

### Steps to Reproduce

Create a 1.12.2 server (with server.pro for example)

Join with 1.8.8

Place a block

### Expected Behavior

The block place sound and not giving me an error in the console every time i put a block

### Additional Server Info

![imagen](https://github.com/ViaVersion/ViaRewind/assets/49927979/2f380d5b-b8ac-4028-a363-79c3e9c8f680)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by pabloalba16** [comment]
fixed in latest version
