### ISSUE TITLE
Trident does not work.

### ISSUE THREAD

**Issue by TheR0b0tMan** [ViaVersion/ViaRewind#441]
### `/viaversion dump` Output

https://dump.viaversion.com/2d4d44f6b1a9e2b02b241081abeeb33d18db1a1f944e89c8c1f3a74fdefe8c25

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I can not use a riptide trident. I try using it yet it does not do anything. There is no error in console.

### Steps to Reproduce

1. Login in using 1.8.
2. Try using a riptide trident.

### Expected Behavior

It should launch.

### Additional Server Info

I use bungeecord. The backend server is 1.16.1.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.6.2)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.3): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by TheR0b0tMan** [comment]
Does not work. https://dump.viaversion.com/7f729f1de6f7fe1236a806f64e7fa08ddedb9b9b1d1c5b24149265536d345b54

**Comment by Barvalg** [comment]
![Platform: git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by TheR0b0tMan** [comment]
https://dump.viaversion.com/637c8c59ff8bb18cf4215d42b858b43b9fbc574f58dcbe60e715112582a8be24

**Comment by Barvalg** [comment]
![Platform: git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by TheR0b0tMan** [comment]
https://dump.viaversion.com/f342d04824a1389800ec4971b9ff8b9ab15e10db84c10afba2f89344870e06c4

**Comment by Barvalg** [comment]
![Platform: git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--0287a20--7560f5f%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
Can you use 1.16.5 instead of 1.16.1?

**Comment by FlorianMichael** [comment]
Tridents were added in 1.13, this issue has nothing to do with ViaRewind, ViaRewind adds only 1.7 -> 1.8 and 1.8 -> 1.9 support, 1.9+ support is added by [ViaBackwards](https://github.com/ViaVersion/ViaBackwards).
