### ISSUE TITLE
CME PacketPlayInArmAnimation

### ISSUE THREAD

**Issue by BestMark** [ViaVersion/ViaRewind#442]
### `/viaversion dump` Output

https://dump.viaversion.com/a49809b850fd06dd0196b990141155237b1917cccda73d7b764a758a550afa6c

### Console Error

```
https://pastebin.com/QYjJa2bx
```

### Bug Description

It started to appear in my server log after this commit: https://github.com/ViaVersion/ViaRewind/commit/4ded017de38cfc811244b0c46132139c20e1a4aa

### Steps to Reproduce

1. Login with 1.8 client.
2. Hit other players.
3. You will be randomly (once per hour) disconnected with the crash.

### Expected Behavior

Crash should not appear

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--%2277cce823%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%2277cce823%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
