### ISSUE TITLE
Commit cd8306a pushed to master instead of dev, causing ViaRewind-master to be incompatible with ViaVersion-master

### ISSUE THREAD

**Issue by buzzcoding** [ViaVersion/ViaRewind#450]
### `/viaversion dump` Output

https://dump.viaversion.com/02fdc076abf03b762ded5d3d3dd681831eda534b249f626b213e91eb78a122cd

### Console Error

```
https://paste.gg/p/anonymous/d7ebde7bdcda43e9867cc4cafe34a1f3
```

### Bug Description

The current build of ViaVersion on the dev branch has a change that requires an update in ViaRewind to support running together with it. The needed change is made in ViaRewind commit [cd8306a](https://github.com/ViaVersion/ViaRewind/commit/cd8306a7fabc8fde87cf15c70c680d5496f94c21).

However, this change was pushed to ViaRewind-master instead of ViaRewind-dev, when it is a change needed to support ViaVersion-dev. Now, ViaRewind-master depends on ViaVersion 4.8.0-23w32a-SNAPSHOT, and since the change is not in ViaVersion-master, but in ViaVersion-dev, using the latest master builds of the Via* plugins together causes an error that makes ViaRewind disable itself.

### Steps to Reproduce

1. Create a Paper server
2. Install the latest versions of ViaVersion, ViaBackwards, and ViaRewind from [https://ci.viaversion.com](https://ci.viaversion.com)
3. Start the server and watch the console

### Expected Behavior

The server should start up with no errors when using the versions which are supposed to be compatible together

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--167%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--167%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Fixed
