### ISSUE TITLE
ViaRewind does not load on Folia anymore

### ISSUE THREAD

**Issue by Yomamaeatstoes** [ViaVersion/ViaRewind#451]
### `/viaversion dump` Output

https://dump.viaversion.com/8e00d1dd5ece945fa4ee7eba98aa6d726c8235cc5c011140474dea3d92f81fe1

### Console Error

```
Put the paste.gg link or text here.
```
https://mclo.gs/SuXtd8g

### Bug Description

Does not load

### Steps to Reproduce

Download latest version on Folia

Download the latest ViaRewind from ( https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/ ) 

### Expected Behavior

Load on Folia

### Additional Server Info

Plugins : AutoPay, BetterBoard, BetterEconomy, BetterRTP, BisectHosting-Folia, BloCommands, BlueMap, ChatFilter, Chunky, ClansLite, ClientDetector, DeluxeMenus, DisableBreeding, DiscordSRV, ElytraSpeed, EpicHomes, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GlobalTrackedMaps, IllegalStack, LuckPerms, mcMMO, NoCheatPlus, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlugManX, ProtocolLib, RedLimiterReloaded, ScoreboardChatShop, SilkySpawnersLITE, spark, StackMob, StormerAntiSpamReloaded, StormerTPAReloaded, StormerWarpsReloaded, TerragenBiomesMockRegistry, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldGuard, ZNPCsPlus

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w33a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w33a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w33a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w33a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Yomamaeatstoes** [comment]
> ![Platform: git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29](https://camo.githubusercontent.com/611fa6738ce8f6c5909e34bb90de90e879881a9411caeb61d818b20fa8ade673/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d466f6c69612d2d253232396165363564312532322532302532384d43253341253230312e32302e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.8.0-23w33a-SNAPSHOT): 1 commits behind dev](https://camo.githubusercontent.com/233478a67e894110391af2608ccec6eecadf119d6ba1b6edbda11b105f2211ca/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e382e302d2d3233773333612d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306465762d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://camo.githubusercontent.com/2640a136e1f4ca41446c27045f74ccd61e2c605061eadb46506da7334e2b2daa/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e342d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.8.0-23w33a-SNAPSHOT): Even with dev](https://camo.githubusercontent.com/77b17f40b4b7d29494107e302fe66f0614921da7c747fd215b4726f4a195ca9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e382e302d2d3233773333612d2d534e415053484f54292d4576656e253230776974682532306465762d627269676874677265656e3f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

I have tried that already. That’s what I was using on the dump I sent. ViaVersion- Dev ( https://dump.viaversion.com/3310c1a827575d996995cca15936f13894f161fdd11b7bc4d2fa469a42748051 )

**Comment by Barvalg** [comment]
![Platform: git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w33a-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w33a--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.8.0-23w33a-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w33a--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Yomamaeatstoes** [comment]
Does
It mean not the development version?

**Comment by Yomamaeatstoes** [comment]
https://dump.viaversion.com/c059f3fe3312e762921f492a025af6d2c71060ba606d61de74813cf0091375ec

**Comment by Barvalg** [comment]
![Platform: git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Folia--%229ae65d1%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w35a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w35a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w35a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w35a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Yomamaeatstoes** [comment]
Updated the plugins again.

**Comment by Yomamaeatstoes** [comment]
ViaVersion did not load

**Comment by Yomamaeatstoes** [comment]
It has been fixed
