### ISSUE TITLE
ERROR IN Protocol1_8To1_9

### ISSUE THREAD

**Issue by AllforHim0064** [ViaVersion/ViaRewind#456]
### `/viaversion dump` Output

https://dump.viaversion.com/89fb8720d64961c93ce6b95e3ab0ce452ab68a7d3b5c70e7a8fb8b26210a53a9

### Console Error

```
[Put the paste.gg link or text here.](https://mclo.gs/3wxBfbA)
```

### Bug Description

A few of my players are getting kicked when opening an ender chest, I experienced a similar error when clicking on a creeper egg.
1.8 client on 1.17.1 server

### Steps to Reproduce

Open an ender chest, or open creative inventory and click on a creeper egg.

### Expected Behavior

The player should not get kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by MorkaZ** [comment]
same here..
![image](https://github.com/ViaVersion/ViaRewind/assets/4214815/afac5e1f-f0f6-4eb8-98a5-f0fbfa3bf969)

**Comment by AllforHim0064** [comment]
> ![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://camo.githubusercontent.com/9c8c9b91b7e961768977c17e692295e2b055128a7d6412e26bf76a8cb639ed58/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3431312532302532384d43253341253230312e31372e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.8.0): 1 commits behind master](https://camo.githubusercontent.com/72a3cd9b6cc406dc5dc83f6895077ab3ac3e8c6dbd99bdfe4ce9c59e3200e506/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e382e30292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Have tried that did not help, here is the error again this time whenever a player clicks a TNT block in the item shop for bedwars.
![image](https://github.com/ViaVersion/ViaRewind/assets/76498719/04d2b7ea-f70e-424a-9664-fd2ba00648df)

**Comment by Luuzzi** [comment]
any updates? same issue when trying to take spawn eggs in creative inventory.

**Comment by Luuzzi** [comment]
```stack trace: https://mclo.gs/zudSgHF```

**Comment by FlorianMichael** [comment]
Try with latest Via* plugins
