### ISSUE TITLE
1.7.10 errors on 1.20.1

### ISSUE THREAD

**Issue by SladeHazard** [ViaVersion/ViaRewind#457]
### `/viaversion dump` Output

https://dump.viaversion.com/5d6d51909685ca9039f30d71bc37739c4a8412965d6a6a3a300607956139f8d4

### Console Error

```
https://paste.gg/p/anonymous/20fe64d9d95e4c99935172617d6533f7
https://paste.gg/p/anonymous/74def82416a3483ba95ee47e559500de
```

### Bug Description

Joining a 1.20.1 server with 1.7.10 client spams the console with error whenever I walk, when i dont walk theres another idle error I think, also im using imageframe plugin so the 2nd error in related to itemframes I think ?

### Steps to Reproduce

Login with 1.7.10 on a 1.20.1 server

### Expected Behavior

no console spam

### Additional Server Info

Velocity proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--23%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--23%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![viarewind-common (3.0.1-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/viarewind--common%20(3.0.1--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>![ViaBackwards(4.8.1-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FlorianMichael** [comment]
Try to use latest ViaRewind snapshot
