### ISSUE TITLE
Protocol 1_7_6 10 to 1_8 crash because profile is null

### ISSUE THREAD

**Issue by drori200** [ViaVersion/ViaRewind#462]
### `/viaversion dump` Output

https://dump.viaversion.com/9353cd6aa02393906f7fa85850eaf24fad27943c390247414c981b09ef10db45

### Console Error

```
https://mclo.gs/m4mEmjg
```

### Bug Description

Trying to join from 1.19.4 to 1.7 results in the crash submitted.

My server setup is two backends under a 1.20 velocity proxy.

Backend 1 is 1.19.4 and used as a queue server to redirect to backend 2 which is 1.7.10

The error only happens once on the first try of connecting to the queue server for some people. It will kick them once and on the next try they successful manage to join. It only happens for some players and never happens for some other players connecting with a client of the same version(1.7.10).

### Steps to Reproduce

1. Use 1.7.10 client to join the 1.19.4 server
2. Get redirected to the 1.7.10 server and get kicked because of the error

### Expected Behavior

Join the 1.7.10 server fine

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by drori200** [comment]
Updated dump
https://dump.viaversion.com/c4e89b3306ef2b802157903d927f4e2f8745dce1e935b5575d45f2425f49d61b

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please update ViaRewind to latest dev version

**Comment by drori200** [comment]
> Please update ViaRewind to latest dev version

Done. New dump:
https://dump.viaversion.com/93052b48cec32dfa7c5be836ae1c287a35b193930f207d49f9ef69a2113f23af

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--%22483368e%22%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
What's the exception you are getting now?

**Comment by drori200** [comment]
> What's the exception you are getting now?

Same exception

**Comment by drori200** [comment]
> What's the exception you are getting now?

Same exception as before.

**Comment by drori200** [comment]
@FlorianMichael anything new regarding this?

**Comment by FlorianMichael** [comment]
Fixed in latest dev version
