### ISSUE TITLE
Creeper explosion causing 1.8 client to disconnect on 1.20.4 server

### ISSUE THREAD

**Issue by BadAimWeeb** [ViaVersion/ViaRewind#467]
### `/viaversion dump` Output

https://dump.viaversion.com/d701f5b64e0d5e8482b760170e974b156d26e7c468cc9d7b44aa7841111a37a0

### Console Error

https://paste.gg/p/anonymous/dffa7f01a93d47cab6554287a8dfeb3c

### Bug Description

Saw this on server log. Creeper explosion should not disconnect player.

### Steps to Reproduce

Not sure how to reproduce this.

### Expected Behavior

Client should not be disconnected.

### Additional Server Info

Server is running on Paper 1.20.4 with 1.21 feature enabled.
Velocity is used (3.2.0-SNAPSHOT git-7774e993), Velocity/1150 enabling 1.20.3/4 proxy (should not affect anything).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--324%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--324%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Fixed.
