### ISSUE TITLE
Exploding TNT kicks all 1.7/1.8 players from 1.20.4 server

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaRewind#471]
### `/viaversion dump` Output

https://dump.viaversion.com/c58bd0bd8f56643a7a5b5455783b058f3a9feaf2681a8a4bb311eb64ea7f2b3d

### Console Error

The full console logs can be found [here](https://pastebin.com/raw/7saxTEsu).

### Bug Description

When exploding any TNT block whilst playing on 1.7/1.8 client, ViaRewind instantly kicks everyone via the explosion packet.

### Steps to Reproduce

1. Make a clean 1.20.4 server,
2. Join with a vanilla 1.7/1.8 client,
3. Get a TNT and Fire Charge,
4. Light up the TNT with the Fire Charge,
5. Get kicked instantly right after it explodes.

### Expected Behavior

Nobody gets kicked after TNT has exploded.

### Additional Server Info

1. This server did not use any proxy software,
2. Paper 1.20.4, *(Build 351)*
3. ViaVersion, ViaBackwards, ViaRewind. *(ViaRewind Legacy Support not included because it causes problem on boot)*

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [ ] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--351%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--351%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3><br><details><summary></summary>,</details>

**Comment by Kichura** [comment]
> ![Platform: git--Paper--351%20%28MC%3A%201.20.4%29](https://camo.githubusercontent.com/0ebdfa674191655d79c135e9c54ae81f1759851aac7ba5448c5efa1629e3360a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3335312532302532384d43253341253230312e32302e342532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.3-SNAPSHOT): 6 commits behind master](https://camo.githubusercontent.com/7f0c71616eee7bf5c4c113c9cdb24e19d0d9afc33224560cad7d30214cca2d72/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e332d2d534e415053484f54292d36253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.2-SNAPSHOT): 3 commits behind master](https://camo.githubusercontent.com/2d0ba7fe3a3dd257cbcd185c7ddf9db292d136826ab6fdfae32df0449954448d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e322d2d534e415053484f54292d33253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(3.0.6-SNAPSHOT): 5 commits behind master](https://camo.githubusercontent.com/0e28a4c884f4a383029e9fb49447dbd5ba76dceab3270947fa447bca0f06b6d1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028332e302e362d2d534e415053484f54292d35253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> ### Please try the **latest** build(s) from [ci.viaversion.com](https://ci.viaversion.com/). In case the issue still persists send the new dump
> 
> ,

Note: This persists in latest builds too.

**Comment by FlorianMichael** [comment]
Fixed, thanks
