### ISSUE TITLE
Error and kick on player death

### ISSUE THREAD

**Issue by LucidAPs** [ViaVersion/ViaRewind#472]
### `/viaversion dump` Output

https://dump.viaversion.com/bffa2bcfad1b79903b7bca763a84955647b1cb55017a5f8cf53a5f1a37b0fa76

### Console Error

https://mclo.gs/9Vgxtr9

### Bug Description

https://mclo.gs/9Vgxtr9

### Steps to Reproduce

https://mclo.gs/9Vgxtr9

### Expected Behavior

https://mclo.gs/9Vgxtr9

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2110%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2110%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>tab_warn,tab_warn,tab_warn,tab_warn,</details>

**Comment by LucidAPs** [comment]
Or maybe its not the deaths that cause these?

https://mclo.gs/7KCllB6

**Comment by LucidAPs** [comment]
actually these errors might be unreleated to the kicks

**Comment by Kichura** [comment]
Closed as this issue is in the wrong repository as this does not mention viarewind atleast once.
