### ISSUE TITLE
Bad packet ID 26 on Paper 1.19.4

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaRewind#475]
### `/viaversion dump` Output

https://dump.viaversion.com/2da786f6fd2a86ecf9ddf13821f3552dffe23781106f280dd2df4aae99387428

### Console Error

*(No console errors have been discovered)*

### Bug Description

When attempting to connect to a 1.19.4 server, ViaRewind will not function correctly and drop vanilla client with the error above.

### Steps to Reproduce

1. Make a vanilla 1.8.9 client,
2. Make a Paper 1.19.4 server that contains all three via* plugins,
3. Attempt to connect to server,
4. Get dropped from server instantly.

### Expected Behavior

1.8.9 clients can connect properly without issues.

### Additional Server Info

1. This setup does not make use of any proxies,
2. Paper 1.19.4 on Fedora 40,
3. ViaVersion, ViaBackwards and ViaRewind.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Does this issue also appear for 1.9.x clients?

**Comment by Kichura** [comment]
Tested this with newest commit and it seems to be fixed.
