### ISSUE TITLE
Latest ViaRewind not working

### ISSUE THREAD

**Issue by linsaftw** [ViaVersion/ViaRewind#482]
### `/viaversion dump` Output

https://dump.viaversion.com/e95701a0126f73f34156af0a2175f1e66f6b4466bb3b40334db8777a08693231

### Console Error

No console error

### Bug Description

Logging in screen infinite. 1.20 server with latest via plugins. Trying to join with 1.8 and 1.7.

### Steps to Reproduce

Install the plugin in the spigot servers.
Install BungeeCord.
Try to join.

### Expected Behavior

To be  able to join.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2095%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2095%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre2--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre1--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
