### ISSUE TITLE
Enchantment table enchants name

### ISSUE THREAD

**Issue by EmanuelFNC** [ViaVersion/ViaRewind#484]
### `/viaversion dump` Output

https://dump.viaversion.com/69822e322b6ecbf4c7625754457ffb8aa58729979682c39ae70b2f82cdecffcc

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

![image](https://github.com/ViaVersion/ViaRewind/assets/45471276/1723870a-190a-4728-b23d-4508c4af4508)

in version 1.8, the enchantments on the enchantment table have this name instead of just the name and level

### Steps to Reproduce

try to enchant an item in 1.8 with the server in 1.20.4

### Expected Behavior

to return to normal

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2124%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2124%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-23w51b-SNAPSHOT): 39 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-39%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): 13 commits behind dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-13%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-23w51b-SNAPSHOT): 22 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-22%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
