### ISSUE TITLE
Enchantment table enchants name

### ISSUE THREAD

**Issue by EmanuelFNC** [ViaVersion/ViaRewind#485]
### `/viaversion dump` Output

https://dump.viaversion.com/425561599c28ad109a5164914376ea565700fa4b91fda79f40d89b9de5e29498

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

in version 1.8, the enchantments on the enchantment table have this name instead of just the name and level

![image](https://github.com/ViaVersion/ViaRewind/assets/45471276/63c196d3-b109-42f8-936e-ffc79618e32a)
![image](https://github.com/ViaVersion/ViaRewind/assets/45471276/2edcd4e4-d9d0-41eb-b03d-737447a0e51e)
![image](https://github.com/ViaVersion/ViaRewind/assets/45471276/9aa978ef-9686-4b2e-bfec-06bda21ed706)

### Steps to Reproduce

try to enchant an item in 1.8 with the server in 1.20.4

### Expected Behavior

to return to normal

### Additional Server Info

nullcordx

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2124%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2124%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w05b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w05b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w05b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w05b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
