### ISSUE TITLE
Error login a 1.20.1 server

### ISSUE THREAD

**Issue by Dragon-ts** [ViaVersion/ViaRewind#487]
### '/viaversion dump' Output

https://dump.viaversion.com/0ba14918924be36b9a4aaa65d090cfd4ec3427ed2df21fd9f766275e8321e121

### Console Error

https://paste.gg/p/anonymous/b0e7f10625b44f3694da16508821b30a

### Bug Description

when I entered the server, I was logged out directly, and it crashed
here's the log(https://paste.gg/p/anonymous/b0e7f10625b44f3694da16508821b30a)

### Steps to Reproduce

1.use 1.7.10 client
2. login the server
3. found that error :(

### Expected Behavior

enter the server as normal

### Additional Server Info

server: spigot
server-version: 1.20.1
other plugins: Authme, gayser, CoreProtection, SkinsRestorer, Floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Dragon-ts** [comment]
Besides, I found that from 1.8 to 1.20.4 is possible to enter normally.

**Comment by I-hate-2FA** [comment]
i have same issue,also 1.20.1 server and 1.7 client and client crash when joining with same latestlog.txt
on server it says `handledisconnection() called twice`

**Comment by I-hate-2FA** [comment]
https://dump.viaversion.com/e1d940d8c6f4d30811c82a950c8ba2d7b0bb19b59a21f44b634e463487213fbe
[latestlog.txt](https://github.com/ViaVersion/ViaRewind/files/15142227/latestlog.txt)

**Comment by Barvalg** [comment]
![Platform: 0.4.14+66--main](https://img.shields.io/badge/Platform-0.4.14+66--main-3498db?style=flat-square) </br>![ViaVersion (4.10.0): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.0): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FlorianMichael** [comment]
Fixed in latest dev build on https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/

**Comment by I-hate-2FA** [comment]
i have updated and i can join now, but if i died in 1.7 i crash and cannot respawn normally, need to use newer version to respawn to play again

and with mobs not existant in old version like a frog, in 1.12 i join i see a rabbit with nametag frog, but in 1.7 i see a chicken with nametag chicken, idk if this is intended, probably not

**Comment by I-hate-2FA** [comment]
https://dump.viaversion.com/47e122d8a7362c2ecfb7ef66795874cc98c49f77607afd97e87de644d8cb7756

**Comment by Barvalg** [comment]
![Platform: 0.4.14+66--main](https://img.shields.io/badge/Platform-0.4.14+66--main-3498db?style=flat-square) </br>![ViaVersion (4.10.0): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
