### ISSUE TITLE
can't climb ladders

### ISSUE THREAD

**Issue by rqyyy** [ViaVersion/ViaRewind#491]
### `/viaversion dump` Output

https://dump.viaversion.com/5f270bbe35ab2b190f914e2a8d1ca3d2593696d45234d3ad87c109ff515cfb91

### Bug Description

i cant climb ladders. it feels like the player ladder movement is glitched. i can climb vines though but not ladders
please fix this issue :)

### Steps to Reproduce

login with 1.8 or lower version
place a ladder and try to climb it

### Expected Behavior

player should climb the ladder instead of glitching. however players from 1.20 (newer version) can climb it properly

### Additional Server Info

I have Vulcan anticheat, i also tried without vulcan but same issue.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--381%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.7-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.7--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Update to latest ViaRewind Legacy Support and switch to master versions of Via*
