### ISSUE TITLE
Error when placing a block on 1.12.2

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaRewind#504]
### `/viaversion dump` Output

https://dump.viaversion.com/645e8785954750e55564ecc948ab23a8f05a5d6a9964a79ef9a46838452e8b14

### Console Error

```
Put the mclo.gs link or text here.
```
https://pastebin.com/jLh7pAWQ

### Bug Description

When you place a block it makes no sound and gives the following error on console

### Steps to Reproduce

1. Make a 1.12.2 server
2. Put ViaVersion, ViaBackwards, ViaRewind and ViaRewind-LegacySupport on it
3. Place a block and see the error on console

### Expected Behavior

To do the sound as it was before

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%22a2ea0f1%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%22a2ea0f1%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.0): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pabloalba16** [comment]
https://dump.viaversion.com/038c36f09984096ad0cc4364196c9813a50a1e1a7f40b6c16caa90269a7c6a5b

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%22a2ea0f1%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%22a2ea0f1%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.0): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by pabloalba16** [comment]
Still the same, no changes have been made on 4.10.1 SNAPSHOT

**Comment by FlorianMichael** [comment]
Try with Spigot/Bukkit/Paper instead of the current fork, I guess the fork you are using is renaming fields or methods causing the reflection fixes to fail.

**Comment by pabloalba16** [comment]
Same issue on regular 1.12.2 paper

**Comment by pabloalba16** [comment]
https://pastebin.com/xrGvL7Mj

**Comment by FlorianMichael** [comment]
Resolved, update ViaRewind-Legacy-Support

**Comment by pabloalba16** [comment]
https://dump.viaversion.com/54e6209757b841c23f2b6238df53ff3ba26e1577ae89d757ed17af5af5966a74

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
Update ViaRewind Legacy Support

**Comment by pabloalba16** [comment]
thats what im trying to

**Comment by pabloalba16** [comment]
im downloading this but the error is still there: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/15/

**Comment by FlorianMichael** [comment]
Can't be, either you didn't downloaded the new jar or the error is different.

**Comment by pabloalba16** [comment]
its the same error, are you sure the latest jar is actually the latest jar? https://pastebin.com/vrbAPi2N
