### ISSUE TITLE
Exploring 1.20.4 worlds in 1.7-1.8 causes player to be kicked

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaRewind#505]
### `/viaversion dump` Output

https://dump.viaversion.com/4d7d9b687035e8dffebfa91fdd05c2a2192818add64c90a742b2d591bc9eca3a

### Console Error

The server logs can be found [here](https://mclo.gs/TSbRqlQ).

### Bug Description

When exploring any 1.20.4 worlds in 1.7.x - 1.8.x client, The player will eventually get thrown out from the server after exploring for a while.

### Steps to Reproduce

1. Make a new 1.20.4 server,
2. Install the latest via* plugins as normal,
3. Log in with any 1.7.x - 1.8.x client,
4. Explore the world for a while - Usually creative is the fastest method.

### Expected Behavior

The player will not get thrown out from the server.

### Additional Server Info

1. This server did not use any proxy-related software,
2. Purpur Build 2176, *(MC: 1.20.4)*
3. ViaVersion 4.10.1-SNAPSHOT, ViaBackwards 4.10.0 and ViaRewind 3.1.0.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.0): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Does this also happen with 1.9.x clients?

**Comment by Kichura** [comment]
Doesn't seem like i can reproduce on there except if i'm correct, the chunks loading on 1.9.x is much more odd compared to the other two client versions.
