### ISSUE TITLE
Sounds not working when placing a block

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaRewind#506]
### `/viaversion dump` Output

https://dump.viaversion.com/6a11fabc1c8e19c790e7d9468f891fe8dae84e51fe898256e499ebee6bbe708f

### Console Error

```
Put the mclo.gs link or text here.
```
https://pastebin.com/ZiLinaJd

### Bug Description

When you place a block, no matter what block is, does not reproduce the sound of placing it. 
Something i realise if you remove ViaRewind-Legacy it does not appear any error on console but the bug is still there
I made 2 videos, one on 1.12.2 and another on 1.16.5 (server version)
Hope it helps:
https://streamable.com/3wm03c
https://streamable.com/1b22qw

### Steps to Reproduce

Create a 1.12.2 or 1.16.5 server (for example)
Put all via plugins (ViaVersion, ViaBackwards, ViaRewind, ViaRewind-Legacy)
Enter on 1.8.9 minecraft version
Place a block

### Expected Behavior

I expected the sound of the block i place

### Additional Server Info

These are simple servers that are created in a minute or so. Nothing special and only with Via plugins, nothing more added.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Install ViaRewind-Legacy-Support from here: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/

**Comment by pabloalba16** [comment]
The version i used on both videos are from that link

**Comment by FlorianMichael** [comment]
Fixed with the latest commit
