### ISSUE TITLE
1.8 Clients crashing when interacting with end rod item

### ISSUE THREAD

**Issue by turnolos** [ViaVersion/ViaRewind#507]
### `/viaversion dump` Output

https://dump.viaversion.com/e24ef572e3edefe651db942374e5868507737fec29cb6ee39888d5de6944cc54

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

When interacting with a end rod on our 1.12.2 native server running latest viaversion, viabackwards and viarewind, players using client version 1.8.9 will crash. I have attached a video of this happening and two separate crash logs of the error occurring.

[when_in_pv.txt](https://github.com/ViaVersion/ViaRewind/files/15143801/when_in_pv.txt)
[when_it_item_frame.txt](https://github.com/ViaVersion/ViaRewind/files/15143802/when_it_item_frame.txt)

Video of it occurring: https://gyazo.com/7cddfabb42f188fbdd6886e70ae1a1ee

### Steps to Reproduce

1.) Get 1.12.2 paper spigot server with viaversion, viabackwards and viarewind installed 

2.) Place an end rod in inventory or in chest or in itemframe

3.) Crash

### Expected Behavior

Should not crash

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22662261c1%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%22662261c1%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
Fixed with the merge of https://github.com/ViaVersion/ViaBackwards/pull/731
