### ISSUE TITLE
1.8.9 client cannot join 1.12.2 server

### ISSUE THREAD

**Issue by BestMark** [ViaVersion/ViaRewind#508]
### `/viaversion dump` Output

https://dump.viaversion.com/39f07558167e9d0c160b2943579ea52be0baf052d4a304de1f77bebab266664a

### Console Error

```
https://mclo.gs/jjjHGJd
```

### Bug Description

1.8.9 client cannot join 1.12.2 server

### Steps to Reproduce

1. Login with 1.8.9 client
2. Join 1.12.2 server with latest ViaVersion, ViaBackwards and ViaRewind from Jenkins.

### Expected Behavior

You cannot join the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--%2277cce823%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%2277cce823%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Can't reproduce, seems to be a plugin issue.
