### ISSUE TITLE
1.7 Client crash on join with Citizens

### ISSUE THREAD

**Issue by ytnoos** [ViaVersion/ViaRewind#509]
### `/viaversion dump` Output

https://dump.viaversion.com/857d1e8c4bd4fb2627711846e375a81598b5b7c7e0fda444a6d198d1e2277981

### Console Error

No console error

### Bug Description

When I join with 1.7 client on a 1.8 server the client crashes due to an Entity which seems to be related with ViaVersion, it didn't happen before the update for 1.20.5

### Steps to Reproduce

This is the Citizens NPC which leads to the client crash https://mclo.gs/jk51aTu
Client crash https://mclo.gs/wjzB5t9

### Expected Behavior

No crash

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Try the latest dev version at: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/

**Comment by ytnoos** [comment]
![2024-05-01_13 06 06](https://github.com/ViaVersion/ViaRewind/assets/21027982/94b64801-8d98-4617-ab99-8b6d17ad8fbe)
Now I don't crash but I'm able to see zombies inside Holograms. I'm using DecentHolograms plugin for holograms.

**Comment by FlorianMichael** [comment]
You should try out the latest commit / dev build, it might be fixed.

**Comment by FlorianMichael** [comment]
https://github.com/ViaVersion/ViaRewind/commit/780b981c68bc9a510e08ba2838f274655306c66a
