### ISSUE TITLE
[1.8->1.7] Custom boss bars do not display correctly

### ISSUE THREAD

**Issue by calcastor** [ViaVersion/ViaRewind#512]
### `/viaversion dump` Output

https://dump.viaversion.com/be943bbbf6ed10f6f1aae5f1712118f56d8397c43127f39e01456ec6790fde61

### Console Error

N/A

### Bug Description

Custom bossbars created with Adventure display only as "Wither" for 1.7.10 clients connected to 1.8.8 servers.

### Steps to Reproduce

1. Log on to a 1.8.8 server with 1.7.10
2. Do something to make a custom boss bar (the bug report case implements them with Adventure)
3. Observe only the "Wither" mob title and no custom progress or otherwise in the boss bar

### Expected Behavior

The boss bar should represent what it does in 1.8.8

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Is this something which started happening with the current release or can you also reproduce it on this builds:
ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3
ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2
ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

**Comment by calcastor** [comment]
> Is this something which started happening with the current release or can you also reproduce it on this builds: ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3 ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2 ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

This issue does not occur on these builds.

**Comment by FlorianMichael** [comment]
Are you sure this is a 1.8 server or is it 1.9+?

**Comment by calcastor** [comment]
> Are you sure this is a 1.8 server or is it 1.9+?

It is a 1.8.8 Paper fork called [SportPaper](https://github.com/Electroid/SportPaper) however this is a custom build with some separate changes.

**Comment by FlorianMichael** [comment]
Yeah I found the issue already, was confused at the beginning.
