### ISSUE TITLE
[1.8->1.7] All buttons render as levers

### ISSUE THREAD

**Issue by calcastor** [ViaVersion/ViaRewind#513]
### `/viaversion dump` Output

https://dump.viaversion.com/be943bbbf6ed10f6f1aae5f1712118f56d8397c43127f39e01456ec6790fde61

### Console Error

N/A

### Bug Description

Instead of rendering buttons placed on top or bottom of blocks as levers, all buttons are sent to 1.7.10 users as levers from a 1.8.8 server regardless of their placement.

### Steps to Reproduce

1. Log onto a 1.8.8 server with 1.7.10
2. Place a button on a wall
3. Observe lever sent to 1.7.10 rather than button

### Expected Behavior

Only levers placed on top or bottom of blocks should render as levers or in otherwise appropriate situations

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Is this something which started happening with the current release or can you also reproduce it on this builds:
ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3
ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2
ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

**Comment by FlorianMichael** [comment]
Fixed, you need to update ViaBackwards
