### ISSUE TITLE
[1.8->1.7] Non-oak doors do not translate correctly

### ISSUE THREAD

**Issue by calcastor** [ViaVersion/ViaRewind#514]
### `/viaversion dump` Output

https://dump.viaversion.com/27b3d95a109c01a737a83c957651c1ba57cac439a79c1694e9ef47b891fce24f

### Console Error

N/A

### Bug Description

Non-oak doors do not appear to translate from 1.8 to 1.7 correctly, see below:

![image](https://github.com/ViaVersion/ViaRewind/assets/43831917/32b44a7a-ee2f-4687-b7d5-a49170ccb694)

This seems to happen with all types of non-oak doors.

### Steps to Reproduce

1. Log onto 1.8.8 server with 1.7.10
2. Place or find a dark oak door, for instance, in a world
3. Observe incorrect translation to wooden door

### Expected Behavior

Non-oak doors should map to oak wooden doors in 1.7 correctly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--c03663e--P.2081566--SP.aff24bb--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Is this something which started happening with the current release or can you also reproduce it on this builds:
ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3
ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2
ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

**Comment by calcastor** [comment]
> Is this something which started happening with the current release or can you also reproduce it on this builds: ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3 ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2 ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

Not reproducible on these builds
