### ISSUE TITLE
ViaRewind sound translate issue

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaRewind#515]
### `/viaversion dump` Output

https://dump.viaversion.com/1538df69f0758d73e7d68b4b35af09271f6b112037ae7268d836af71afff9da5

### Console Error

```
Put the mclo.gs link or text here.
```
No errors on console, i made a video which explains it better than me: https://streamable.com/j495ix

### Bug Description

Im running a 1.12.2 server which contains the minigame called MurderMystery. Everything works well except for the part of the countdown as you can watch in the video i made, it does not translate correctly the countdown sound. In native does not happen.

### Steps to Reproduce

Make a 1.12.2 server with latest Via plugins (ViaVersion, ViaBackwards, ViaRewind, ViaRewind-Legacy)
Run MurderMystery and create an arena
Play the arena and hear the "countdown" sound

### Expected Behavior

I expected the same sound as in native version on higher. On 1.20.4 theh sound does not change

### Additional Server Info

Im using a fork of paper so, let me know if you want me to test it on regular paper if needed
Via plugins are on the backed server, not in the proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Beast--%229585c44%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Beast--%229585c44%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by pabloalba16** [comment]
Just tested ViaVersion 4.9.3 and does not happen

**Comment by FlorianMichael** [comment]
I can't really reproduce this issue, do you know the exactly sound which is used here? I tried to play dispenser/gui button sounds using the /playsound command but everything works fine for me.

**Comment by pabloalba16** [comment]
The plugin doesn't really tells you the sounds it uses, but seems to be the CLICK sound

**Comment by FlorianMichael** [comment]
Which plugin is used here exactly so I can try to reproduce it?

**Comment by pabloalba16** [comment]
https://github.com/Plugily-Projects/MurderMystery

**Comment by FlorianMichael** [comment]
Thanks

**Comment by pabloalba16** [comment]
Its the CLICK sound, confirmed. I can make a video if you desire

**Comment by FlorianMichael** [comment]
Does this issue also happen when using a 1.9 client?

**Comment by pabloalba16** [comment]
going to test it rn

**Comment by pabloalba16** [comment]
on 1.9 client does not happen

**Comment by FlorianMichael** [comment]
what about 1.10?

**Comment by pabloalba16** [comment]
same as 1.9

**Comment by FlorianMichael** [comment]
And you surely tried 1.9.0 and not something like 1.9.3/4?

**Comment by pabloalba16** [comment]
oh my bad, i tested 1.9.4

**Comment by FlorianMichael** [comment]
Should be fixed, thanks for reporting and helping, download at:
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/

**Comment by pabloalba16** [comment]
Yes confirm it is fixed, thank YOU for the quick response and fix!

**Comment by FlorianMichael** [comment]
No problem!
