### ISSUE TITLE
Bow animation not showing for 1.8 players

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaRewind#516]
### `/viaversion dump` Output

https://dump.viaversion.com/afcf8239e5815411892b97d54d7263893071c436072838e5ea74933465bf82bc

### Console Error

```
Put the mclo.gs link or text here.
```
I made a video showing it: https://streamable.com/t0p8a8

### Bug Description

It does not show the bow charging animation

### Steps to Reproduce

Create a 1.12 server (for example)
Put all latest SNAPSHOT Via plugins (ViaVersion, ViaBackwards ViaRewind, ViaRewind-Legacy)

### Expected Behavior

To actually show the animation as native

### Additional Server Info

This was working before as it got fixed on Apr 3: https://github.com/ViaVersion/ViaRewind/issues/64#issuecomment-2034325292

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by pabloalba16** [comment]
Btw this also happens with sword blocking animation, but this issue was never resolved afaik, i hope it also gets resolved soon: https://streamable.com/t2n3ao

**Comment by FlorianMichael** [comment]
Is this something which started happening with the current release or can you also reproduce it on this builds:
ViaVersion: https://github.com/ViaVersion/ViaVersion/releases/tag/4.9.3
ViaBackwards: https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2
ViaRewind: https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6

**Comment by pabloalba16** [comment]
Just tested ViaVersion 4.9.3 and ViaRewind. Bow animation is working, sword blocking isn't

**Comment by FlorianMichael** [comment]
Bows should be fixed now, will take care of swords another time.
