### ISSUE TITLE
Random crashes on client when rendering a specific chunk? (1.20.3/4 server)

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaRewind#521]
seems to affect versions 1.7.2 up to 1.8.9.
[vanilla 1.7.2 crash report](https://mclo.gs/DHIMPxI)
[viaproxy debug log](https://mclo.gs/QESfGPc)
[viaproxy latest log](https://mclo.gs/KiFOQH5)

**Comment by RaphiMC** [comment]
@NPC-Master3304 Forgot to mention, but please test if the issue still occurs with the dev build of ViaProxy: https://ci.viaversion.com/view/Platforms/job/ViaProxy/

If it does go to the Advanced tab of the GUI and press the "create ViaVersion dump" button and upload it here

**Comment by RaphiMC** [comment]
No thats good. Now you have to wait until someone looks into this issue

**Comment by RaphiMC** [comment]
Leave it open. It will be closed once its fixed

**Comment by bramcia** [comment]
hey i also have crashes with Buffer Underflow messages or Excepted to receive (amount) bytes, received (less) bytes.

**Comment by FlorianMichael** [comment]
Please try if this still happens with the latest ViaProxy and if so provide us steps to reproduce this (in a new GitHub issue). Same for you @bramcia
