### ISSUE TITLE
packet issue with 1.7.2 clients (with viaproxy)

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaRewind#522]
### `/viaversion dump` Output

https://dump.viaversion.com/57959ef65725ee04204d7b3846de9846d8ab633fd261431620ea21f9b83448d2

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/4FFOl2b)
```

### Bug Description

when connecting to a 1.20.3/1.20.4 server (like hoobs.live), game immediately gets kicked when you're playing on 1.7.2.
[https://i.imgur.com/3YLTT9L.png](https://i.imgur.com/3YLTT9L.png)

### Steps to Reproduce

1. Login with a 1.7.2 client on a 1.20.4 server.

### Expected Behavior

not being kicked by a packet.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<b>Put the jars into config/viafabricplus/jars.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
I just fixed this issue lol.
