### ISSUE TITLE
Console spam when someone on 1.8 joins into 1.20.4 backend server

### ISSUE THREAD

**Issue by Rubenicos** [ViaVersion/ViaRewind#524]
### `/viaversion dump` Output

https://dump.viaversion.com/8a500372d3825c7d7689bc241936de5fdc279f06dcfc4ff0b0d0eb0e42f90b15

### Console Error

```
https://mclo.gs/JtalD4H
```

### Bug Description

When someone using 1.8 joins into 1.20.4 backend server the console start spamming

### Steps to Reproduce

1. Login with a 1.8.8 client on 1.20.4 server

### Expected Behavior

The console spam should not appear

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%221954a51%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%221954a51%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
It looks like some plugin is sending invalid data, try if it also appears just with Via* plugins installed, if that's not the case, try to perform a binary search on your plugin list:

1. Remove half of the existing plugins and put them aside for now,
2. Run the server again,
3. Is it still creating errors from there?

*(If yes; Repeat from step 1 with current items)*
*(If not; Swap out the current plugins with the ones set aside and repeat from step 1)*

4. Repeat process until problematic plugin/s are found.
