### ISSUE TITLE
Couldn't place player in world

### ISSUE THREAD

**Issue by ImYenil** [ViaVersion/ViaRewind#528]
### `/viaversion dump` Output

https://dump.viaversion.com/973b4ac05629c295d166546dec7e3f493a9b75eb5d7beeb3ad6f5ac9c7f8fb2c

### Console Error

https://mclo.gs/YsI7Ias

### Bug Description

when player server joined

### Steps to Reproduce

login with 1.8.8 client
and get issue

### Expected Behavior

Access is possible in the latest version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please provide the full server log as well as more context about this issue, try if it also appears on 1.9 clients and try to perform a binary search on your plugin list:
1. Remove half of the existing plugins and put them aside for now,
2. Run the server again,
3. Is it still creating errors from there?

(If yes; Repeat from step 1 with current items)
(If not; Swap out the current plugins with the ones set aside and repeat from step 1)

4. Repeat process until problematic plugin/s are found.
