### ISSUE TITLE
Glitch when someone goes below y=0

### ISSUE THREAD

**Issue by TheTruePerson** [ViaVersion/ViaRewind#529]
### `/viaversion dump` Output

.

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

If you are in version 1.8 and you join a 1.20 server and go below y=0 the game glitches out.

### Steps to Reproduce

Create a 1.20 server
Join with 1.8
Mine below y=0

### Expected Behavior

It should work the same as in 1.18, the player should be able to see the blocks and move around.

### Additional Server Info

Tried it with no extra things, just plain spigot (and i also tried paper.) No luck.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
That's a ViaBackwards (1.16 -> 1.17) protocol issue, you can set `bedrock-at-y-0` to `true` in the `ViaBackwards/config.yml` file so players below 1.17 will see a bedrock layer at position 0.

**Comment by TheTruePerson** [comment]
i dont see it, heres the settings i see

# If you need help, you can join our Discord - https://viaversion.com/discord
#
# Always shows a mapped mob's original name, and not only when hovering over it with the cursor.
always-show-original-mob-name: true
#
# Writes name and level of custom enchantments into the item's lore.
# Set this to false if you see the entries doubled/if the custom-enchant plugin already writes these into the lore manually.
add-custom-enchants-into-lore: true
#
# Adds the color of a scoreboard team after its prefix for 1.12 clients on 1.13+ servers.
add-teamcolor-to-prefix: true
#
# Converts the 1.13 face look-at packet for 1.12- players. Requires a bit of extra caching.
fix-1_13-face-player: false
#
# Fixes 1.13 clients and lower not seeing color or formatting in inventory titles by converting them to legacy text.
# If you have issues with translatable text being displayed wrongly, disable this.
fix-formatted-inventory-titles: true
#
# Sends inventory acknowledgement packets to act as a replacement for ping packets for sub 1.17 clients.
# This only takes effect for ids in the short range. Useful for anticheat compatibility.
handle-pings-as-inv-acknowledgements: false
#
# Suppresses warnings of missing emulations for certain features that are not supported (e.g. world height in 1.17+).
suppress-emulation-warnings: false

**Comment by FlorianMichael** [comment]
Delete the config file and restart the server, also make sure to have latest dev builds from https://ci.viaversion.com/

**Comment by TheTruePerson** [comment]
> Delete the config file and restart the server, also make sure to have latest dev builds from https://ci.viaversion.com/

i did, and i do have the latest version. same issue.
