### ISSUE TITLE
1.7.10 clients cannot load chunks on 1.20.4 server

### ISSUE THREAD

**Issue by wuangg** [ViaVersion/ViaRewind#530]
### `/viaversion dump` Output

https://dump.viaversion.com/86238c2b78b9b7c2c943d886f02e1a2e5297183f8349119eb1211792b958f0f8

### Console Error

```
No console errors
```

### Bug Description

Players using 1.7.10 clients joining 1.20.4 server successfully, but cannot load any chunk

### Steps to Reproduce

1. Run a 1.20.4 Paper server with latest Via* dev builds
2. Login with a 1.7.10 client

### Expected Behavior

Players on 1.7.10 client should be able to load chunks on 1.20.4 server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--393%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--393%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by wuangg** [comment]
![2024-07-12_16 10 15](https://github.com/user-attachments/assets/3e8bd840-2e39-4051-8d5e-74f5500639a1)

**Comment by FlorianMichael** [comment]
I can not reproduce your issue, try if this also happens with an Vanilla 1.7.10 client. This might be an rendering issue of your modifications
