### ISSUE TITLE
Collision issues with ladders and carpets (and probably more?)

### ISSUE THREAD

**Issue by NPC-Master3304** [ViaVersion/ViaRewind#534]
### `/viaversion dump` Output

https://dump.viaversion.com/993e3c33bb3b716c58c173bf318a053778a8e3b336139beea50f6e76b6c12dc0

### Bug Description

Ladders will teleport you back down if you try to climb up them on any version before 1.9.3 ([wasn't able to test this out on 1.9-1.9.2](https://github.com/ViaVersion/ViaRewind/issues/533))
Carpets will do the same thing on 1.7.X versions, however carpets work on 1.8 and above.

https://github.com/user-attachments/assets/a9fff058-c02a-4104-8bd7-f66418c672b3

### Steps to Reproduce

**Ladders:**
1. Join a 1.21 (seemed to also occur on older servers as in 1.20 and 1.19 iirc) server on 1.7.X
2. Climb up a ladder.

**Carpets:**
1. Join a 1.21 (seemed to also occur on older servers as in 1.20 and 1.19 iirc) server on any version from 1.8 to 1.9.3.
2. Walk over any carpet block.

### Expected Behavior

Being able to climb ladders and walk over carpets without getting stuck.

### Additional Server Info

[ViaProxy log](https://mclo.gs/MDinZXa)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 3.0.2--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.2--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
That's a known issue which can't be fixed on protocol level and therefore won't be, if you use Via* on the serverside you can install [ViaRewind-Legacy-Support](https://github.com/ViaVersion/ViaRewind-Legacy-Support) but this won't get fixed with ViaProxy
