### ISSUE TITLE
1.7.10 players are still not allowed to enter after installing viarewind.

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [ViaVersion/ViaRewind#536]
### `/viaversion dump` Output

https://dump.viavers ion.com/86c200d3eb151288f79cf18a8189e3ca161efa8a010f52d10e57 265e1b2b718f

### Console Error

```
Put the mclo.gs link or text here.
```
NOTHING

### Bug Description

![image](https://github.com/user-attachments/assets/37f7a547-cfd2-4086-965b-c9efd666c5a5)
![Uploading image.png…]()

### Steps to Reproduce

1. Install three plugins(Copy multiple groups for each back-end server, without installing in bungee)

2. Use 1.7.10 to try to enter the game.

### Expected Behavior

Didn't you say that 1.8 and 1.7 players could access the server? Why is it only 1.8?(According to the test, only 1.8-1.21 players can access our server)
![image](https://github.com/user-attachments/assets/3b94dbb7-15e3-43f0-8f68-7626f9b61149)
And this is a common phenomenon, because my bungeecord didn't redirect me to any back-end server, that is to say, neither paper nor mohist can do it.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Not a viarewind issue, this is an intentional bungeecord feature that prevents the use of 1.7.x clients.

**Comment by MinecraftEarthVillage** [comment]
> 不是 viarewind 问题;这是一个有意的蹦极功能，可以阻止使用 1.7.x 客户端，并尽可能找到一个允许 1.7.x 客户端进入的分支。

How to repair it
