### ISSUE TITLE
update viaversion 5.1.0

### ISSUE THREAD

**Issue by franxyk** [ViaVersion/ViaRewind#546]
### `/viaversion dump` Output

https://dump.viaversion.com/87f8628bfc22a625aaeb2930fdda8f299dbe601f84d5cb0a27c68167a3a12361

### Console Error

io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j15/stub/java_base/J_L_CharSequence

### Bug Description

Update viaversion 5.1.0
io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j15/stub/java_base/J_L_CharSequence
mc client 1.7

### Steps to Reproduce

Join mc 1.7

### Expected Behavior

join normal

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.0): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by franxyk** [comment]
Everything is updated and the error continues.
