### ISSUE TITLE
ERROR IN Protocol1_8To1_7_6_10 IN REMAP OF PLAYER_POSITION (0x08)

### ISSUE THREAD

**Issue by clivet268** [ViaVersion/ViaRewind#547]
### `/viaversion dump` Output

https://dump.viaversion.com/8737cd3edca074f8e0c07c84cb640311935c000a94cbf4f984cd54c9ef219da1

### Console Error

```
Server side error:
https://mclo.gs/ZsTQq3Y

Client side error:

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at bok.a(SourceFile:271)
	at bok.a(SourceFile:220)
	at ban.a(SourceFile:1693)
	at ban.a(SourceFile:1651)
	at bll.a(SourceFile:118)
	at hd.a(SourceFile:70)
	at hd.a(SourceFile:13)
	at ej.a(SourceFile:166)
	at bcr.c(SourceFile:78)
	at ban.p(SourceFile:1342)
	at ban.ak(SourceFile:773)
	at ban.f(SourceFile:727)
	at net.minecraft.client.main.Main.main(SourceFile:148)

```

### Bug Description

Pre 1.8 players unable to join with above server error and IndexOutOfBoundsException on client side

Issue persists with latest version of viaversion, viabackwards and latest dev version of viarewind  and viarewind legacy support

### Steps to Reproduce

1. Log in with pre 1.8 client
2. Crash

### Expected Behavior

Player joins as normal

### Additional Server Info

Running purpur purpur-1.21.1-2287 with plugins: AntiCrasher, AuthMe, ChatFilter, Essentials, floodgate, Geyser-Spigot, GeyserUpdater, LuckPerms, ProtocolLib, SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion, XClaim, zDiscord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.4)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by clivet268** [comment]
https://dump.viaversion.com/8737cd3edca074f8e0c07c84cb640311935c000a94cbf4f984cd54c9ef219da1

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2287--07979c3%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please provide the full server log including the Via error

**Comment by clivet268** [comment]
This is not a ViaRewind specific issue, upon further testing this issue occurs when you enter a client in a higher version of Minecraft, set the render distance above 16 and then launch an instance of Minecraft on certain versions pre 1.8.

To fix just lower your render distance in the client before you try joining a world

**Comment by FlorianMichael** [comment]
Alright, thanks for explaining.
