### ISSUE TITLE
ERROR IN Protocol1_9To1_8 IN REMAP OF SET_PASSENGERS (0x40)

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaRewind#552]
### `/viaversion dump` Output

https://dump.viaversion.com/e043856b62ae6fecf72b28ec0fb99521de7da9574ba3e9fa8a1fb2b7138fd450

### Console Error

https://pastebin.com/raw/AgDWXknr

### Bug Description

Unsure on reproduction.

### Steps to Reproduce

Unsure on reproduction.

### Expected Behavior

No errors.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 1.21.3--53--aee6f7a%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--53--aee6f7a%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by andrewkm** [comment]
https://dump.viaversion.com/b2d78f036261397c043c86f63b5410646a67371da9a2447117fec422c8f58d90

**Comment by Barvalg** [comment]
![Platform: 1.21.3--63--4190ee7%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--63--4190ee7%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Should be fixed in dev builds :tm:
