### ISSUE TITLE
1.8 -> 1.7 WindowItems packet in enchantment table wiped the last items

### ISSUE THREAD

**Issue by LeeGodSRC** [ViaVersion/ViaRewind#553]
### `/viaversion dump` Output

https://dump.viaversion.com/7090cbabc17545507b0c04c8d94fe3e14616681d5e6fc3db8f6a9ffd023f56c5

### Bug Description

The WindowItems packet remapping for 1.8 -> 1.7.10 subtracts an additional item in the array, which causes the last item to be wiped.
Code: https://github.com/ViaVersion/ViaRewind/blob/a4b666724fae030f1d17afc67b730320db92ae4b/common/src/main/java/com/viaversion/viarewind/protocol/v1_8to1_7_6_10/rewriter/BlockItemPacketRewriter1_8.java#L137

### Steps to Reproduce

1. Login in your 1.8+ servers with 1.7.10 client
2. Fill your hotbar with items, and drag items within the inventory to produce a WindowItems packet
3. See the last item in the hotbar disappearing

Video:

https://github.com/user-attachments/assets/63e5aa68-b59d-4f16-bfd8-74d774c6afe0

### Expected Behavior

The item in the hotbar should not disappear randomly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--cSpigot--PaperEdition%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--cSpigot--PaperEdition%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 34 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.3): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by LeeGodSRC** [comment]
https://dump.viaversion.com/7324de6893b74cb6b3ff9894b4477f44f0301eed20459072422902280830e550
Still persists

**Comment by Barvalg** [comment]
![Platform: git--cSpigot--PaperEdition%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--cSpigot--PaperEdition%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
