### ISSUE TITLE
1.7 Absorption Hears Not Showing

### ISSUE THREAD

**Issue by blok601** [ViaVersion/ViaRewind#86]
Running the latest version of ViaRewind on a 1.8 PaperSpigot server. Absorption hearts don't show for either version players.

**Comment by blok601** [comment]
@Gerrygames Occasionally, the 1.8 players can see the hearts. Seems to be random but I could try to look into it more.

**Comment by WabMiran** [comment]
@Gerrygames fix please

**Comment by Gerrygames** [comment]
If even 1.8 players can't see the absorption hearts, the issue won't be 100% on ViaRewind. However there is an issue with absorption hearts. I think this is related to issues in ViaVersion (EntityTracker and/or packet ordering).
