### ISSUE TITLE
Unable to send 1.8 block crack particle packets to 1.7 clients

### ISSUE THREAD

**Issue by WhatATopic** [ViaVersion/ViaRewind#92]
I am using [DarkBlade12's Particle Effect API](https://github.com/DarkBlade12/ParticleEffect), when I send 1.8 block crack packets to the users, 1.8 users are able to see it while 1.7 users are not. If I switch from using ViaRewind to an old ProtocolSupport 1.8.8 build, the particles are visible to 1.8 and 1.7 users like it should. I would definitely rather use ViaRewind though over ProtocolSupport because I believe some 1.7 users are having connectivity issues now that I switched to ProtocolSupport.

**Comment by Gerrygames** [comment]
Could you provide the your code to send the particles? A vanilla /particle command would be even better.

**Comment by Bonista** [comment]
I can confirm this as well, using https://dev.bukkit.org/projects/particledemo.

Using the command "/particle display blockcrack 0 0 0 1 100 10 1:4" (where 1:4 is the 1.8.8 item, in this case Diorite), no particles show up on 1.7.10, but in the case of ProtocolSupport, they do.

@Gerrygames

**Comment by FlorianMichael** [comment]
Fixed with https://github.com/ViaVersion/ViaRewind/commit/2b791879d38a9e170689ea02f046861547b93db6
