### ISSUE TITLE
1.7 Clients Crashing

### ISSUE THREAD

**Issue by LinsaFTW** [ViaVersion/ViaRewind#96]
After 30 minutes aproximatelly, after changing worlds 4 - 8 times and playing a bit, 1.7 clients crash.

Client Crash Log: https://pastebin.com/TgyQkzYb

**Observations**

It happens at all kind of game servers, SkyWars, ArenaPvP, Capture The Wool.

When the player disconnects theres nothing on the console, just "disconnected".

**Plugins**

Plugins (32): LuckPerms, KillCommands, PlaceholderAPI, SmoothKnockback, DisableJoinMessage, MiRespawn, OldCombatMechanics, FastAsyncWorldEdit, AutoRestart, EffectLib, MicroJump, ViaVersion, VoidKill, Vault, CombatLogX, FastPot, ViaBackwards, aFreeze, ViaRewind, WorldEdit, Essentials, ViaRewind-Legacy-Support, ProtocolLib, AAC, CancelSounds, ProtocolSupportPotions, EssentialsChat, TitleManager, EssentialsMysqlStorage, CTWserver, AACAdditionPro, LiteBans

**Comment by LinsaFTW** [comment]
I just want to update that this wasnt fixed yet.

Server Version: 1.12.2 PaperSpigot

**Comment by Xernium** [comment]
If you can reproduce this without plugins that rely on ProtocolLib and without ProtocolSupport and a render distance between 5-8 then please go ahead and add that. Without we can’t really help much

**Comment by LinsaFTW** [comment]
I tested latest ViaRewind and seems fixed. I had tested a old version of ViaRewind.
